In [1]:
import os
import sys
import glob
from pathlib import Path
from astropy.io import fits
import numpy as np
from numpy import savetxt
import matplotlib
import matplotlib.pyplot as plt
from PyAstronomy import pyasl
from scipy.interpolate import interp1d
from astropy import units as u
from astropy.coordinates import SkyCoord
#install dustmaps from https://github.com/gregreen/dustmaps
from dustmaps.sfd import SFDQuery
import pandas as pd
from astropy.table import Table
import gc
matplotlib.use("Agg")
plt.ioff()
from PIL import Image
from matplotlib.offsetbox import OffsetImage, AnnotationBbox
from mpl_toolkits.axes_grid1.inset_locator import inset_axes
from matplotlib.cbook import get_sample_data
from astroquery.sdss import SDSS
import urllib.request
import warnings
from joblib import Parallel, delayed

In [2]:
storage_dir = os.path.join(os.path.expanduser("~"),'Data_storageHII/')
os.makedirs(storage_dir, exist_ok=True)

In [3]:
tex_folder = storage_dir + '/specTx_DR7/'
plots_folder =  storage_dir + '/specPlt_DR7/'


if (os.path.exists(tex_folder) == True and os.path.exists(plots_folder) == True):
    print('Folder for TEX set saving already created \n')
    print('Folder for PLOTS set saving already created \n')
else:
    if (os.path.exists(plots_folder) == False):
        print(f'Folder for PLOTS set saving created ({plots_folder}) \n')
        os.makedirs(plots_folder, exist_ok=True)
    if (os.path.exists(tex_folder) == False):
        print(f'Folder for TEX set saving created ({tex_folder}) \n')
        os.makedirs(tex_folder, exist_ok=True)
    else:
        print(f'Folder for TEX set saving created ({tex_folder}) \n')
        print(f'Folder for PLOTS set saving created ({plots_folder}) \n')
        os.makedirs(tex_folder, exist_ok=True)
        os.makedirs(plots_folder, exist_ok=True)

Folder for TEX set saving already created

Folder for PLOTS set saving already created

In [4]:
fits_folder = storage_dir + '/HIIG_specDR7/'
spec_list = os.listdir(fits_folder)
spec_list.remove('DOWNspec_listDR7.txt')
spec_list = sorted(spec_list)
len(spec_list)

121

In [5]:
def sdss_SpectralSynthesis_prepare_DR7(NAME,fits_folder,tex_folder):
    hdu = fits.open(fits_folder+NAME)
    data = hdu[0].data
    ##############################################################
    #Read the header
    
    zz = hdu[0].header['Z']
    RA = hdu[0].header['RA']
    DEC = hdu[0].header['DEC']
    
    c = SkyCoord(ra=RA*u.degree, dec=DEC*u.degree, frame='icrs')
    c.galactic
    
    sfd = SFDQuery()
    ebv01 = sfd(c.galactic)
    
    ##############################################################
    #Read the spectra, flux and wavelength
    
    flux = data[0]
    wav00 = hdu[0].header['COEFF0']
    wavdiff = hdu[0].header['COEFF1']

    hdu.close()
    
    waveair = 10**(wav00 + wavdiff*np.arange(len(flux)))
    
    waveobs = waveair/(1.0+2.735182E-4+131.4182/(waveair)**2 +2.76249E8/(waveair)**4)
    
    ##############################################################
    #redshift correction
    
    wave = waveobs/(1.0+zz)
    
    ##############################################################
    #Unredding the spectra
    
    fluxUnred = pyasl.unred(wave, flux, ebv=ebv01, R_V=3.1)
    
    ##############################################################
    #cosmoiogical flux corrextion
    
    flux_final = fluxUnred*(1.0+zz)**3
    
    ##############################################################
    #Change the wavelength to starlight input
    
    wave_in = int(wave[2])             #initial wavelength
    wave_fin = int(wave[len(wave)-2])  #final wavelength
    
    wave_new = np.arange(wave_in, wave_fin, 1)
    
    flux_interpolate = interp1d(wave, flux_final, kind='quadratic')
    flux_starlight = flux_interpolate(wave_new)
    
    ##############################################################
    #Crate an output array
    
    table = list(zip(wave_new, flux_starlight))
    
    # Save the file

    new_name  = tex_folder   + (NAME.replace('.fit',"")) 
    savetxt(new_name + '.tex', table, fmt='%8.4f', delimiter='    ')
    
    return f"{NAME} spectra saved in {new_name} .tex"

In [6]:
tmp = [sdss_SpectralSynthesis_prepare_DR7(t,fits_folder,tex_folder) for t in spec_list]

In [7]:
HIIG_IMG_folder = storage_dir + '/HIIG_img/'


if (os.path.exists(HIIG_IMG_folder) == True ):
    print('Folder for HIIG SDSS images set saving already created \n')
else:
    print(f'Folder for HIIG SDSS images set saving created ({HIIG_IMG_folder}) \n')
    os.makedirs(HIIG_IMG_folder, exist_ok=True)

Folder for HIIG SDSS images set saving already created

In [8]:
catalog_file = os.path.join(storage_dir,"gal_info_dr7_v5_2.fit.gz")
catalog = catalog_file
catalog=Table.read(catalog)
w=((catalog['RA']!=catalog['DEC']) & (catalog['RA']>0) & ((catalog['DEC']>=-90) | (catalog['DEC']<=90)) & (catalog['Z']>=0) & ( catalog['Z'] != float('nan') ) & ( catalog['DEC'] != float('nan') ) & ( catalog['RA'] != float('nan') ))
reduced_cat=catalog[w]

In [10]:
def HIIG_image_retriever(NAME,fits_folder,img_folder,catalog_table):
    warnings.filterwarnings('ignore')
    reduced_cat=catalog_table

    hdu = fits.open(fits_folder+NAME)
    
    PLATE = hdu[0].header['PLATEID']
    FIBER = hdu[0].header['FIBERID']
    MJD = hdu[0].header['MJD']

    IDs = SDSS.query_specobj(plate = int(PLATE), mjd = int(MJD), fiberID = int(FIBER))

    status = str(type(IDs))

    if (status != "<class 'NoneType'>"):
        ra = float(SDSS.query_specobj(plate = int(PLATE), mjd = int(MJD), fiberID = int(FIBER))['ra'])
        dec = float(SDSS.query_specobj(plate = int(PLATE), mjd = int(MJD), fiberID = int(FIBER))['dec'])
    else:
        ra = np.array(reduced_cat[(reduced_cat['PLATEID']==int(PLATE)) & (reduced_cat['FIBERID']==int(FIBER)) & (reduced_cat['MJD']==int(MJD))]['RA'])[0]
        dec = np.array(reduced_cat[(reduced_cat['PLATEID']==int(PLATE)) & (reduced_cat['FIBERID']==int(FIBER)) & (reduced_cat['MJD']==int(MJD))]['DEC'])[0]



    imgURL = f"http://skyserver.sdss.org/dr16/SkyServerWS/ImgCutout/getjpeg?TaskName=Skyserver.Explore.Image&ra={ra}&dec={dec}&scale=0.2&width=200&height=200&opt=G"

    result = SDSS.query_specobj(plate=PLATE,mjd=MJD,fiberID=FIBER,fields = ['specobjid'])

    status = str(type(result))

    if (status != "<class 'NoneType'>"):
        result = str(result['specobjid'][0])
        image_spec = f'https://skyserver.sdss.org/dr16/en/get/SpecById.ashx?id={result}'
        if os.path.exists(f"{img_folder}/specimage_{NAME}.jpeg")!=True:
            urllib.request.urlretrieve(image_spec,f"{img_folder}/specimage_{NAME}.jpeg")
        alert = 0
    else:
        alert = 'No hay imagen de este espectro'



    hdu.close()

    

    if os.path.exists(f"{img_folder}/{NAME}.jpeg")!=True:
        urllib.request.urlretrieve(imgURL,f"{img_folder}/{NAME}.jpeg")
    




    return f"{PLATE},{FIBER},{MJD},{ra},{dec},{alert}\n"


#tmp = Parallel(n_jobs=-1)(delayed(HIIG_image_retriever)(e,fits_folder,HIIG_IMG_folder,reduced_cat) for e in spec_list)

for e in range(len(spec_list)):
    tmp = e + 0 #e + 94 
    print(HIIG_image_retriever(spec_list[tmp],fits_folder,HIIG_IMG_folder,reduced_cat),e)

267,421,51608,147.597162628828,0.708127177268213,0
 0
341,606,51690,200.94776134765,-1.54777983724568,0
 1
388,457,51793,1.73758544441037,0.857230431344045,0
 2
415,141,51810,53.8609151908011,-0.636533804183749,0
 3
381,370,51811,346.765651605092,1.21977224962501,0
 4
382,328,51816,348.675639921919,1.10584233786806,0
 5
410,220,51816,43.6088418917947,-0.689572212220896,0
 6
418,302,51817,8.07750453626596,15.0039393153258,0
 7
400,441,51820,23.4359526850297,0.953121139115853,0
 8
429,495,51820,26.779343875627,13.9414254674982,0
 9
384,281,51821,352.402311298105,-1.18250049873833,0
 10
447,361,51877,131.365038079905,53.1480248071366,0
 11
442,156,51882,126.377825178692,50.8012690367536,0
 12
481,483,51908,148.112334702567,2.29996410813119,0
 13
270,617,51909,153.62905412036,0.798627952656554,0
 14
485,550,51909,142.52681944382,60.4481509142727,0
 15
275,445,51910,161.478244311513,1.06827527952586,0
 16
456,195,51910,41.2236197598615,-8.36054102570387,0
 17
456,306,51910,40.217485051174,-8.47428151092793,0
 18
465,524,51910,62.4067794675881,-5.30161979054662,0
 19
394,472,51913,12.9470306991655,0.161116101734004,0
 20
488,439,51914,152.652595599468,64.2118356009627,0
 21
459,253,51924,47.5997860893018,-8.57580343695024,0
 22
458,185,51929,45.8392181918358,-7.98978855825929,0
 23
490,128,51929,164.424774637009,65.5943926257816,0
 24
472,546,51955,139.217647636228,0.520534667169167,0
 25
283,389,51959,175.55166625976562,0.3340807855129242,No hay imagen de este espectro
 26
549,621,51981,130.124643778074,47.119515965845,0
 27
556,224,51991,144.556236238901,54.4736362531743,0
 28
337,97,51997,193.27488552987,-3.2163463587691,0
 29
474,610,52000,142.3266458722,0.470340475344925,0
 30
652,90,52138,4.19900692273353,-10.7950668290856,0
 31
375,118,52140,336.292217144073,-0.198026594582048,0
 32
375,348,52140,334.599403003796,0.655117186877085,0
 33
653,462,52145,5.91504256562465,-9.81353480088271,0
 34
639,143,52146,319.759502958771,-7.70743968646834,0
 35
639,242,52146,318.862827696552,-7.99760858853458,0
 36
658,312,52146,14.0094359946736,-10.1693922667689,0
 37
662,466,52147,23.2439274152965,-8.89383954755804,0
 38
668,89,52162,35.1569241414867,-9.48529387084885,0
 39
668,152,52162,34.7204381427193,-9.20519703237608,0
 40
637,399,52174,315.309983635999,-5.91952600923344,0
 41
637,523,52174,316.256286649838,-6.37745605070674,0
 42
664,355,52174,25.4050906599671,-9.24310377449046,0
 43
640,267,52178,320.88629211919,-7.80862250317138,0
 44
564,216,52224,131.059269550442,2.43923267628427,0
 45
564,283,52224,130.233425813693,2.34193997659028,0
 46
753,94,52233,6.10809542060741,14.0695495109622,0
 47
501,602,52235,151.943818352223,2.87455625869643,0
 48
566,497,52238,136.379496383194,3.59178568418219,0
 49
741,279,52261,342.917982231792,13.4537117003387,0
 50
740,259,52263,341.487216250317,12.839548791069,0
 51
742,161,52263,345.323539537018,13.8750682424864,0
 52
742,179,52263,345.348309197426,13.5540880172263,0
 53
769,100,52282,147.882377573571,52.9933279653564,0
 54
505,228,52317,158.550948364493,1.71362726467767,0
 55
859,70,52317,120.002908105926,27.778350381329,0
 56
861,489,52318,123.392369353295,31.547822150694,0
 57
575,521,52319,156.121872398115,5.41416579320963,0
 58
578,60,52339,161.240820365874,3.88698524967083,0
 59
507,87,52353,163.380874504651,1.29456286110105,0
 60
507,521,52353,163.043392358698,3.45367832880545,0
 61
580,302,52368,163.358407349486,4.50403552200196,0
 62
854,514,52373,206.381265464752,4.70909440615118,0
 63
920,575,52411,222.022421282705,-1.18269137235429,0
 64
976,600,52413,258.152638846607,32.2759515230224,0
 65
735,461,52519,332.011976206163,13.2262471368087,0
 66
987,440,52523,320.183136502246,1.00191059337383,0
 67
899,594,52620,138.645621619008,47.0353238841518,0
 68
999,517,52636,158.368843879236,7.13382802868978,0
 69
1003,327,52641,164.92068135733,8.01580628929196,0
 70
1001,363,52670,161.98300556773,7.66422462279093,0
 71
934,369,52672,131.64334617991,36.4390915106511,0
 72
941,109,52709,147.041227476213,42.9537564011014,0
 73
1216,619,52709,148.939831354241,41.5749624798775,0
 74
1195,60,52724,141.420570962018,6.52133290833426,0
 75
1240,340,52734,158.788856385291,9.75465295692724,0
 76
1302,639,52763,141.954953128565,8.67698904940813,0
 77
1177,556,52824,325.961904862792,-7.33434106299438,0
 78
1269,177,52937,130.579483885863,30.1176623489611,0
 79
1582,335,52939,117.02626837124,19.5297104526044,0
 80
1585,261,52962,123.515734491529,23.8913857165456,0
 81
1594,563,52992,145.719928157021,35.7905571698772,0
 82
1745,463,53061,152.987846286344,13.1394616668371,0
 83
1745,475,53061,152.677242609419,12.9213209850819,0
 84
1758,338,53084,126.333814823016,8.45642583970685,0
 85
1601,168,53115,162.121764419201,11.255589923972,0
 86
1697,415,53142,198.146470671063,12.9620457025874,0
 87
1612,73,53149,183.372906574455,11.6824749006223,0
 88
1781,55,53297,124.406602111505,52.043424036998,0
 89
1922,588,53315,121.581228407964,19.8242505111669,0
 90
1921,281,53317,117.445868047152,15.6703657715983,0
 91
1927,6,53321,126.844057066824,20.436890586719,0
 92
1749,26,53357,162.787018186912,13.3244405033349,0
 93
1749,499,53357,161.724945603128,13.7793710275593,0
 94
1872,526,53386,123.586628160746,57.8355437809631,0
 95
1935,204,53387,136.075489111866,26.0184299666772,0
 96
1945,346,53387,145.726141539347,34.0699893569975,0
 97
1947,448,53431,147.503220467538,30.0613881426123,0
 98
1946,609,53432,148.11472597429,32.4692432853759,0
 99
1983,308,53442,162.670149947092,34.4964952502011,0
 100
1981,438,53463,161.848367195774,30.3622991323676,0
 101
1695,627,53473,195.330248631425,12.6665274644088,0
 102
2132,241,53493,215.928635870339,22.9580007646398,0
 103
2112,557,53534,201.455939326735,33.0651073346478,0
 104
2284,545,53708,136.278595965378,22.6427524199796,0
 105
2278,411,53711,130.001550151982,18.0919350511313,0
 106
2293,5,53730,143.600361761916,22.4229482950441,0
 107
2347,501,53757,152.900226191878,26.5076348729622,0
 108
2361,523,53762,145.002159252884,20.5229180197517,0
 109
2372,508,53768,151.835372233101,19.563771071423,0
 110
2373,560,53768,153.744333083821,19.5387552785828,0
 111
2356,172,53786,159.360613923123,27.1332450562639,0
 112
2353,585,53794,158.112320858702,27.298677845718,0
 113
2426,15,53795,130.587253480993,11.8334411955499,0
 114
2439,372,53795,139.170750209393,18.4688585766741,0
 115
2427,117,53815,129.941767106108,14.0092246277788,0
 116
2430,117,53815,133.090475493234,12.2810385835711,0
 117
2483,254,53852,162.635467975454,15.6350884314661,0
 118
2489,123,53857,167.160416589826,22.6360485538983,0
 119
2208,306,53880,245.469056235267,15.3155453947077,0
 120

In [11]:
hdu = fits.open(fits_folder+spec_list[0])
hdu[0].header

SIMPLE  =                    T
BITPIX  =                  -32
NAXIS   =                    2
NAXIS1  =                 3818
NAXIS2  =                    4
TAI     =        4458951910.50 / 1st row - Number of seconds since Nov 17 1858
RA      =            147.73167 / 1st row - Right ascension of telescope boresigh
DEC     =           -0.033455  / 1st row - Declination of telescope boresight (d
EQUINOX =              2000.00 /
RADECSYS= 'FK5     '           /
AZ      =        113.863787882 / 1st row - Azimuth  (encoder) of tele (0=N?) (de
ALT     =        56.6194209010 / 1st row - Altitude (encoder) of tele        (de
AIRMASS =        1.20178423413 /
FOCUS   = -999999999999.999999 / 1st row - Focus piston (microns?)
DATE-OBS= '2000-03-05'         / 1st row - TAI date
TAIHMS  = '05:18:10.29'        / 1st row - TAI time (HH:MM:SS.SS) (TAI-UT = appr
TIMESYS = 'tai     '           / TAI, not UTC
TAI-BEG =        4458949291.00 / Exposure Start Time
TAI-END =        4458953286.00 / Exposure End Time
MJD     =                51608 / MJD of observation
MJDLIST = '51608   '           /
VERSION = 'v3_10_0 '           / version of IOP
CAMVER  = 'SPEC2 v4_5'         / Camera code version
OBSERVER= 'sjnk    '
TELESCOP= 'SDSS 2.5-M'         / Sloan Digital Sky Survey
NEXP    =                   16 / Number of exposures in this file
EXPID00 = 'b1-51608-00002728-00002726-00002727' / ID string for exposure 0
EXPID01 = 'b1-51608-00002729-00002726-00002727' / ID string for exposure 1
EXPID02 = 'b1-51608-00002730-00002726-00002727' / ID string for exposure 2
EXPID03 = 'b1-51608-00002731-00002726-00002727' / ID string for exposure 3
EXPID04 = 'b2-51608-00002728-00002726-00002727' / ID string for exposure 4
EXPID05 = 'b2-51608-00002729-00002726-00002727' / ID string for exposure 5
EXPID06 = 'b2-51608-00002730-00002726-00002727' / ID string for exposure 6
EXPID07 = 'b2-51608-00002731-00002726-00002727' / ID string for exposure 7
EXPID08 = 'r1-51608-00002728-00002726-00002727' / ID string for exposure 8
EXPID09 = 'r1-51608-00002729-00002726-00002727' / ID string for exposure 9
EXPID10 = 'r1-51608-00002730-00002726-00002727' / ID string for exposure 10
EXPID11 = 'r1-51608-00002731-00002726-00002727' / ID string for exposure 11
EXPID12 = 'r2-51608-00002728-00002726-00002727' / ID string for exposure 12
EXPID13 = 'r2-51608-00002729-00002726-00002727' / ID string for exposure 13
EXPID14 = 'r2-51608-00002730-00002726-00002727' / ID string for exposure 14
EXPID15 = 'r2-51608-00002731-00002726-00002727' / ID string for exposure 15
EXPT_B1 =              3600.00 / b1 camera exposure time (seconds)
EXPT_B2 =              3600.00 / b2 camera exposure time (seconds)
EXPT_R1 =              3600.00 / r1 camera exposure time (seconds)
EXPT_R2 =              3600.00 / r2 camera exposure time (seconds)
EXPTIME =              3600.00 / Minimum of exposure times for all cameras
SPCOADD = 'Mon Sep  1 20:25:42 2003' / SPCOADD finished
FLAVOR  = 'science '           / Flavor of this sequence (e.g., dome flat, etc.)
QUALITY = 'excellent'          / night/image quality
RADEG   = 1.47733165000000E+02 / Right Ascension. (degrees)
DECDEG  = -3.0653000000000E-02 / Declination. (degrees)
PLATEID =                  267 / Plate Id
TILEID  =                  121 / Tile Id
CARTID  =                    3 /Cartridge used in this plugging
MAPID   =              5160303 / Map Id
NAME    = '0267-51603-03'      / Name of target; PlateId-MJD-Mapper ReRun
NGUIDE  =              29.0000 / Number of guider frames during exposure
SEEING20=        1.72728093465 / 20% seeing during exposure (arcsec)
SEEING50=        1.84960465806 / 50% seeing during exposure (arcsec)
SEEING80=        1.96940994406 / 80% seeing during exposure (arcsec)
RMSOFF20=       0.263027454968 / 20% RMS offset of guide fibers (arcsec)
RMSOFF50=       0.395028603438 / 50% RMS offset of guide fibers (arcsec)
RMSOFF80=       0.517532368831 / 80% RMS offset of guide fibers (arcsec)
COLBIN  =                    1 / Binning factor perpendicular to the columns
ROWBIN  =                    1 / Binning factor perpendicular to the rows
PROGRAM = 'binning 1   1 '     / Identifying name for CCD program
SECFOCUS= 1.50000000000000E+03 / Secondary Mirror Position as reported by TCC
GUIDEIMG= '/data/spectro/guider/gimg0158.fits' / Last archived guider image
WTIME   =        952234312.086 / weatherData(timeStamp)
AIRTEMP =        5.25766627911 / weatherData(airtemp)
DEWPOINT=       -8.73495113036 / weatherData(dewpoint)
DEWDEP  =        14.0166732195 / weatherData(dewpointDep)
DUSTA   =        22984.6371677 / weatherData(dusta)
DUSTB   =        566.638421723 / weatherData(dustb)
DUSTC   =        23290.0617870 / weatherData(dustc)
DUSTD   =        584.570525241 / weatherData(dustd)
GUSTD   = 1.57100000000000E+02 / weatherData(gustd)
GUSTS   =        20.5387227346 / weatherData(gusts)
HUMIDITY=        35.5975343901 / weatherData(humidity)
HUMIDOUT=        35.2379478008 / weatherData(humidout)
PRESSURE=        21.3420836621 / weatherData(pressure)
WINDD   =        133.466367847 / weatherData(windd)
WINDS   =        15.7425033189 / weatherData(winds)
VERSIDL = '5.4     '           / Version of IDL
VERSUTIL= 'v4_10_1 '           / Version of idlutils
VERSREAD= 'v4_10_2 '           / Version of idlspec2d for pre-processing raw dat
VERS2D  = 'v4_10_2 '           / Version of idlspec2d for 2D reduction
VERSCOMB= 'v4_10_2 '           / Version of idlspec2d for combining multiple spe
VERSLOG = 'Unknown '           / Version of SPECLOG product
VERSFLAT= 'v1_5    '           / Version of SPECFLAT product
OPBC    = 'opBC-50000.par'     /
OPCONFIG= 'opConfig-50000.par' /
OPECALIB= 'opECalib-51577.par' /
XSIGMA  =       0.944547515800 /
XSIGMIN =       0.903111000000 /
XSIGMAX =        1.00733995438 /
WSIGMA  =       0.952430101596 /
WSIGMIN =       0.871273000000 /
WSIGMAX =        1.01359999180 /
PLUGFILE= 'plPlugMapM-0267-51603-03.par' /
LAMPLIST= 'lamphgcdne.dat'     /
SKYLIST = 'skylines.dat'       /
HELIO_RV=        7.16623392617 / Heliocentric correction (added to velocities)
VACUUM  =                    T / Wavelengths are in vacuum
SFLATTEN=                    T / Superflat has been applied
PSFSKY  =                    3 / Order of PSF skysubtraction
SKYCHI2 =       0.937947027897 / Mean chi^2 of sky-subtraction
SCHI2MIN=       0.885463000000 /
SCHI2MAX=       0.986218000000 /
PREJECT =             0.200000 / Profile area rejection threshold
SPEC1_G =              41.7634 /(S/N)^2 for spec  1 at mag 20.20
SPEC1_R =              47.9548 /(S/N)^2 for spec  1 at mag 20.25
SPEC1_I =              38.2125 /(S/N)^2 for spec  1 at mag 19.90
SPEC2_G =              42.7072 /(S/N)^2 for spec  2 at mag 20.20
SPEC2_R =              44.7397 /(S/N)^2 for spec  2 at mag 20.25
SPEC2_I =              37.1950 /(S/N)^2 for spec  2 at mag 19.90
LOWREJ  =                    5 / Extraction: low rejection
HIGHREJ =                    8 / Extraction: high rejection
SCATPOLY=                    5 / Extraction: Order of scattered light polynomial
PROFTYPE=                    3 / Extraction profile: 1=Gaussian
NFITPOLY=                    1 / Extraction: Number of parameters in each profil
XCHI2   =        1.22530998889 / Extraction: Mean chi^2
XCHI2MIN=              1.07531 /
XCHI2MAX=              1.35970 /
ROFFSET1=            0.0286449 /Mean r-band mag difference (spectro - photo)
RSIGMA1 =            0.0761011 /Stddev of r-band mag difference (spectro - photo
GROFF1  =           -0.0713897 /Mean (g-r) color difference (spectro - photo)
GRSIGMA1=            0.0806137 /Stddev of (g-r) color difference (spectro - phot
ROFFSET2=            0.0608601 /Mean r-band mag difference (spectro - photo)
RSIGMA2 =            0.0727158 /Stddev of r-band mag difference (spectro - photo
GROFF2  =           -0.0391065 /Mean (g-r) color difference (spectro - photo)
GRSIGMA2=            0.0643332 /Stddev of (g-r) color difference (spectro - phot
NWORDER =                    2 / Linear-log10 coefficients
WFITTYPE= 'LOG-LINEAR'         / Linear-log10 dispersion
UNAME   = 'sdssdp30.fnal.gov'  /
SMEARUSE=                    F / Smear available?
TSOBJNAM= 'tsObj-0267-51603-03.fit' / Name of tsObj file used
SFD_USED=                    T / SFD dust maps used?
XYGRSIG1=            0.0372534 / Sigma of (g-r) offsets as a fcn of plate x/y
XYGRSIG2=            0.0430895 / Sigma of (g-r) offsets as a fcn of plate x/y
MPGRSIG1=             0.124436 / Sigma of (g-r)_model - (g-r)_photo Spec 1
MPGRSIG2=            0.0663546 / Sigma of (g-r)_model - (g-r)_photo Spec 2
MPGROFF1=           -0.0920109 / Mean of (g-r)_model - (g-r)_photo of Spec 1
MPGROFF2=           -0.0706763 / Mean of (g-r)_model - (g-r)_photo of Spec 2
FBADPIX =            0.0124276 / Fraction of bad pixels
FBADPIX1=            0.0112272 / Fraction of bad pixels on spectro-1
FBADPIX2=            0.0136279 / Fraction of bad pixels on spectro-2
WAT0_001= 'system=linear'      /
WAT1_001= 'wtype=linear label=Wavelength units=Angstroms' /
CRPIX1  =                    1 / Starting pixel (1-indexed)
CTYPE1  = 'LINEAR  '           /
DC-FLAG =                    1 / Log-linear flag
PIXMIN  = 0.00000000000000E+00 / Place Holder
PIXMAX  = 2.04700000000000E+03 / Place Holder
ARRAY1  = 'SPECTRUM'           / units of (10^-17 erg/s/cm^2/A
ARRAY2  = 'CONTINUUM-SUBTRACTED SPECTRUM' / units of 10^-17 erg/s/cm^2/A
ARRAY3  = 'ERROR   '           / units of 10^-17 erg/s/cm^2/A
ARRAY4  = 'MASK    '           / mask bit array
BUNIT   = '1.0E-17 erg/cm/s/Ang' / units
SN_G    = 1.33800000000000E+01 / Median S/N ration ig g'
MAG_G   = 1.89834000000000E+01 / Synthetic magnitude in g'
SN_R    = 1.25973000000000E+01 / Median S/N ratio in r'
MAG_R   = 1.91411000000000E+01 / Synthetic magnitude in r'
SN_I    = 1.08993000000000E+01 / Median S/N ratio in i'
MAG_I   = 1.86198000000000E+01 / Synthetic magnitude in i'
SCI_SN  = 0.00000000000000E+00 / Science signal to noise ratio
SMEAR_SN= 0.00000000000000E+00 / Smear signal to noise ratio
SM_LEG_0= 0.00000000000000E+00 / 1st legendre coeff. for smear correct
SM_LEG_1= 0.00000000000000E+00 / 2nd legendre coeff. for smear correct
SM_LEG_2= 0.00000000000000E+00 / 3rd legendre coeff. for smear correct
OBJID   = ' 756 1 5 212 129'   / run rerun camcol field objID
MAG     = ' 18.9573 18.7503 18.897 18.3499 18.8371' / fiber Mags
OBJTYPE = 'QSO     '           / object Type
RAOBJ   = 1.47597180000000E+02 / RA(deg) of object
DECOBJ  = 7.08132960000000E-01 / DEC(deg) of object
XFOCAL  = -2.9601185000000E+01 / X position in Focal plane
YFOCAL  = 1.60809600000000E+02 / Y position in focal plane
PRIMTARG=              1048580 / primary Target Flag
SECTARGE=                    0 / Secondary Target Flag
FIBERID =                  421 / fiber ID
SPECID  =                    2 / spectrograph ID
NGOOD   =                 3818 / Number of Good Pixels
VERS_1D = 'v5_9_4  '           / Version of Spectro1d
BESTTEMP=                   29 / Best cross-correlation template
COEFF0  = 3.58220000000000E+00 / Center wavelength (log10) of first pi
COEFF1  = 1.00000000000000E-04 / Log10 dispersion per pixel
CRVAL1  = 3.58220000000000E+00 / Iraf zero point
CD1_1   = 1.00000000000000E-04 / Iraf dispersion
1D_PDATE= '06/07/05:23:19:35'  / 1D Processing/last Modification date
SPEC_CLN=                    2 / Spectral Classn
VEL_DIS = -9.9990000000000E+03 / Velocity dispersion (km/s)
VEL_DISE= -9.9990000000000E+03 / Error on Velocity Dispersion (km/s)
Z       = 9.77184000000000E-02 / Final redshift
Z_ERR   = 7.56864000000000E-04 / Redshift error
Z_CONF  = 9.99952000000000E-01 / Redshift confidence
Z_STATUS=                    4 / Redshift Status
Z_WARNIN=                  512 / Redshift Warning Flags
ECLASS  = 9.08674000000000E-01 / galaxy classification parameter
ECOEFF1 = 4.80691000000000E-01 / 1st expansion coefficient
ECOEFF2 = -6.1665700000000E-01 / 2nd expansion coefficient
ECOEFF3 = -5.0340500000000E-01 / 3rd expansion coefficient
ECOEFF4 = 3.46761000000000E-01 / 4th expansion coefficient
ECOEFF5 = -1.2251600000000E-01 / 5th expansion coefficient
EXTEND  =                    T / Binary tables follow

In [12]:
def spec_plotter(name,
                figsize=(48, 18),        # << mucho más pequeño
                render_dpi=100,          # DPI de canvas
                save_dpi=100,            # DPI del archivo final
                tol=1.0,                  # tolerancia en Å para localizar líneas           
                img_folder='',
                fits_folder='',
                tex_folder='',
                plots_folder=''):

    ll = ['HB','O[III]a','O[III]b','Ha']
    lines = {
    "HB": [4862.721, r'H-$\beta$', 4862.0000],
    "O[III]a": [4960.295, r'O[III]$\lambda$4959', 4960.0000],
    "O[III]b": [5008.239, r'O[III]$\lambda$5007', 5007.0000],
    "Ha": [6562.801, r'H-$\alpha$', 6562.0000]
    }



    # Construye paths/nombres como en tu versión
    #base = (name.replace('.fit', '')) + ".tex"
    #base = base.replace(".tex", f"._{str(counter)}_.tex")

    base_fit = fits_folder + name
    base_tex = tex_folder + name.replace('.fit', '.tex')
    base_img = img_folder + name.replace('.fit', '.fit.jpeg')



    hdu = fits.open(base_fit)
    
    plateid,fiberid,mjd,Z,Zerr,ra,dec = hdu[0].header['PLATEID'],hdu[0].header['FIBERID'],hdu[0].header['MJD'],hdu[0].header['Z'],hdu[0].header['Z_ERR'],hdu[0].header['RAOBJ'],hdu[0].header['DECOBJ']

    hdu.close()

    data = Table.read(base_tex, format='ascii', fast_reader=True)
    lam = np.asarray(data['col1'], dtype=float)
    flux = np.asarray(data['col2'], dtype=float)

    fig, ax = plt.subplots(figsize=figsize, dpi=render_dpi)
    ax.spines.right.set_visible(False)
    ax.spines.top.set_visible(False)

    # Trazado principal
    ax.plot(lam, flux, label='HIIG Flux', lw=2.0, color = 'green')

    ax.set_ylabel(r"$F_{\lambda}\ \left[10^{-17}\ {\rm erg\ s}^{-1}\ {\rm cm}^{-2}\ \AA^{-1}\right]$",
                    style='oblique', family='serif', size = 35)
    ax.set_xlabel(r'Rest Wavelength [$\AA$]',
                    style='oblique', family='serif', size = 35)
    
    # Anotación de líneas (con tolerancia en lugar de igualdad exacta)
    for key in ll:
        rest = lines[key][2]
        idx = np.where(np.abs(lam - rest) <= 3)[0]
        if idx.size:
            i0 = idx[len(idx)//2]
            i1, i2 = max(i0 - 10, 0), min(i0 + 10, flux.size)
            selec_flux_max = float(flux[i1:i2].max()) + 0.05 * (flux.max() - flux.min())
            x = rest - (100 if key in ('O[III]a', 'O[III]b') else 30)
            ax.text(x, selec_flux_max, f"{lines[key][1]}",
                    fontsize=30,
                    bbox={'facecolor': '#F4F1BB', 'alpha': 0.5, 'boxstyle': "round,pad=0.2", 'ec': 'none'})
    
    ax.tick_params(axis='x', labelsize=20)
    ax.tick_params(axis='y', labelsize=20)

    ax.tick_params(axis='x', labelrotation=90)
    ax.set_xlim(3500, 7500)
    #ax.set_ylim(0, max(float(flux.max()), 1.0) * 1.05)
    ax.set_yscale('log')
    ax.grid(True, which="both", ls=":", linewidth=0.9)

    sym = [r"$\alpha$",r"$\delta$",r"$z$",r"$\mathcal{PLATE}$",r"$\mathcal{MJD}$",r"$\mathcal{FIBERID}$",r"$\mathbf{name}$",r"$\pm$"]

    leg_title = f'{sym[6]}: {name}\n {sym[0]}: {ra}°\n {sym[1]}: {dec}°\n {sym[2]}: {Z}{sym[7]}{Zerr}\n {sym[3]}: {plateid}\n {sym[4]}: {mjd}\n {sym[5]}: {fiberid}\n'

    #leg_title = f"PLATEID = {plateid}\nMJD = {mjd}\nFIBERID = {fiberid}\nZ = {Z}\n"
    ax.legend(title=leg_title, loc='lower left', prop={'size': 20}, title_fontsize=30)


    image_path = plt.imread(get_sample_data(base_img))


    inset_ax = inset_axes(ax, width="30%", height="30%",loc='upper left')
    inset_ax.imshow(image_path)

    inset_ax.axis('off')



    os.makedirs(plots_folder, exist_ok=True)
    outfile = os.path.join(plots_folder, name.replace('.fit', '.png'))

    # Guarda (si "tight" no es imprescindible, quítalo para ahorrar un poco más)
    fig.savefig(outfile, dpi=save_dpi, bbox_inches='tight', transparent=False)

    # Cierra y limpia SOLO esta figura
    plt.close(fig)
    del fig, ax, data, lam, flux
    gc.collect()
    return f"Done for {name.replace('.fit', '.png')} "

spec_plotter(spec_list[50],img_folder=HIIG_IMG_folder,fits_folder=fits_folder,tex_folder=tex_folder,plots_folder=plots_folder)

'Done for spSpec-52261-0741-279.png '

In [13]:
tmp = Parallel(n_jobs=-1)(delayed(spec_plotter)(e,img_folder=HIIG_IMG_folder,fits_folder=fits_folder,tex_folder=tex_folder,plots_folder=plots_folder) for e in spec_list)

In [14]:
hdu = fits.open(fits_folder+spec_list[93])
hdu[0].header

SIMPLE  =                    T
BITPIX  =                  -32
NAXIS   =                    2
NAXIS1  =                 3829
NAXIS2  =                    4
TAI     =        4609853174.00 / 1st row - Number of seconds since Nov 17 1858
RA      =            161.78680 / 1st row - Right ascension of telescope boresigh
DEC     =            13.844803 / 1st row - Declination of telescope boresight (d
EQUINOX =              2000.00 /
RADECSYS= 'FK5     '           /
AZ      =        26.5012390656 / 1st row - Azimuth  (encoder) of tele (0=N?) (de
ALT     =        68.3792181922 / 1st row - Altitude (encoder) of tele        (de
AIRMASS =        1.08547404962 /
FOCUS   =           -30.000000 / 1st row - Focus piston (microns?)
DATE-OBS= '2004-12-10'         / 1st row - TAI date
TAIHMS  = '12:03:16.86'        / 1st row - TAI time (HH:MM:SS.SS) (TAI-UT = appr
TIMESYS = 'tai     '           / TAI, not UTC
TAI-BEG =        4609395416.00 / Exposure Start Time
TAI-END =        4610086279.00 / Exposure End Time
MJD     =                53357 / MJD of observation
MJDLIST = '53349 53357'        /
VERSION = 'v3_143_0'           / version of IOP
CAMVER  = 'SPEC1 v4_8'         / Camera code version
OBSERVER= 'jurek   '
OBSCOMM = 'science '
TELESCOP= 'SDSS 2.5-M'         / Sloan Digital Sky Survey
NEXP    =                   20 / Number of exposures in this file
EXPID00 = 'b1-53349-00029780-00029778-00029779' / ID string for exposure 0
EXPID01 = 'b1-53349-00029781-00029778-00029779' / ID string for exposure 1
EXPID02 = 'b1-53357-00029944-00029942-00029943' / ID string for exposure 2
EXPID03 = 'b1-53357-00029945-00029942-00029943' / ID string for exposure 3
EXPID04 = 'b1-53357-00029946-00029942-00029943' / ID string for exposure 4
EXPID05 = 'b2-53349-00029780-00029778-00029779' / ID string for exposure 5
EXPID06 = 'b2-53349-00029781-00029778-00029779' / ID string for exposure 6
EXPID07 = 'b2-53357-00029944-00029942-00029943' / ID string for exposure 7
EXPID08 = 'b2-53357-00029945-00029942-00029943' / ID string for exposure 8
EXPID09 = 'b2-53357-00029946-00029942-00029943' / ID string for exposure 9
EXPID10 = 'r1-53349-00029780-00029778-00029779' / ID string for exposure 10
EXPID11 = 'r1-53349-00029781-00029778-00029779' / ID string for exposure 11
EXPID12 = 'r1-53357-00029944-00029942-00029943' / ID string for exposure 12
EXPID13 = 'r1-53357-00029945-00029942-00029943' / ID string for exposure 13
EXPID14 = 'r1-53357-00029946-00029942-00029943' / ID string for exposure 14
EXPID15 = 'r2-53349-00029780-00029778-00029779' / ID string for exposure 15
EXPID16 = 'r2-53349-00029781-00029778-00029779' / ID string for exposure 16
EXPID17 = 'r2-53357-00029944-00029942-00029943' / ID string for exposure 17
EXPID18 = 'r2-53357-00029945-00029942-00029943' / ID string for exposure 18
EXPID19 = 'r2-53357-00029946-00029942-00029943' / ID string for exposure 19
EXPT_B1 =              6600.50 / b1 camera exposure time (seconds)
EXPT_B2 =              6600.50 / b2 camera exposure time (seconds)
EXPT_R1 =              6600.50 / r1 camera exposure time (seconds)
EXPT_R2 =              6600.50 / r2 camera exposure time (seconds)
EXPTIME =              6600.50 / Minimum of exposure times for all cameras
SPCOADD = 'Sat Dec 18 14:39:33 2004' / SPCOADD finished
FLAVOR  = 'science '           / Flavor of this sequence (e.g., dome f
QUALITY = 'excellent'          / night/image quality
RADEG   = 1.61786700000000E+02 / Right Ascension. (degrees)
DECDEG  = 1.38450400000000E+01 / Declination. (degrees)
PLATEID =                 1749 / Plate Id
TILEID  =                 1254 / Tile Id
CARTID  =                    5 /Cartridge used in this plugging
REDDEN  = '0.1169 0.0860 0.0624 0.0473 0.0335' / Median reddening vector for pla
MAPID   =              5333901 / Map Id
NAME    = '1749-53339-01'      / Name of target; PlateId-MJD-Mapper Re
NGUIDE  =              47.0000 / Number of guider frames during exposure
SEEING20=       0.948394004639 / 20% seeing during exposure (arcsec)
SEEING50=        1.04214825896 / 50% seeing during exposure (arcsec)
SEEING80=        1.14693491857 / 80% seeing during exposure (arcsec)
RMSOFF20=      0.0663162113243 / 20% RMS offset of guide fibers (arcsec)
RMSOFF50=       0.124849407819 / 50% RMS offset of guide fibers (arcsec)
RMSOFF80=       0.190828692035 / 80% RMS offset of guide fibers (arcsec)
COLBIN  =                    1 / Binning factor perpendicular to the c
ROWBIN  =                    1 / Binning factor perpendicular to the r
PROGRAM = 'binning 1   1 '     / Identifying name for CCD program
SECFOCUS= -3.0000000000000E+01 / Secondary Mirror Position as reported
GUIDEIMG= '/data/spectro/guider/gimg0358.fits' / Last archived guider image
WTIME   =        1103136150.49 / weatherData(timeStamp)
AIRTEMP =        1.27794174785 / weatherData(airtemp)
DEWPOINT=       -23.0292085672 / weatherData(dewpoint)
DEWDEP  =        24.2689540256 / weatherData(dewpointDep)
DUSTA   =       -9999.00000000 / weatherData(dusta)
DUSTB   =        133.188632408 / weatherData(dustb)
DUSTC   =        5002.58639808 / weatherData(dustc)
DUSTD   =        80.5358784910 / weatherData(dustd)
GUSTD   = 6.13000000000000E+01 / weatherData(gustd)
GUSTS   =        21.3018361107 / weatherData(gusts)
HUMIDITY=        15.4466650273 / weatherData(humidity)
HUMIDOUT=        15.0534390120 / weatherData(humidout)
PRESSURE=        21.5306722734 / weatherData(pressure)
WINDD   =        68.8134715088 / weatherData(windd)
WINDS   =        14.8923253508 / weatherData(winds)
TEMP01  =       -93.7500000000 / CCD 01 Temperature
TEMP02  =       -93.0798738331 / CCD 02 Temperature
TEMP03  =       -92.5273709151 / CCD 03 Temperature
TEMP04  =       -92.8174229214 / CCD 04 Temperature
VERSIDL = '5.4     '           / Version of IDL
VERSUTIL= 'v4_10_1 '           / Version of idlutils
VERSREAD= 'VV4_10_4'           / Version of idlspec2d for pre-processing raw dat
VERS2D  = 'VV4_10_4'           / Version of idlspec2d for 2D reduction
VERSCOMB= 'VV4_10_4'           / Version of idlspec2d for combining multiple spe
VERSLOG = 'Unknown '           / Version of SPECLOG product
VERSFLAT= 'v1_5    '           / Version of SPECFLAT product
OPBC    = 'opBC-51813.par'     /
OPCONFIG= 'opConfig-50000.par' /
OPECALIB= 'opECalib-51577.par' /
XSIGMA  =       0.846015134121 /
XSIGMIN =       0.794703000000 /
XSIGMAX =       0.913462000000 /
WSIGMA  =       0.895203917443 /
WSIGMIN =       0.844423000000 /
WSIGMAX =        1.02305996418 /
PLUGFILE= 'plPlugMapM-1749-53339-01.par' /
LAMPLIST= 'lamphgcdne.dat'     /
SKYLIST = 'skylines.dat'       /
HELIO_RV=       -28.9074336086 / Heliocentric correction (added to velocities)
VACUUM  =                    T / Wavelengths are in vacuum
SFLATTEN=                    T / Superflat has been applied
PSFSKY  =                    3 / Order of PSF skysubtraction
SKYCHI2 =       0.975985550491 / Mean chi^2 of sky-subtraction
SCHI2MIN=       0.861771000000 /
SCHI2MAX=        1.27761995792 /
PREJECT =             0.200000 / Profile area rejection threshold
SPEC1_G =              56.5973 /(S/N)^2 for spec  1 at mag 20.20
SPEC1_R =              66.0616 /(S/N)^2 for spec  1 at mag 20.25
SPEC1_I =              60.8341 /(S/N)^2 for spec  1 at mag 19.90
SPEC2_G =              61.4239 /(S/N)^2 for spec  2 at mag 20.20
SPEC2_R =              68.1814 /(S/N)^2 for spec  2 at mag 20.25
SPEC2_I =              55.1312 /(S/N)^2 for spec  2 at mag 19.90
LOWREJ  =                    5 / Extraction: low rejection
HIGHREJ =                    8 / Extraction: high rejection
SCATPOLY=                    5 / Extraction: Order of scattered light polynomial
PROFTYPE=                    3 / Extraction profile: 1=Gaussian
NFITPOLY=                    1 / Extraction: Number of parameters in each profil
XCHI2   =        1.26520622792 / Extraction: Mean chi^2
XCHI2MIN=              1.11800 /
XCHI2MAX=              1.60609 /
ROFFSET1=           -0.0803245 /Mean r-band mag difference (spectro - photo)
RSIGMA1 =            0.0619670 /Stddev of r-band mag difference (spectro - photo
GROFF1  =          -0.00259215 /Mean (g-r) color difference (spectro - photo)
GRSIGMA1=             0.119939 /Stddev of (g-r) color difference (spectro - phot
ROFFSET2=           -0.0585678 /Mean r-band mag difference (spectro - photo)
RSIGMA2 =            0.0747859 /Stddev of r-band mag difference (spectro - photo
GROFF2  =            0.0178410 /Mean (g-r) color difference (spectro - photo)
GRSIGMA2=            0.0346920 /Stddev of (g-r) color difference (spectro - phot
NWORDER =                    2 / Linear-log10 coefficients
WFITTYPE= 'LOG-LINEAR'         / Linear-log10 dispersion
UNAME   = 'fnpc17.fnal.gov'    /
SMEARUSE=                    F / Smear available?
TSOBJNAM= 'tsObj-1749-53339-01.fit' / Name of tsObj file used
SFD_USED=                    T / SFD dust maps used?
XYGRSIG1=            0.0250000 / Sigma of (g-r) offsets as a fcn of plate x/y
XYGRSIG2=            0.0187645 / Sigma of (g-r) offsets as a fcn of plate x/y
MPGRSIG1=            0.0361182 / Sigma of (g-r)_model - (g-r)_photo Spec 1
MPGRSIG2=            0.0364746 / Sigma of (g-r)_model - (g-r)_photo Spec 2
MPGROFF1=            0.0464152 / Mean of (g-r)_model - (g-r)_photo of Spec 1
MPGROFF2=            0.0371270 / Mean of (g-r)_model - (g-r)_photo of Spec 2
FBADPIX =            0.0377000 / Fraction of bad pixels
FBADPIX1=            0.0420851 / Fraction of bad pixels on spectro-1
FBADPIX2=            0.0333148 / Fraction of bad pixels on spectro-2
WAT0_001= 'system=linear'      /
WAT1_001= 'wtype=linear label=Wavelength units=Angstroms' /
CRPIX1  =                    1 / Starting pixel (1-indexed)
CTYPE1  = 'LINEAR  '           /
DC-FLAG =                    1 / Log-linear flag
PIXMIN  = 0.00000000000000E+00 / Place Holder
PIXMAX  = 2.04700000000000E+03 / Place Holder
ARRAY1  = 'SPECTRUM'           / units of (10^-17 erg/s/cm^2/A
ARRAY2  = 'CONTINUUM-SUBTRACTED SPECTRUM' / units of 10^-17 erg/s/cm^2/A
ARRAY3  = 'ERROR   '           / units of 10^-17 erg/s/cm^2/A
ARRAY4  = 'MASK    '           / mask bit array
BUNIT   = '1.0E-17 erg/cm/s/Ang' / units
SN_G    = 1.41815000000000E+01 / Median S/N ration ig g'
MAG_G   = 1.88474000000000E+01 / Synthetic magnitude in g'
SN_R    = 1.77838000000000E+01 / Median S/N ratio in r'
MAG_R   = 1.89064000000000E+01 / Synthetic magnitude in r'
SN_I    = 1.61819000000000E+01 / Median S/N ratio in i'
MAG_I   = 1.86397000000000E+01 / Synthetic magnitude in i'
SCI_SN  = 0.00000000000000E+00 / Science signal to noise ratio
SMEAR_SN= 0.00000000000000E+00 / Smear signal to noise ratio
SM_LEG_0= 0.00000000000000E+00 / 1st legendre coeff. for smear correct
SM_LEG_1= 0.00000000000000E+00 / 2nd legendre coeff. for smear correct
SM_LEG_2= 0.00000000000000E+00 / 3rd legendre coeff. for smear correct
OBJID   = ' 4344 40 2 158 162' / run rerun camcol field objID
MAG     = ' 19.6932 18.9443 18.9819 18.7106 18.6889' / fiber Mags
OBJTYPE = 'QSO     '           / object Type
RAOBJ   = 1.62787030000000E+02 / RA(deg) of object
DECOBJ  = 1.33244410000000E+01 / DEC(deg) of object
XFOCAL  = 2.12030610000000E+02 / X position in Focal plane
YFOCAL  = -1.1294920000000E+02 / Y position in focal plane
PRIMTARG=                    2 / primary Target Flag
SECTARGE=                    0 / Secondary Target Flag
FIBERID =                   26 / fiber ID
SPECID  =                    1 / spectrograph ID
NGOOD   =                 3820 / Number of Good Pixels
VERS_1D = 'v5_9_4  '           / Version of Spectro1d
BESTTEMP=                   29 / Best cross-correlation template
COEFF0  = 3.58120000000000E+00 / Center wavelength (log10) of first pi
COEFF1  = 1.00000000000000E-04 / Log10 dispersion per pixel
CRVAL1  = 3.58120000000000E+00 / Iraf zero point
CD1_1   = 1.00000000000000E-04 / Iraf dispersion
1D_PDATE= '09/21/05:02:53:07'  / 1D Processing/last Modification date
SPEC_CLN=                    2 / Spectral Classn
VEL_DIS = -9.9990000000000E+03 / Velocity dispersion (km/s)
VEL_DISE= -9.9990000000000E+03 / Error on Velocity Dispersion (km/s)
Z       = 4.54384000000000E-02 / Final redshift
Z_ERR   = 3.29810000000000E-05 / Redshift error
Z_CONF  = 9.93404000000000E-01 / Redshift confidence
Z_STATUS=                    6 / Redshift Status
Z_WARNIN=                    0 / Redshift Warning Flags
ECLASS  = 7.67117000000000E-01 / galaxy classification parameter
ECOEFF1 = 5.60083000000000E-01 / 1st expansion coefficient
ECOEFF2 = -5.3997100000000E-01 / 2nd expansion coefficient
ECOEFF3 = -4.9440800000000E-01 / 3rd expansion coefficient
ECOEFF4 = 3.60693000000000E-01 / 4th expansion coefficient
ECOEFF5 = -1.4212500000000E-01 / 5th expansion coefficient
EXTEND  =                    T / Binary tables follow

In [22]:
PLATE = hdu[0].header['PLATEID']
FIBER = hdu[0].header['FIBERID']
MJD = hdu[0].header['MJD']
print(PLATE,FIBER,MJD)
#IDs = SDSS.query_specobj(plate = int(PLATE), mjd = int(MJD), fiberID = int(FIBER))

1749 26 53357

In [23]:
imgURL = f"http://skyserver.sdss.org/dr16/SkyServerWS/ImgCutout/getjpeg?TaskName=Skyserver.Explore.Image&ra=162.787042&dec=13.324442&scale=0.2&width=200&height=200&opt=G"
imgURL

'http://skyserver.sdss.org/dr16/SkyServerWS/ImgCutout/getjpeg?TaskName=Skyserver.Explore.Image&ra=162.787042&dec=13.324442&scale=0.2&width=200&height=200&opt=G'

In [24]:
image_spec = f'https://skyserver.sdss.org/dr16/en/get/SpecById.ashx?id=1969206140214470656'


urllib.request.urlretrieve(image_spec,f"{HIIG_IMG_folder}/specimage_{spec_list[93]}.jpeg")

('/home/holman/Data_storageHII//HIIG_img//specimage_spSpec-53357-1749-026.fit.jpeg',
 <http.client.HTTPMessage at 0x70dd56a16fd0>)

In [ ]:
for e in range(len(download_list)): #len(download_list)
    A = download_list[e][64:-4]
    MJD = A.partition('-')[0]
    PLATE = (A.partition('-')[2]).partition('-')[0]
    FIBER = (A.partition('-')[2]).partition('-')[2]

    IDs = SDSS.query_specobj(plate = int(PLATE), mjd = int(MJD), fiberID = int(FIBER))

    status = str(type(IDs))

    if (status != "<class 'NoneType'>"):
        ra = float(SDSS.query_specobj(plate = int(PLATE), mjd = int(MJD), fiberID = int(FIBER))['ra'])
        dec = float(SDSS.query_specobj(plate = int(PLATE), mjd = int(MJD), fiberID = int(FIBER))['dec'])
    else:
        ra = np.array(reduced_cat[(reduced_cat['PLATEID']==int(PLATE)) & (reduced_cat['FIBERID']==int(FIBER)) & (reduced_cat['MJD']==int(MJD))]['RA'])[0]
        dec = np.array(reduced_cat[(reduced_cat['PLATEID']==int(PLATE)) & (reduced_cat['FIBERID']==int(FIBER)) & (reduced_cat['MJD']==int(MJD))]['DEC'])[0]

    print(ra, dec)


    imgURL = f"http://skyserver.sdss.org/dr16/SkyServerWS/ImgCutout/getjpeg?TaskName=Skyserver.Explore.Image&ra={ra}&dec={dec}&scale=0.2&width=200&height=200&opt=G"

    #urllib.request.urlretrieve(imgURL,HOME +  '/HIIGs/SDSS_Imaging/' + f'imObj-{A}.jpeg')

    #print(imgURL)

    
    #print(ra)

In [3]:
tex_folder = '/HIIGs/Tex_spectra/'
plots_folder =  '/HIIGs/Spectra_plots/'

if (os.path.exists(HOME + tex_folder) == True and os.path.exists(HOME + plots_folder) == True):
    print('Folder for TEX set saving already created \n')
    print('Folder for PLOTS set saving already created \n')
else:
    if (os.path.exists(HOME + plots_folder) == False):
        print(f'Folder for PLOTS set saving created ({HOME+plots_folder}) \n')
        os.mkdir(HOME+plots_folder)
    if (os.path.exists(HOME + tex_folder) == False):
        print(f'Folder for TEX set saving created ({HOME+tex_folder}) \n')
        os.mkdir(HOME+plots_folder)
    else:
        print(f'Folder for TEX set saving created ({HOME+tex_folder}) \n')
        print(f'Folder for PLOTS set saving created ({HOME+plots_folder}) \n')
        os.mkdir(HOME+tex_folder)
        os.mkdir(HOME+plots_folder)

Folder for TEX set saving already created

Folder for PLOTS set saving already created

In [4]:
fits_folder = HOME + '/HIIGs/FITS_download/'
spec_list = os.listdir(fits_folder)
spec_list = sorted(spec_list)

In [5]:
def sdss_dust_correction(NAME,counter):
    counter = int(counter)
    hdu = fits.open(fits_folder+NAME)
    data = hdu[0].data
    ##############################################################
    #Read the header
    
    zz = hdu[0].header['Z']
    RA = hdu[0].header['RA']
    DEC = hdu[0].header['DEC']
    
    c = SkyCoord(ra=RA*u.degree, dec=DEC*u.degree, frame='icrs')
    c.galactic
    
    sfd = SFDQuery()
    ebv01 = sfd(c.galactic)
    
    ##############################################################
    #Read the spectra, flux and wavelength
    
    flux = data[0]
    wav00 = hdu[0].header['COEFF0']
    wavdiff = hdu[0].header['COEFF1']

    hdu.close()
    
    waveair = 10**(wav00 + wavdiff*np.arange(len(flux)))
    
    waveobs = waveair/(1.0+2.735182E-4+131.4182/(waveair)**2 +2.76249E8/(waveair)**4)
    
    ##############################################################
    #redshift correction
    
    wave = waveobs/(1.0+zz)
    
    ##############################################################
    #Unredding the spectra
    
    fluxUnred = pyasl.unred(wave, flux, ebv=ebv01, R_V=3.1)
    
    ##############################################################
    #cosmoiogical flux corrextion
    
    flux_final = fluxUnred*(1.0+zz)**3
    
    ##############################################################
    #Change the wavelength to starlight input
    
    wave_in = int(wave[2])             #initial wavelength
    wave_fin = int(wave[len(wave)-2])  #final wavelength
    
    wave_new = np.arange(wave_in, wave_fin, 1)
    
    flux_interpolate = interp1d(wave, flux_final, kind='quadratic')
    flux_starlight = flux_interpolate(wave_new)
    
    ##############################################################
    #Crate an output array
    
    table = list(zip(wave_new, flux_starlight))
    
    # Save the file

    C = str(counter)

    if len(C) < 3:
        if len(C) == 2:
            C = '0' + C
        if len(C) == 1:
            C = '00' + C

    new_name  = HOME + tex_folder   + '[' + C + ']' + (NAME.replace('.fit',"")) 
    savetxt(new_name + '.tex', table, fmt='%8.4f', delimiter='    ')
    print(NAME+ ' spectra saved in '+new_name + '.tex')

In [6]:
for i in range(len(spec_list)):
    sdss_dust_correction(sorted(spec_list)[i],i+1)

spSpec-51608-0267-421.fit spectra saved in /home/hollman/gdrive/DataHII//HIIGs/Tex_spectra/[001]spSpec-51608-0267-421.tex
spSpec-51690-0341-606.fit spectra saved in /home/hollman/gdrive/DataHII//HIIGs/Tex_spectra/[002]spSpec-51690-0341-606.tex
spSpec-51793-0388-457.fit spectra saved in /home/hollman/gdrive/DataHII//HIIGs/Tex_spectra/[003]spSpec-51793-0388-457.tex
spSpec-51810-0415-141.fit spectra saved in /home/hollman/gdrive/DataHII//HIIGs/Tex_spectra/[004]spSpec-51810-0415-141.tex
spSpec-51811-0381-370.fit spectra saved in /home/hollman/gdrive/DataHII//HIIGs/Tex_spectra/[005]spSpec-51811-0381-370.tex
spSpec-51816-0382-328.fit spectra saved in /home/hollman/gdrive/DataHII//HIIGs/Tex_spectra/[006]spSpec-51816-0382-328.tex
spSpec-51816-0410-220.fit spectra saved in /home/hollman/gdrive/DataHII//HIIGs/Tex_spectra/[007]spSpec-51816-0410-220.tex
spSpec-51817-0418-302.fit spectra saved in /home/hollman/gdrive/DataHII//HIIGs/Tex_spectra/[008]spSpec-51817-0418-302.tex
spSpec-51820-0400-441.fit spectra saved in /home/hollman/gdrive/DataHII//HIIGs/Tex_spectra/[009]spSpec-51820-0400-441.tex
spSpec-51820-0429-495.fit spectra saved in /home/hollman/gdrive/DataHII//HIIGs/Tex_spectra/[010]spSpec-51820-0429-495.tex
spSpec-51821-0384-281.fit spectra saved in /home/hollman/gdrive/DataHII//HIIGs/Tex_spectra/[011]spSpec-51821-0384-281.tex
spSpec-51877-0447-361.fit spectra saved in /home/hollman/gdrive/DataHII//HIIGs/Tex_spectra/[012]spSpec-51877-0447-361.tex
spSpec-51882-0442-156.fit spectra saved in /home/hollman/gdrive/DataHII//HIIGs/Tex_spectra/[013]spSpec-51882-0442-156.tex
spSpec-51908-0481-483.fit spectra saved in /home/hollman/gdrive/DataHII//HIIGs/Tex_spectra/[014]spSpec-51908-0481-483.tex
spSpec-51909-0270-617.fit spectra saved in /home/hollman/gdrive/DataHII//HIIGs/Tex_spectra/[015]spSpec-51909-0270-617.tex
spSpec-51909-0485-550.fit spectra saved in /home/hollman/gdrive/DataHII//HIIGs/Tex_spectra/[016]spSpec-51909-0485-550.tex
spSpec-51910-0275-445.fit spectra saved in /home/hollman/gdrive/DataHII//HIIGs/Tex_spectra/[017]spSpec-51910-0275-445.tex
spSpec-51910-0456-195.fit spectra saved in /home/hollman/gdrive/DataHII//HIIGs/Tex_spectra/[018]spSpec-51910-0456-195.tex
spSpec-51910-0456-306.fit spectra saved in /home/hollman/gdrive/DataHII//HIIGs/Tex_spectra/[019]spSpec-51910-0456-306.tex
spSpec-51910-0465-524.fit spectra saved in /home/hollman/gdrive/DataHII//HIIGs/Tex_spectra/[020]spSpec-51910-0465-524.tex
spSpec-51913-0394-472.fit spectra saved in /home/hollman/gdrive/DataHII//HIIGs/Tex_spectra/[021]spSpec-51913-0394-472.tex
spSpec-51914-0488-439.fit spectra saved in /home/hollman/gdrive/DataHII//HIIGs/Tex_spectra/[022]spSpec-51914-0488-439.tex
spSpec-51924-0459-253.fit spectra saved in /home/hollman/gdrive/DataHII//HIIGs/Tex_spectra/[023]spSpec-51924-0459-253.tex
spSpec-51929-0458-185.fit spectra saved in /home/hollman/gdrive/DataHII//HIIGs/Tex_spectra/[024]spSpec-51929-0458-185.tex
spSpec-51929-0490-128.fit spectra saved in /home/hollman/gdrive/DataHII//HIIGs/Tex_spectra/[025]spSpec-51929-0490-128.tex
spSpec-51955-0472-546.fit spectra saved in /home/hollman/gdrive/DataHII//HIIGs/Tex_spectra/[026]spSpec-51955-0472-546.tex
spSpec-51959-0283-389.fit spectra saved in /home/hollman/gdrive/DataHII//HIIGs/Tex_spectra/[027]spSpec-51959-0283-389.tex
spSpec-51981-0549-621.fit spectra saved in /home/hollman/gdrive/DataHII//HIIGs/Tex_spectra/[028]spSpec-51981-0549-621.tex
spSpec-51991-0556-224.fit spectra saved in /home/hollman/gdrive/DataHII//HIIGs/Tex_spectra/[029]spSpec-51991-0556-224.tex
spSpec-51997-0337-097.fit spectra saved in /home/hollman/gdrive/DataHII//HIIGs/Tex_spectra/[030]spSpec-51997-0337-097.tex
spSpec-52000-0474-610.fit spectra saved in /home/hollman/gdrive/DataHII//HIIGs/Tex_spectra/[031]spSpec-52000-0474-610.tex
spSpec-52138-0652-090.fit spectra saved in /home/hollman/gdrive/DataHII//HIIGs/Tex_spectra/[032]spSpec-52138-0652-090.tex
spSpec-52140-0375-118.fit spectra saved in /home/hollman/gdrive/DataHII//HIIGs/Tex_spectra/[033]spSpec-52140-0375-118.tex
spSpec-52140-0375-348.fit spectra saved in /home/hollman/gdrive/DataHII//HIIGs/Tex_spectra/[034]spSpec-52140-0375-348.tex
spSpec-52145-0653-462.fit spectra saved in /home/hollman/gdrive/DataHII//HIIGs/Tex_spectra/[035]spSpec-52145-0653-462.tex
spSpec-52146-0639-143.fit spectra saved in /home/hollman/gdrive/DataHII//HIIGs/Tex_spectra/[036]spSpec-52146-0639-143.tex
spSpec-52146-0639-242.fit spectra saved in /home/hollman/gdrive/DataHII//HIIGs/Tex_spectra/[037]spSpec-52146-0639-242.tex
spSpec-52146-0658-312.fit spectra saved in /home/hollman/gdrive/DataHII//HIIGs/Tex_spectra/[038]spSpec-52146-0658-312.tex
spSpec-52147-0662-466.fit spectra saved in /home/hollman/gdrive/DataHII//HIIGs/Tex_spectra/[039]spSpec-52147-0662-466.tex
spSpec-52162-0668-089.fit spectra saved in /home/hollman/gdrive/DataHII//HIIGs/Tex_spectra/[040]spSpec-52162-0668-089.tex
spSpec-52162-0668-152.fit spectra saved in /home/hollman/gdrive/DataHII//HIIGs/Tex_spectra/[041]spSpec-52162-0668-152.tex
spSpec-52174-0637-399.fit spectra saved in /home/hollman/gdrive/DataHII//HIIGs/Tex_spectra/[042]spSpec-52174-0637-399.tex
spSpec-52174-0637-523.fit spectra saved in /home/hollman/gdrive/DataHII//HIIGs/Tex_spectra/[043]spSpec-52174-0637-523.tex
spSpec-52174-0664-355.fit spectra saved in /home/hollman/gdrive/DataHII//HIIGs/Tex_spectra/[044]spSpec-52174-0664-355.tex
spSpec-52178-0640-267.fit spectra saved in /home/hollman/gdrive/DataHII//HIIGs/Tex_spectra/[045]spSpec-52178-0640-267.tex
spSpec-52224-0564-216.fit spectra saved in /home/hollman/gdrive/DataHII//HIIGs/Tex_spectra/[046]spSpec-52224-0564-216.tex
spSpec-52224-0564-283.fit spectra saved in /home/hollman/gdrive/DataHII//HIIGs/Tex_spectra/[047]spSpec-52224-0564-283.tex
spSpec-52233-0753-094.fit spectra saved in /home/hollman/gdrive/DataHII//HIIGs/Tex_spectra/[048]spSpec-52233-0753-094.tex
spSpec-52235-0501-602.fit spectra saved in /home/hollman/gdrive/DataHII//HIIGs/Tex_spectra/[049]spSpec-52235-0501-602.tex
spSpec-52238-0566-497.fit spectra saved in /home/hollman/gdrive/DataHII//HIIGs/Tex_spectra/[050]spSpec-52238-0566-497.tex
spSpec-52261-0741-279.fit spectra saved in /home/hollman/gdrive/DataHII//HIIGs/Tex_spectra/[051]spSpec-52261-0741-279.tex
spSpec-52263-0740-259.fit spectra saved in /home/hollman/gdrive/DataHII//HIIGs/Tex_spectra/[052]spSpec-52263-0740-259.tex
spSpec-52263-0742-161.fit spectra saved in /home/hollman/gdrive/DataHII//HIIGs/Tex_spectra/[053]spSpec-52263-0742-161.tex
spSpec-52263-0742-179.fit spectra saved in /home/hollman/gdrive/DataHII//HIIGs/Tex_spectra/[054]spSpec-52263-0742-179.tex
spSpec-52282-0769-100.fit spectra saved in /home/hollman/gdrive/DataHII//HIIGs/Tex_spectra/[055]spSpec-52282-0769-100.tex
spSpec-52317-0505-228.fit spectra saved in /home/hollman/gdrive/DataHII//HIIGs/Tex_spectra/[056]spSpec-52317-0505-228.tex
spSpec-52317-0859-070.fit spectra saved in /home/hollman/gdrive/DataHII//HIIGs/Tex_spectra/[057]spSpec-52317-0859-070.tex
spSpec-52318-0861-489.fit spectra saved in /home/hollman/gdrive/DataHII//HIIGs/Tex_spectra/[058]spSpec-52318-0861-489.tex
spSpec-52319-0575-521.fit spectra saved in /home/hollman/gdrive/DataHII//HIIGs/Tex_spectra/[059]spSpec-52319-0575-521.tex
spSpec-52339-0578-060.fit spectra saved in /home/hollman/gdrive/DataHII//HIIGs/Tex_spectra/[060]spSpec-52339-0578-060.tex
spSpec-52353-0507-087.fit spectra saved in /home/hollman/gdrive/DataHII//HIIGs/Tex_spectra/[061]spSpec-52353-0507-087.tex
spSpec-52353-0507-521.fit spectra saved in /home/hollman/gdrive/DataHII//HIIGs/Tex_spectra/[062]spSpec-52353-0507-521.tex
spSpec-52368-0580-302.fit spectra saved in /home/hollman/gdrive/DataHII//HIIGs/Tex_spectra/[063]spSpec-52368-0580-302.tex
spSpec-52373-0854-514.fit spectra saved in /home/hollman/gdrive/DataHII//HIIGs/Tex_spectra/[064]spSpec-52373-0854-514.tex
spSpec-52411-0920-575.fit spectra saved in /home/hollman/gdrive/DataHII//HIIGs/Tex_spectra/[065]spSpec-52411-0920-575.tex
spSpec-52413-0976-600.fit spectra saved in /home/hollman/gdrive/DataHII//HIIGs/Tex_spectra/[066]spSpec-52413-0976-600.tex
spSpec-52519-0735-461.fit spectra saved in /home/hollman/gdrive/DataHII//HIIGs/Tex_spectra/[067]spSpec-52519-0735-461.tex
spSpec-52523-0987-440.fit spectra saved in /home/hollman/gdrive/DataHII//HIIGs/Tex_spectra/[068]spSpec-52523-0987-440.tex
spSpec-52620-0899-594.fit spectra saved in /home/hollman/gdrive/DataHII//HIIGs/Tex_spectra/[069]spSpec-52620-0899-594.tex
spSpec-52636-0999-517.fit spectra saved in /home/hollman/gdrive/DataHII//HIIGs/Tex_spectra/[070]spSpec-52636-0999-517.tex
spSpec-52641-1003-327.fit spectra saved in /home/hollman/gdrive/DataHII//HIIGs/Tex_spectra/[071]spSpec-52641-1003-327.tex
spSpec-52670-1001-363.fit spectra saved in /home/hollman/gdrive/DataHII//HIIGs/Tex_spectra/[072]spSpec-52670-1001-363.tex
spSpec-52672-0934-369.fit spectra saved in /home/hollman/gdrive/DataHII//HIIGs/Tex_spectra/[073]spSpec-52672-0934-369.tex
spSpec-52709-0941-109.fit spectra saved in /home/hollman/gdrive/DataHII//HIIGs/Tex_spectra/[074]spSpec-52709-0941-109.tex
spSpec-52709-1216-619.fit spectra saved in /home/hollman/gdrive/DataHII//HIIGs/Tex_spectra/[075]spSpec-52709-1216-619.tex
spSpec-52724-1195-060.fit spectra saved in /home/hollman/gdrive/DataHII//HIIGs/Tex_spectra/[076]spSpec-52724-1195-060.tex
spSpec-52734-1240-340.fit spectra saved in /home/hollman/gdrive/DataHII//HIIGs/Tex_spectra/[077]spSpec-52734-1240-340.tex
spSpec-52763-1302-639.fit spectra saved in /home/hollman/gdrive/DataHII//HIIGs/Tex_spectra/[078]spSpec-52763-1302-639.tex
spSpec-52824-1177-556.fit spectra saved in /home/hollman/gdrive/DataHII//HIIGs/Tex_spectra/[079]spSpec-52824-1177-556.tex
spSpec-52937-1269-177.fit spectra saved in /home/hollman/gdrive/DataHII//HIIGs/Tex_spectra/[080]spSpec-52937-1269-177.tex
spSpec-52939-1582-335.fit spectra saved in /home/hollman/gdrive/DataHII//HIIGs/Tex_spectra/[081]spSpec-52939-1582-335.tex
spSpec-52962-1585-261.fit spectra saved in /home/hollman/gdrive/DataHII//HIIGs/Tex_spectra/[082]spSpec-52962-1585-261.tex
spSpec-52992-1594-563.fit spectra saved in /home/hollman/gdrive/DataHII//HIIGs/Tex_spectra/[083]spSpec-52992-1594-563.tex
spSpec-53061-1745-463.fit spectra saved in /home/hollman/gdrive/DataHII//HIIGs/Tex_spectra/[084]spSpec-53061-1745-463.tex
spSpec-53061-1745-475.fit spectra saved in /home/hollman/gdrive/DataHII//HIIGs/Tex_spectra/[085]spSpec-53061-1745-475.tex
spSpec-53084-1758-338.fit spectra saved in /home/hollman/gdrive/DataHII//HIIGs/Tex_spectra/[086]spSpec-53084-1758-338.tex
spSpec-53115-1601-168.fit spectra saved in /home/hollman/gdrive/DataHII//HIIGs/Tex_spectra/[087]spSpec-53115-1601-168.tex
spSpec-53142-1697-415.fit spectra saved in /home/hollman/gdrive/DataHII//HIIGs/Tex_spectra/[088]spSpec-53142-1697-415.tex
spSpec-53149-1612-073.fit spectra saved in /home/hollman/gdrive/DataHII//HIIGs/Tex_spectra/[089]spSpec-53149-1612-073.tex
spSpec-53297-1781-055.fit spectra saved in /home/hollman/gdrive/DataHII//HIIGs/Tex_spectra/[090]spSpec-53297-1781-055.tex
spSpec-53315-1922-588.fit spectra saved in /home/hollman/gdrive/DataHII//HIIGs/Tex_spectra/[091]spSpec-53315-1922-588.tex
spSpec-53317-1921-281.fit spectra saved in /home/hollman/gdrive/DataHII//HIIGs/Tex_spectra/[092]spSpec-53317-1921-281.tex
spSpec-53321-1927-006.fit spectra saved in /home/hollman/gdrive/DataHII//HIIGs/Tex_spectra/[093]spSpec-53321-1927-006.tex
spSpec-53357-1749-026.fit spectra saved in /home/hollman/gdrive/DataHII//HIIGs/Tex_spectra/[094]spSpec-53357-1749-026.tex
spSpec-53357-1749-499.fit spectra saved in /home/hollman/gdrive/DataHII//HIIGs/Tex_spectra/[095]spSpec-53357-1749-499.tex
spSpec-53386-1872-526.fit spectra saved in /home/hollman/gdrive/DataHII//HIIGs/Tex_spectra/[096]spSpec-53386-1872-526.tex
spSpec-53387-1935-204.fit spectra saved in /home/hollman/gdrive/DataHII//HIIGs/Tex_spectra/[097]spSpec-53387-1935-204.tex
spSpec-53387-1945-346.fit spectra saved in /home/hollman/gdrive/DataHII//HIIGs/Tex_spectra/[098]spSpec-53387-1945-346.tex
spSpec-53431-1947-448.fit spectra saved in /home/hollman/gdrive/DataHII//HIIGs/Tex_spectra/[099]spSpec-53431-1947-448.tex
spSpec-53432-1946-609.fit spectra saved in /home/hollman/gdrive/DataHII//HIIGs/Tex_spectra/[100]spSpec-53432-1946-609.tex
spSpec-53442-1983-308.fit spectra saved in /home/hollman/gdrive/DataHII//HIIGs/Tex_spectra/[101]spSpec-53442-1983-308.tex
spSpec-53463-1981-438.fit spectra saved in /home/hollman/gdrive/DataHII//HIIGs/Tex_spectra/[102]spSpec-53463-1981-438.tex
spSpec-53473-1695-627.fit spectra saved in /home/hollman/gdrive/DataHII//HIIGs/Tex_spectra/[103]spSpec-53473-1695-627.tex
spSpec-53493-2132-241.fit spectra saved in /home/hollman/gdrive/DataHII//HIIGs/Tex_spectra/[104]spSpec-53493-2132-241.tex
spSpec-53534-2112-557.fit spectra saved in /home/hollman/gdrive/DataHII//HIIGs/Tex_spectra/[105]spSpec-53534-2112-557.tex
spSpec-53708-2284-545.fit spectra saved in /home/hollman/gdrive/DataHII//HIIGs/Tex_spectra/[106]spSpec-53708-2284-545.tex
spSpec-53711-2278-411.fit spectra saved in /home/hollman/gdrive/DataHII//HIIGs/Tex_spectra/[107]spSpec-53711-2278-411.tex
spSpec-53730-2293-005.fit spectra saved in /home/hollman/gdrive/DataHII//HIIGs/Tex_spectra/[108]spSpec-53730-2293-005.tex
spSpec-53757-2347-501.fit spectra saved in /home/hollman/gdrive/DataHII//HIIGs/Tex_spectra/[109]spSpec-53757-2347-501.tex
spSpec-53762-2361-523.fit spectra saved in /home/hollman/gdrive/DataHII//HIIGs/Tex_spectra/[110]spSpec-53762-2361-523.tex
spSpec-53768-2372-508.fit spectra saved in /home/hollman/gdrive/DataHII//HIIGs/Tex_spectra/[111]spSpec-53768-2372-508.tex
spSpec-53768-2373-560.fit spectra saved in /home/hollman/gdrive/DataHII//HIIGs/Tex_spectra/[112]spSpec-53768-2373-560.tex
spSpec-53786-2356-172.fit spectra saved in /home/hollman/gdrive/DataHII//HIIGs/Tex_spectra/[113]spSpec-53786-2356-172.tex
spSpec-53794-2353-585.fit spectra saved in /home/hollman/gdrive/DataHII//HIIGs/Tex_spectra/[114]spSpec-53794-2353-585.tex
spSpec-53795-2426-015.fit spectra saved in /home/hollman/gdrive/DataHII//HIIGs/Tex_spectra/[115]spSpec-53795-2426-015.tex
spSpec-53795-2439-372.fit spectra saved in /home/hollman/gdrive/DataHII//HIIGs/Tex_spectra/[116]spSpec-53795-2439-372.tex
spSpec-53815-2427-117.fit spectra saved in /home/hollman/gdrive/DataHII//HIIGs/Tex_spectra/[117]spSpec-53815-2427-117.tex
spSpec-53815-2430-117.fit spectra saved in /home/hollman/gdrive/DataHII//HIIGs/Tex_spectra/[118]spSpec-53815-2430-117.tex
spSpec-53852-2483-254.fit spectra saved in /home/hollman/gdrive/DataHII//HIIGs/Tex_spectra/[119]spSpec-53852-2483-254.tex
spSpec-53857-2489-123.fit spectra saved in /home/hollman/gdrive/DataHII//HIIGs/Tex_spectra/[120]spSpec-53857-2489-123.tex
spSpec-53880-2208-306.fit spectra saved in /home/hollman/gdrive/DataHII//HIIGs/Tex_spectra/[121]spSpec-53880-2208-306.tex

In [ ]:
# Opcional: evita trazados gigantes en Agg con paths muy largos
plt.rcParams['agg.path.chunksize'] = 10000

DATA_URL = "http://das.sdss.org/spectro/ss_tar_26/"
catalog_name = "gal_info_dr7_v5_2.fit.gz"
local_dir = HOME

# Lee el catálogo una sola vez, con mapeo de memoria
#with fits.open(os.path.join(local_dir, catalog_name), memmap=True) as hdul:
    #catalog = Table(hdul[1].data)

In [43]:
plt.rcParams['agg.path.chunksize'] = 10000

ll = ['HB','O[III]a','O[III]b','Ha']
lines = {
  "HB": [4862.721, r'H-$\beta$', 4862.0000],
  "O[III]a": [4960.295, r'O[III]$\lambda$4959', 4960.0000],
  "O[III]b": [5008.239, r'O[III]$\lambda$5007', 5007.0000],
  "Ha": [6562.801, r'H-$\alpha$', 6562.0000]
}


TEX_folder = HOME + '/HIIGs/Tex_spectra/'
tex_list = os.listdir(TEX_folder)
tex_list = sorted(tex_list)

IMG_folder = HOME + '/HIIGs/SDSS_Imaging/'
img_list = os.listdir(IMG_folder)
img_list = sorted(img_list)

Final_list = pd.read_csv(HOME + '/SPS/Final_speclist.csv', sep=",", header=0)



for u in range(1): #len(tex_list)

    u = 83

    spc = os.path.join(TEX_folder, tex_list[u])

    A = tex_list[u][12:-4]
    MJD = int(A.partition('-')[0])
    PLATE = int((A.partition('-')[2]).partition('-')[0])
    FIBER = int((A.partition('-')[2]).partition('-')[2])


    partial_list = Final_list[(Final_list['MJD'] == MJD) & (Final_list['PLATE'] == PLATE) & (Final_list['FIBERID'] == FIBER)]


    data = Table.read(spc, format='ascii', fast_reader=True)
    lam = np.asarray(data['col1'], dtype=float)
    flux = np.asarray(data['col2'], dtype=float)
    
    fig, ax = plt.subplots(figsize=(37, 12.57), dpi=50)
    ax.spines.right.set_visible(False)
    ax.spines.top.set_visible(False)
    ax.plot(lam, flux, label='HIIG Flux', lw=2.0, color = 'green')

    ax.set_ylabel(r"$F_{\lambda}\ \left[10^{-17}\ {\rm erg\ s}^{-1}\ {\rm cm}^{-2}\ \AA^{-1}\right]$",
                    style='oblique', family='serif', size = 35)
    ax.set_xlabel(r'Rest Wavelength [$\AA$]',
                    style='oblique', family='serif', size = 35)


    for key in ll:
        rest = lines[key][2]
        idx = np.where(np.abs(lam - rest) <= 3)[0]
        if idx.size:
            i0 = idx[len(idx)//2]
            i1, i2 = max(i0 - 10, 0), min(i0 + 10, flux.size)
            selec_flux_max = float(flux[i1:i2].max()) + 0.05 * (flux.max() - flux.min())
            x = rest - (100 if key in ('O[III]a', 'O[III]b') else 30)
            ax.text(x, selec_flux_max, f"{lines[key][1]}",
                    fontsize=30,
                    bbox={'facecolor': '#F4F1BB', 'alpha': 0.5, 'boxstyle': "round,pad=0.2", 'ec': 'none'})

    ax.tick_params(axis='x', labelsize=20)
    ax.tick_params(axis='y', labelsize=20)

    ax.tick_params(axis='x', labelrotation=90)
    ax.set_xlim(3500, 7000)
    ax.set_ylim(0, max(float(flux.max()), 1.0) * 1.2)
    ax.grid(True, which="both", ls=":", linewidth=0.9)


    image_path = plt.imread(get_sample_data(IMG_folder + img_list[u]))


    inset_ax = inset_axes(ax, width="60%", height="60%", loc='upper right')
    inset_ax.imshow(image_path)
    inset_ax.axis('off')

    sym = [r"$\alpha$",r"$\delta$",r"$z$",r"$\mathcal{PLATE}$",r"$\mathcal{MJD}$",r"$\mathcal{FIBERID}$",r"$\mathbf{NAME}$"]

    leg_title = f'{sym[6]}: {partial_list["Name"].iloc[0]}\n {sym[0]}: {partial_list["RA"].iloc[0]}°\n {sym[1]}: {partial_list["DEC"].iloc[0]}°\n {sym[2]}: {partial_list["Z"].iloc[0]}\n {sym[3]}: {partial_list["PLATE"].iloc[0]}\n {sym[4]}: {partial_list["MJD"].iloc[0]}\n {sym[5]}: {partial_list["FIBERID"].iloc[0]}\n'

    C = str(u+1)

    if len(C) < 3:
        if len(C) == 2:
            C = '0' + C
        if len(C) == 1:
            C = '00' + C


    new_name = '[' + f'{C}' +']' + 'SpecObj-' + A + ".png"
    ax.legend(title=leg_title, loc='upper left', prop={'size': 25}, title_fontsize=35)
    #outdir = HOME + plots_folder
    outdir = '/home/hollman/'
    os.makedirs(outdir, exist_ok=True)
    outfile = os.path.join(outdir, new_name)

    fig.savefig(outfile, dpi=50, bbox_inches='tight', transparent=False)

In [56]:
Final_list = pd.read_csv(HOME + '/SPS/Final_speclist.csv', sep=",", header=0)
Final_list

,N,Name,RA,DEC,Z,PLATE,MJD,FIBERID
0,0,UM 199,1.737614,0.857181,0.073682,388,51793,457
1,1,UM 282,12.947112,0.161124,0.037556,394,51913,472
2,2,UM 336,23.436174,0.953078,0.019236,400,51820,441
3,3,MRK 0627,131.643397,36.438978,0.010634,934,52672,369
4,4,SBS 0934+546,144.556301,54.473618,0.102102,556,51991,224
...,...,...,...,...,...,...,...,...
116,116,WISEA J103226.97+271755.3,158.112320,27.298679,0.192490,2353,53794,585
117,117,WISEA J101136.07+263027.5,152.900317,26.507660,0.054666,2347,53757,501
118,118,WISEA J162152.58+151855.9,245.469098,15.315537,0.034341,2208,53880,306
119,119,WISEA J090506.84+223834.7,136.278600,22.642759,0.125548,2284,53708,545
120,120,WISEA J094000.50+203122.7,145.002109,20.522973,0.044799,2361,53762,523

In [31]:
def spec_plotter(name,
                 figsize=(48, 18),        # << mucho más pequeño
                 render_dpi=100,          # DPI de canvas
                 save_dpi=100,            # DPI del archivo final
                 tol=1.0,counter=0):                # tolerancia en Å para localizar líneas

    # Construye paths/nombres como en tu versión
    base = (name.replace('.fit', '')) + ".tex"
    base = base.replace(".tex", f"._{str(counter)}_.tex")
    local_dirspc = HOME + tex_folder
    spc = os.path.join(local_dirspc, base)

    # Extrae IDs desde el nombre, como en tu código
    plateid, mjd, fiberid = [int(base[13:17]), int(base[7:12]), int(base[18:21])]

    # Selección de fila en el catálogo
    z_finder = (catalog['PLATEID'] == plateid) & (catalog['MJD'] == mjd) & (catalog['FIBERID'] == fiberid)
    reduced_cat = catalog[z_finder]
    Z = float(reduced_cat['Z'][0])

    # Lee espectro (rápido y sobrio en memoria)
    data = Table.read(spc, format='ascii', fast_reader=True)
    lam = np.asarray(data['col1'], dtype=float)
    flux = np.asarray(data['col2'], dtype=float)

    # Prepara figura/axes (OO) y estilos básicos
    fig, ax = plt.subplots(figsize=figsize, dpi=render_dpi)
    ax.spines.right.set_visible(False)
    ax.spines.top.set_visible(False)

    # Trazado principal
    ax.plot(lam, flux, label='Flux', lw=1.2)

    ax.set_ylabel(r"$F_{\lambda}\ \left[10^{-17}\ {\rm erg\ s}^{-1}\ {\rm cm}^{-2}\ \AA^{-1}\right]$",
                  style='oblique', family='serif')
    ax.set_xlabel(r'Wavelength at rest $\lambda$ [$\AA$]',
                  style='oblique', family='serif')

    # Anotación de líneas (con tolerancia en lugar de igualdad exacta)
    for key in ll:
        rest = lines[key][2]
        idx = np.where(np.abs(lam - rest) <= tol)[0]
        if idx.size:
            i0 = idx[len(idx)//2]
            i1, i2 = max(i0 - 10, 0), min(i0 + 10, flux.size)
            selec_flux_max = float(flux[i1:i2].max()) + 0.05 * (flux.max() - flux.min())
            x = rest - (100 if key in ('O[III]a', 'O[III]b') else 30)
            ax.text(x, selec_flux_max, f"{lines[key][1]}",
                    fontsize=11,
                    bbox={'facecolor': '#F4F1BB', 'alpha': 0.5, 'boxstyle': "round,pad=0.2", 'ec': 'none'})

    ax.tick_params(axis='x', labelrotation=90)
    ax.set_xlim(3500, 7500)
    ax.set_ylim(0, max(float(flux.max()), 1.0) * 1.05)
    ax.grid(True, which="both", ls=":", linewidth=0.8)

    leg_title = f"{base[:-4]}\nZ = {Z}\nPLATEID = {plateid}\nMJD = {mjd}\nFIBERID = {fiberid}"
    ax.legend(title=leg_title, loc='upper right', prop={'size': 10}, title_fontsize=11)

    outdir = HOME + plots_folder
    os.makedirs(outdir, exist_ok=True)
    outfile = os.path.join(outdir, base.replace('.tex', '') + ".png")

    # Guarda (si "tight" no es imprescindible, quítalo para ahorrar un poco más)
    fig.savefig(outfile, dpi=save_dpi, bbox_inches='tight', transparent=False)

    # Cierra y limpia SOLO esta figura
    plt.close(fig)
    del fig, ax, data, lam, flux, reduced_cat
    gc.collect()
    print('Done for ' + base.replace('.tex', ''))

In [ ]:

Final_list

   N    Name        RA       DEC         Z  PLATE    MJD  FIBERID
0  0  UM 199  1.737614  0.857181  0.073682    388  51793      457

In [ ]:
TEX_folder = HOME + '/HIIGs/Tex_spectra/'
tex_list = os.listdir(TEX_folder)
tex_list = sorted(tex_list)



# Bucle principal (usa directamente la lista)
for h in range(2): #len(spec_list)
    try:
        spec_plotter(name = sorted(tex_list)[h],counter = h+1)
    except Exception as e:
        print(f"[WARN] Falló {name}: {e}")

# Version vieja no optimizada

In [6]:
DATA_URL="http://das.sdss.org/spectro/ss_tar_26/"
catalog_name="gal_info_dr7_v5_2.fit.gz"
local_dir="/home/hollman/DataHII/"
local_file = fits.open(os.path.join(local_dir,catalog_name))
catalog=Table.read(local_file[1])
local_file.close()

ll = ['HB','O[III]a','O[III]b','Ha']
# Lines dictionary
lines = {
  "HB": [4862.721,r'H-$\beta$',4862.0000], #4862
  "O[III]a": [4960.295,r'O[III]$\lambda$4959',4960.0000],#4960
  "O[III]b": [5008.239,r'O[III]$\lambda$5007',5007.0000],#5007
  "Ha": [6562.801,r'H-$\alpha$',6562.0000] ##6550
}

In [8]:
def spec_plotter(name):
    name = (name.replace('.fit',"")) + ".tex"
    local_dirspc="/home/hollman/DataHII/HIIGalaxy_Spectra(Chavez2012)/Tex_spectra/"
    spc = os.path.join(local_dirspc,name)
    plateid, mjd, fiberid = [int(name[13:17]), int(name[7:12]), int(name[18:21])]
    z_finder = (catalog['PLATEID']==plateid) & (catalog['MJD']==mjd) & (catalog['FIBERID']==fiberid)
    reduced_cat = catalog[z_finder]
    Z = round(float(reduced_cat['Z'][0]),6)
    data = Table.read(spc, format='ascii')
    data.rename_column('col1', r'$\lambda$')
    data.rename_column('col2', 'Flux')
    plt.rcParams['axes.spines.left'] = True
    plt.rcParams['axes.spines.right'] = False
    plt.rcParams['axes.spines.top'] = False
    plt.rcParams['axes.spines.bottom'] = True
    plt.figure(figsize=(40,18),dpi=200)
    plt.plot(data[r'$\lambda$'],data['Flux'],label = 'Flux',lw=1.3, color ='#1C448E')
    plt.ylabel(r"$F_{\lambda}\ \left[ 10^{-17}\ {\rm erg\ s}^{-1}\ {\rm cm}^{-2}\ \AA^{-1} \right]$", style = 'oblique', family = 'serif', size = 25)
    plt.xlabel(r'Wavelength at rest $\lambda$ [$\AA$]', style = 'oblique', family = 'serif', size = 25)
    # Lineas a mostrar
    for a in range(len(ll)):#len(ll)
        v_lambda = lines[ll[a]][2] 
        flux_line = data[(data[r'$\lambda$'])==v_lambda]
        selec_flux_idx = np.where(data[r'$\lambda$'] == v_lambda)
        selec_flux_max = max(data['Flux'][(selec_flux_idx[0][0])-10:(selec_flux_idx[0][0])+10]) + 70
        if (a==1) or (a==2):
            v_lambda = v_lambda- 100
        else:
            v_lambda = v_lambda - 30
        plt.text(v_lambda, selec_flux_max, f'{lines[ll[a]][1]}', 
                fontsize = 25,bbox = {'facecolor': '#F4F1BB', 'alpha': 0.5, 'boxstyle': "round,pad=0.3", 'ec': 'none'}, rotation = 0)
    plt.yticks(fontsize = 20)
    plt.xticks(fontsize = 20,rotation=90)
    plt.ylim(0,max(data['Flux'],)+15)
    plt.xlim(4000,7000)
    plt.grid(True, which="both", ls=":", color = 'gray', linewidth = 0.8)
    txt_prop = {'style' : 'oblique', 'family' : 'serif', 'size' :30}       
    plt.legend(title = f'{name[:-4]} \n Z = {Z} \n PLATEID = {plateid} \n MJD = {mjd} \n FIBERID = {fiberid}', prop = txt_prop, loc= 'upper right', title_fontsize=35)
    plt.savefig("/home/hollman/DataHII/HIIGalaxy_Spectra(Chavez2012)/Spectra_plots/" + (name.replace('.tex',"")) + ".png" ,
                bbox_inches='tight', transparent=False,dpi=150)
    #plt.show()
    plt.close('all')
    print('Done for '+ (name.replace('.tex',"")))
    gc.collect()
    del name, plateid, mjd, fiberid,z_finder,reduced_cat, Z, data
    
#spSpec-52339-0578-060.tex
#spec_plotter(spec_list[0])

In [ ]:
for i in range(len(spec_list)):
    spec_plotter(spec_list[i])

Done for spSpec-52339-0578-060
Done for spSpec-52937-1269-177
Done for spSpec-53297-1781-055
Done for spSpec-52962-1585-261
Done for spSpec-53473-1695-627
Done for spSpec-52353-0507-521
Done for spSpec-53534-2112-557
Done for spSpec-51929-0490-128
Done for spSpec-54561-2708-193
Done for spSpec-51821-0384-281
Done for spSpec-53768-2372-508
Done for spSpec-54628-2318-286
Done for spSpec-51882-0442-156
Done for spSpec-53386-1872-526
Done for spSpec-52174-0637-523
Done for spSpec-52224-0564-216
Done for spSpec-52636-0999-517
Done for spSpec-51957-0502-007
Done for spSpec-53084-1758-338
Done for spSpec-52413-0976-600
Done for spSpec-52178-0640-267
Done for spSpec-53463-1981-438
Done for spSpec-52641-1003-327
Done for spSpec-53768-2373-560
Done for spSpec-52939-1582-335
Done for spSpec-51816-0382-328
Done for spSpec-53317-1921-281
Done for spSpec-53142-1697-415
Done for spSpec-52138-0652-090
Done for spSpec-52238-0566-497
Done for spSpec-53786-2356-172
Done for spSpec-52174-0664-355
Done for spSpec-53852-2483-254
Done for spSpec-54521-2942-246
Done for spSpec-51909-0455-073
Done for spSpec-52992-1594-563
Done for spSpec-51811-0381-370
Done for spSpec-52263-0742-179
Done for spSpec-53387-1935-204
Done for spSpec-51909-0485-550
Done for spSpec-51877-0447-361
Done for spSpec-53815-2430-117
Done for spSpec-51662-0284-277
Done for spSpec-52146-0639-242
Done for spSpec-53061-1745-463
Done for spSpec-51877-0410-217
Done for spSpec-51914-0488-439
Done for spSpec-51929-0458-185
Done for spSpec-52140-0375-118
Done for spSpec-52145-0653-462
Done for spSpec-51924-0459-253
Done for spSpec-53815-2427-117
Done for spSpec-52318-0861-489
Done for spSpec-52263-0740-259
Done for spSpec-54149-2689-190
Done for spSpec-53115-1601-168
Done for spSpec-53880-2208-306
Done for spSpec-53708-2284-545
Done for spSpec-51820-0429-495