In [7]:
import re
import os
import numpy as np
import pandas as pd

In [8]:
tables_dir = os.path.join(os.path.expanduser("~"), 'HIIGalaxies/Distance_moduli/Compilation_tables')

In [9]:
PLRC_tab_list = [f for f in os.listdir(tables_dir) if 'plrc' in f.lower()]
TRGB_tab_list = [f for f in os.listdir(tables_dir) if 'trgb' in f.lower()]
PLRC_tab_list.sort(key=lambda x: (int(x.split('.')[0]), x.split('.')[1]))
TRGB_tab_list.sort(key=lambda x: (int(x.split('.')[0]), x.split('.')[1]))

In [10]:
PLRC_dfs_list = []

for i in range(len(PLRC_tab_list)):
    df = pd.read_csv(os.path.join(tables_dir,PLRC_tab_list[i]))
    df['galaxy'] = (PLRC_tab_list[i].split('.')[1]).replace('_PLRC','')

    columna_left = df.pop('galaxy')
    df.insert(0, 'galaxy', columna_left)

    df.rename(columns={
        'RefCode': 'bibcode',
        'Citation': 'citation',
        'Band': 'band',
        'mu_0': 'modulus',
        'e_R': 'random_error',
        'e_S': 'systematic_error',
        'e_T': 'total_error',
        'Category': 'category_error',
        'Ncef': 'cepheids_number',
        'Zcorr': 'metal_correction',
        'zeroP': 'zero_point',
        'Rank': 'probe_quality',
        'Year': 'publication_year',
        'Date': 'review_year',
        'Comments': 'comments',
        'Author': 'review_author',
        'ADS_date': 'ads_date',
        'JD': 'ads_jd',
    }, inplace=True)

    PLRC_dfs_list.append(df)


PLRC_final_DF = pd.concat(PLRC_dfs_list, ignore_index=True)
PLRC_final_DF.to_csv('PLRC_general_v1.1.csv',index=False)
PLRC_final_DF

,galaxy,bibcode,citation,band,modulus,random_error,systematic_error,total_error,category_error,cepheids_number,metal_correction,zero_point,probe_quality,publication_year,review_year,comments,review_author,ads_date,ads_jd
0,IC0010,2000ApJ...529..745F,Ferrarese et al.2000,W(VI),24.100,0.190,NaN,NaN,1,4,False,LMC,1,2000,2024,There are no specific comments on the publicat...,Valencia et al.2024,2000-02-00,2451575.5
1,M33,2000ApJ...529..745F,Ferrarese et al.2000,VI,24.640,0.090,NaN,NaN,1,10,False,LMC,1,2000,2024,They calculate gamma.,Valencia et al.2024,2000-02-00,2451575.5
2,M33,2001ApJ...548..564W,Willick & Batra 2001,W(VI),24.470,0.130,NaN,NaN,1,12,False,LMC,1,2001,2024,They do not apply correction for metallicity.,Valencia et al.2024,2001-02-00,2451941.5
3,M33,2001ApJ...553...47F,Freedman et al.2001,W(VI),24.560,0.100,NaN,NaN,1,11,False,LMC,1,2001,2024,There are no specific comments on the publicat...,Valencia et al.2024,2001-05-00,2452030.5
4,M33,2001ApJ...553...47F,Freedman et al.2001,W(VI),24.620,0.100,NaN,NaN,1,11,True,LMC,1,2001,2024,Correction for metallicity and same uncertaint...,Valencia et al.2024,2001-05-00,2452030.5
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
357,NGC7331,2003A&A...411..361K,"Kanbur, S. M. et al.2003",W(VI),30.791,0.079,NaN,NaN,1,13,False,LMC,1,2003,2026,Representative LMC mean-light solution. CTE co...,Quintero-Salazar et al.2026,2003-12-00,2452974.5
358,NGC7331,2003A&A...411..361K,"Kanbur, S. M. et al.2003",W(VI),30.818,0.083,NaN,NaN,1,13,True,GC,1,2003,2026,FSG03 Galactic result with a -0.040 mag metall...,Quintero-Salazar et al.2026,2003-12-00,2452974.5
359,NGC7331,2003A&A...411..361K,"Kanbur, S. M. et al.2003",W(VI),30.825,0.079,NaN,NaN,1,13,True,LMC,1,2003,2026,LMC solution with a +0.034 mag metallicity cor...,Quintero-Salazar et al.2026,2003-12-00,2452974.5
360,NGC7331,2003A&A...411..361K,"Kanbur, S. M. et al.2003",W(VI),30.858,0.083,NaN,NaN,1,13,False,GC,1,2003,2026,Representative FSG03 Galactic mean-light solut...,Quintero-Salazar et al.2026,2003-12-00,2452974.5
361,NGC7331,2006ApJS..165..108S,Saha et al.2006,W(VI),30.890,0.100,0.08,0.128062,2,13,True,GC+LMC,1,2006,2026,Final modulus from 13 Cepheids. The uncorrecte...,Quintero-Salazar et al.2026,2006-07-00,2453917.5

In [11]:
TRGB_dfs_list = []

for i in range(len(TRGB_tab_list)):
    df = pd.read_csv(os.path.join(tables_dir,TRGB_tab_list[i]))
    df['galaxy'] = (TRGB_tab_list[i].split('.')[1]).replace('_TRGB','')

    columna_left = df.pop('galaxy')
    df.insert(0, 'galaxy', columna_left)

    df.rename(columns={
        'RefCode': 'bibcode',
        'Citation': 'citation',
        'Band': 'band',
        'mu_0': 'modulus',
        'e_R': 'random_error',
        'Rank': 'probe_quality',
        'Year': 'publication_year',
        'Date': 'review_year',
        'Comments': 'comments',
        'Author': 'review_author',
        'ADS_date': 'ads_date',
        'JD': 'ads_jd',
    }, inplace=True)

    TRGB_dfs_list.append(df)


TRGB_final_DF = pd.concat(TRGB_dfs_list, ignore_index=True)
TRGB_final_DF.to_csv('TRGB_general_v1.1.csv',index=False)
TRGB_final_DF

,galaxy,bibcode,citation,band,modulus,random_error,probe_quality,publication_year,review_year,comments,review_author,ads_date,ads_jd
0,IC0010,2000ApJ...529..745F,Ferrarese et al.2000,I (BVI),24.170,0.390,1,2000,2024,There are no specific comments on the publicat...,Valencia et al.2024,2000-02-00,2451575.5
1,IC0010,2001ApJ...559..225H,Hunter 2001,F814W(F555W F814W),24.950,0.200,1,2001,2026,HST/WFPC2 TRGB measurement adopting E(B-V)=0.7...,Quintero-Salazar et al.2026,2001-09-00,2452153.5
2,IC0010,2007ApJ...662..272V,Vacca et al.2007,F814W(HK),24.480,0.080,2,2007,2024,E(B-V)=0.95+/-0.15.,Valencia et al.2024,2007-06-00,2454252.5
3,IC0010,2008ApJ...688L..69S,Sanna et al.2008,F814W(F555W F606W),24.510,0.800,1,2008,2024,There are no specific comments on the publicat...,Valencia et al.2024,2008-12-00,2454801.5
4,IC0010,2009ApJ...703..816K,Kim et al.2009,J(JHK),24.150,0.060,2,2009,2024,Region 2.,Valencia et al.2024,2009-09-00,2455075.5
...,...,...,...,...,...,...,...,...,...,...,...,...,...
177,NGC5584,2017ApJ...836...74J,Jang & Lee 2017,QT(F555W F814W),31.751,0.049,1,2017,2026,Preferred combined-anchor QT solution from the...,Quintero-Salazar et al.2026,2017-02-00,2457785.5
178,NGC5584,2017ApJ...836...74J,Jang & Lee 2017,F814W(F555W F814W),31.784,0.060,1,2017,2026,Combined-anchor blue-I solution from uniformly...,Quintero-Salazar et al.2026,2017-02-00,2457785.5
179,NGC5584,2024ApJ...966...89A,Anand et al. 2024,F090W(F090W F150W),31.800,0.080,1,2024,2026,Preliminary JWST result using a method-matched...,Quintero-Salazar et al.2026,2024-05-00,2460431.5
180,NGC5584,2024ApJ...976..177L,Li et al. 2024,F090W(F090W F150W),31.800,0.110,1,2024,2026,Baseline s=0.05 mag smoothing selects the brig...,Quintero-Salazar et al.2026,2024-12-00,2460645.5
181,NGC5584,2024ApJ...976..177L,Li et al. 2024,F090W(F090W F150W),31.950,0.080,1,2024,2026,Alternative s=0.10 mag smoothing selects the f...,Quintero-Salazar et al.2026,2024-12-00,2460645.5

In [52]:
galaxy_list = ['IC0010',
                    'IC2574',
                    'M33',
                    'M81',
                    'M101',
                    'MRK116',
                    'NGC0925',
                    'NGC2366',
                    'NGC2403',
                    'NGC2541',
                    'NGC3198',
                    'NGC3319',
                    'NGC4214',
                    'NGC4236',
                    'NGC4258',
                    'NGC4395',
                    'NGC6822',
                    'NGC1073',
                    'NGC2500',
                    'NGC3184',
                    'M96',
                    'NGC3370',
                    'M66',
                    'NGC4414',
                    'NGC4496A',
                    'NGC4535',
                    'NGC4536',
                    'NGC4725',
                    'UGC08091',
                    'NGC5204',
                    'UGC09128',
                    'NGC5584',                                  
                    'NGC7331',]

In [53]:
PLRC_articles_eff = pd.read_csv('PLRC_general_v1.1.csv')

In [54]:
ART_S = np.unique(PLRC_articles_eff['bibcode'])

In [55]:
with open(f"transition_to_excel_PLRC.txt", "w", encoding="ascii") as f:
    pass


for A in range(len(ART_S)):
    print(ART_S[A])
    filter_art = PLRC_articles_eff[PLRC_articles_eff['bibcode'] == ART_S[A]]
    unique_gal_in_art = np.unique(filter_art['galaxy'])
    print(unique_gal_in_art)
    for_excel = [0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0]
    for m in range(len(unique_gal_in_art)):
        for g in range(len(galaxy_list)):
            if galaxy_list[g] == unique_gal_in_art[m]:
                for_excel[g] = 1

    buffer = [0,0,0,0,0]
    print(ART_S[A],*buffer,*for_excel, sep=",")
    print('\n')
    with open("transition_to_excel_PLRC.txt", "a", encoding="ascii") as f:
        print(ART_S[A], *buffer, *for_excel, sep="\t", file=f)

1995AJ....110.1640T
['NGC2366']
1995AJ....110.1640T,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0


1996ApJS..107..693S
['NGC4496A']
1996ApJS..107..693S,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0


2000ApJ...529..723G
['M66' 'M96' 'NGC4414' 'NGC4496A' 'NGC4536']
2000ApJ...529..723G,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,1,1,1,0,1,0,0,0,0,0,0


2000ApJ...529..745F
['IC0010' 'M101' 'M33' 'M66' 'M81' 'M96' 'NGC0925' 'NGC2541' 'NGC3198'
 'NGC3319' 'NGC4414' 'NGC4496A' 'NGC4535' 'NGC4536' 'NGC4725' 'NGC6822'
 'NGC7331']
2000ApJ...529..745F,0,0,0,0,0,1,0,1,1,1,0,1,0,0,1,1,1,0,0,0,0,1,0,0,0,1,0,1,1,1,1,1,1,0,0,0,0,1


2000ApJ...530L...5G
['NGC4496A' 'NGC4536']
2000ApJ...530L...5G,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,1,0,0,0,0,0,0


2001ApJ...547L.103G
['M66' 'M96' 'NGC4414' 'NGC4496A' 'NGC4536']
2001ApJ...547L.103G,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,1,1,1,0,1,0,0,0,0,0,0


2001ApJ...548..564W
['M101' 'M33' 'M66' 'M81' 'M96' 'NGC0925' 'NGC2541' 'NGC3198' 'NGC3319'
 'NGC4258' 'NGC4414' 'NGC4496A' 'NGC4535' 'NGC4536' 'NGC4725' 'NGC6822'
 'NGC7331']
2001ApJ...548..564W,0,0,0,0,0,0,0,1,1,1,0,1,0,0,1,1,1,0,0,1,0,1,0,0,0,1,0,1,1,1,1,1,1,0,0,0,0,1


2001ApJ...549..721M
['M101' 'M81' 'NGC0925' 'NGC3198' 'NGC4496A' 'NGC4536']
2001ApJ...549..721M,0,0,0,0,0,0,0,0,1,1,0,1,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,1,0,0,0,0,0,0


2001ApJ...553...47F
['M101' 'M33' 'M66' 'M81' 'M96' 'NGC0925' 'NGC2403' 'NGC2541' 'NGC3198'
 'NGC3319' 'NGC4258' 'NGC4414' 'NGC4496A' 'NGC4535' 'NGC4536' 'NGC4725'
 'NGC7331']
2001ApJ...553...47F,0,0,0,0,0,0,0,1,1,1,0,1,0,1,1,1,1,0,0,1,0,0,0,0,0,1,0,1,1,1,1,1,1,0,0,0,0,1


2001ApJ...553..562N
['NGC4258']
2001ApJ...553..562N,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0


2002A&A...383..398P
['M101' 'M33' 'M66' 'M81' 'M96' 'NGC0925' 'NGC2541' 'NGC3198' 'NGC3319'
 'NGC4258' 'NGC4414' 'NGC4496A' 'NGC4535' 'NGC4536' 'NGC4725' 'NGC6822'
 'NGC7331']
2002A&A...383..398P,0,0,0,0,0,0,0,1,1,1,0,1,0,0,1,1,1,0,0,1,0,1,0,0,0,1,0,1,1,1,1,1,1,0,0,0,0,1


2002A&A...389...19P
['M101' 'M33' 'M66' 'M81' 'M96' 'NGC0925' 'NGC2541' 'NGC3198' 'NGC3319'
 'NGC4258' 'NGC4414' 'NGC4496A' 'NGC4535' 'NGC4536' 'NGC4725' 'NGC6822'
 'NGC7331']
2002A&A...389...19P,0,0,0,0,0,0,0,1,1,1,0,1,0,0,1,1,1,0,0,1,0,1,0,0,0,1,0,1,1,1,1,1,1,0,0,0,0,1


2002AJ....123..207D
['M66']
2002AJ....123..207D,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0


2002ApJ...565..959L
['M33']
2002ApJ...565..959L,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0


2002ApJ...566..833C
['NGC4258']
2002ApJ...566..833C,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0


2003A&A...411..361K
['M66' 'M81' 'NGC0925' 'NGC2541' 'NGC3198' 'NGC3319' 'NGC4258' 'NGC4414'
 'NGC4496A' 'NGC4535' 'NGC4536' 'NGC4725' 'NGC7331']
2003A&A...411..361K,0,0,0,0,0,0,0,0,1,0,0,1,0,0,1,1,1,0,0,1,0,0,0,0,0,0,0,1,1,1,1,1,1,0,0,0,0,1


2003ApJ...586..959N
['NGC4258']
2003ApJ...586..959N,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0


2004AJ....127.2322T
['NGC4395']
2004AJ....127.2322T,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0


2004AJ....128.2815P
['NGC6822']
2004AJ....128.2815P,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0


2004ApJ...608...42S
['M101' 'M33' 'M81' 'NGC6822']
2004ApJ...608...42S,0,0,0,0,0,0,0,1,1,1,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0


2004MNRAS.349.1130N
['NGC4258']
2004MNRAS.349.1130N,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0


2005ApJ...627..579R
['NGC3370' 'NGC4536']
2005ApJ...627..579R,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,1,0,0,0,0,0,0


2006ApJ...642L..29N
['NGC3370' 'NGC4536']
2006ApJ...642L..29N,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,1,0,0,0,0,0,0


2006ApJ...647.1056G
['NGC6822']
2006ApJ...647.1056G,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0


2006ApJ...652.1133M
['NGC4258']
2006ApJ...652.1133M,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0


2006ApJS..165..108S
['M101' 'M33' 'M66' 'M81' 'M96' 'NGC0925' 'NGC2403' 'NGC2541' 'NGC3198'
 'NGC3319' 'NGC3370' 'NGC4258' 'NGC4414' 'NGC4496A' 'NGC4535' 'NGC4536'
 'NGC4725' 'NGC6822' 'NGC7331']
2006ApJS..165..108S,0,0,0,0,0,0,0,1,1,1,0,1,0,1,1,1,1,0,0,1,0,1,0,0,0,1,1,1,1,1,1,1,1,0,0,0,0,1


2007AJ....133.1810B
['NGC4258']
2007AJ....133.1810B,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0


2007ApJ...667L.151A
['MRK116']
2007ApJ...667L.151A,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0


2007ApJ...671.1640A
['NGC4258']
2007ApJ...671.1640A,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0


2007MNRAS.379..723V
['NGC4258']
2007MNRAS.379..723V,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0


2008ApJ...684..102B
['NGC4258']
2008ApJ...684..102B,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0


2008MNRAS.390.1762D
['NGC4258']
2008MNRAS.390.1762D,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0


2009AJ....137.4707M
['M81']
2009AJ....137.4707M,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0


2009ApJ...693..936M
['NGC6822']
2009ApJ...693..936M,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0


2009ApJ...699..539R
['NGC3370' 'NGC4536']
2009ApJ...699..539R,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,1,0,0,0,0,0,0


2009MNRAS.396.1287S
['M33']
2009MNRAS.396.1287S,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0


2010ApJ...711..808F
['MRK116']
2010ApJ...711..808F,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0


2010ApJ...713..615M
['MRK116']
2010ApJ...713..615M,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0


2010ApJ...715..277B
['M33' 'NGC4258' 'NGC6822']
2010ApJ...715..277B,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,1,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0


2011ApJ...730..119R
['NGC3370' 'NGC4536' 'NGC5584']
2011ApJ...730..119R,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,1,0,0,0,0,1,0


2011ApJ...733..124S
['M101']
2011ApJ...733..124S,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0


2011ApJ...743..176G
['M81']
2011ApJ...743..176G,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0


2011ApJS..193...26P
['M33']
2011ApJS..193...26P,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0


2012MNRAS.421.2998F
['NGC6822']
2012MNRAS.421.2998F,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0


2013ApJ...773...69G
['M33']
2013ApJ...773...69G,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0


2013ApJ...777...79M
['M101']
2013ApJ...777...79M,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0


2013MNRAS.430..546D
['NGC4258']
2013MNRAS.430..546D,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0


2013MNRAS.434.2866F
['NGC3370' 'NGC4258' 'NGC4536' 'NGC5584']
2013MNRAS.434.2866F,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,1,0,0,0,0,1,0,0,0,0,1,0


2014A&A...572A..64M
['NGC6822']
2014A&A...572A..64M,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0


2014ApJ...794..107R
['NGC6822']
2014ApJ...794..107R,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0


2014MNRAS.440.1138E
['NGC4258']
2014MNRAS.440.1138E,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0


2015AJ....149..183H
['NGC4258']
2015AJ....149..183H,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0


2015MNRAS.449.1171N
['M101']
2015MNRAS.449.1171N,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0


2015MNRAS.450.3597F
['NGC4258']
2015MNRAS.450.3597F,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0


2016AJ....151...88B
['NGC6822']
2016AJ....151...88B,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0


2016ApJ...826...56R
['M101' 'NGC3370' 'NGC4536' 'NGC5584']
2016ApJ...826...56R,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,1,0,0,0,0,1,0


2021ApJ...911...12J
['NGC5584']
2021ApJ...911...12J,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0


2022ApJ...934L...7R
['M101' 'NGC3370' 'NGC4536' 'NGC5584']
2022ApJ...934L...7R,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,1,0,0,0,0,1,0


2023ApJ...951..118B
['M33']
2023ApJ...951..118B,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0

In [56]:
TRGB_articles_eff = pd.read_csv('TRGB_general_v1.1.csv')

In [57]:
ART_S = np.unique(TRGB_articles_eff['bibcode'])

In [59]:
with open(f"transition_to_excel_TRGB.txt", "w", encoding="ascii") as f:
    pass


for A in range(len(ART_S)):
    print(ART_S[A])
    filter_art = TRGB_articles_eff[TRGB_articles_eff['bibcode'] == ART_S[A]]
    unique_gal_in_art = np.unique(filter_art['galaxy'])
    print(unique_gal_in_art)
    for_excel = [0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0]
    for m in range(len(unique_gal_in_art)):
        for g in range(len(galaxy_list)):
            if galaxy_list[g] == unique_gal_in_art[m]:
                for_excel[g] = 1

    buffer = [0,0,0,0,1]
    print(ART_S[A],*buffer,*for_excel, sep=",")
    print('\n')
    with open("transition_to_excel_TRGB.txt", "a", encoding="ascii") as f:
        print(ART_S[A], *buffer, *for_excel, sep="\t", file=f)

2000AJ....119..177A
['UGC09128']
2000AJ....119..177A,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0


2000ApJ...529..745F
['IC0010' 'M33' 'NGC6822']
2000ApJ...529..745F,0,0,0,0,1,1,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0


2001ApJ...559..225H
['IC0010']
2001ApJ...559..225H,0,0,0,0,1,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0


2002A&A...383..125K
['NGC2366' 'NGC4236']
2002A&A...383..125K,0,0,0,0,1,0,0,0,0,0,0,0,1,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0


2002AJ....123..244K
['M33']
2002AJ....123..244K,0,0,0,0,1,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0


2002AJ....123.1307M
['NGC4214']
2002AJ....123.1307M,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0


2002AJ....124..811D
['NGC4214']
2002AJ....124..811D,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0


2003A&A...398..467K
['NGC4395' 'NGC5204']
2003A&A...398..467K,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0


2003A&A...398..479K
['IC2574']
2003A&A...398..479K,0,0,0,0,1,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0


2003AJ....125.3046D
['NGC2403']
2003AJ....125.3046D,0,0,0,0,1,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0


2003AJ....125.3097W
['NGC6822']
2003AJ....125.3097W,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0


2004A&A...423..925G
['M33']
2004A&A...423..925G,0,0,0,0,1,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0


2004AJ....128..224T
['M33']
2004AJ....128..224T,0,0,0,0,1,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0


2004AJ....128..237B
['M33']
2004AJ....128..237B,0,0,0,0,1,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0


2004ApJ...608...42S
['M101' 'M33' 'M81']
2004ApJ...608...42S,0,0,0,0,1,0,0,1,1,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0


2004MNRAS.350..243M
['M33']
2004MNRAS.350..243M,0,0,0,0,1,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0


2005A&A...429..837C
['NGC6822']
2005A&A...429..837C,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0


2005A&A...431..127T
['M81']
2005A&A...431..127T,0,0,0,0,1,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0


2005ApJ...627..739T
['NGC2366']
2005ApJ...627..739T,0,0,0,0,1,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0


2005ApJ...633..810M
['NGC4258']
2005ApJ...633..810M,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0


2005MNRAS.356..979M
['M33']
2005MNRAS.356..979M,0,0,0,0,1,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0


2006AJ....132..729T
['NGC4214' 'UGC08091' 'UGC09128']
2006AJ....132..729T,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,1,0,0


2007ApJ...661..815R
['M101' 'M33' 'M81' 'NGC4258']
2007ApJ...661..815R,0,0,0,0,1,0,0,1,1,1,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0


2007ApJ...662..272V
['IC0010']
2007ApJ...662..272V,0,0,0,0,1,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0


2007ApJ...667L.151A
['MRK116']
2007ApJ...667L.151A,0,0,0,0,1,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0


2007AstL...33..137T
['MRK116']
2007AstL...33..137T,0,0,0,0,1,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0


2008AJ....135.1482S
['M33']
2008AJ....135.1482S,0,0,0,0,1,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0


2008ARep...52...19T
['NGC2366']
2008ARep...52...19T,0,0,0,0,1,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0


2008ApJ...688L..69S
['IC0010']
2008ApJ...688L..69S,0,0,0,0,1,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0


2008ApJ...689..721M
['NGC4258']
2008ApJ...689..721M,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0


2009AJ....138..332J
['IC2574' 'M33' 'M81' 'NGC2366' 'NGC2403' 'NGC4214' 'NGC4236' 'NGC4395'
 'UGC08091' 'UGC09128']
2009AJ....138..332J,0,0,0,0,1,0,1,1,1,0,0,0,1,1,0,0,0,1,1,0,1,0,0,0,0,0,0,0,0,0,0,0,0,1,0,1,0,0


2009ApJ...690..389M
['NGC4258']
2009ApJ...690..389M,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0


2009ApJ...694.1331M
['M96']
2009ApJ...694.1331M,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0


2009ApJ...697..996M
['M66']
2009ApJ...697..996M,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0


2009ApJ...703..816K
['IC0010']
2009ApJ...703..816K,0,0,0,0,1,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0


2009ApJ...704.1120U
['M33']
2009ApJ...704.1120U,0,0,0,0,1,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0


2009ApJS..183...67D
['IC2574' 'M81' 'NGC2366' 'NGC2403' 'NGC4214' 'UGC08091' 'UGC09128']
2009ApJS..183...67D,0,0,0,0,1,0,1,0,1,0,0,0,1,1,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,1,0,0


2009AstL...35..748T
['IC0010']
2009AstL...35..748T,0,0,0,0,1,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0


2010ApJ...718.1118D
['M81']
2010ApJ...718.1118D,0,0,0,0,1,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0


2010ApJ...724..799Y
['M33']
2010ApJ...724..799Y,0,0,0,0,1,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0


2011A&A...533A..91G
['M33']
2011A&A...533A..91G,0,0,0,0,1,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0


2011AJ....141..194G
['NGC6822']
2011AJ....141..194G,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0


2011ApJ...733..124S
['M101']
2011ApJ...733..124S,0,0,0,0,1,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0


2011ApJS..195...18R
['NGC2403']
2011ApJS..195...18R,0,0,0,0,1,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0


2012A&A...540A..49M
['NGC4214' 'NGC6822' 'UGC08091' 'UGC09128']
2012A&A...540A..49M,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,1,0,1,0,0


2012A&A...548A.129F
['NGC6822']
2012A&A...548A.129F,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0


2012ApJ...751L..19J
['M81']
2012ApJ...751L..19J,0,0,0,0,1,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0


2012ApJ...758...11C
['M33']
2012ApJ...758...11C,0,0,0,0,1,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0


2012ApJ...760L..14L
['M101']
2012ApJ...760L..14L,0,0,0,0,1,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0


2013AJ....146...86T
['IC2574' 'NGC4214' 'NGC4236' 'NGC4395' 'UGC09128']
2013AJ....146...86T,0,0,0,0,1,0,1,0,0,0,0,0,0,0,0,0,0,1,1,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0


2013ApJ...773...13L
['M66' 'M96']
2013ApJ...773...13L,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,1,0,0,0,0,0,0,0,0,0,0


2013AstBu..68..125M
['NGC4214' 'NGC5204' 'UGC09128']
2013AstBu..68..125M,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,1,0,0


2014AJ....148....7W
['NGC4214']
2014AJ....148....7W,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0


2015ApJ...807..133J
['NGC5584']
2015ApJ...807..133J,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0


2015AstL...41..239T
['M101']
2015AstL...41..239T,0,0,0,0,1,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0


2015MNRAS.450.3886M
['NGC5204']
2015MNRAS.450.3886M,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0


2016ApJ...828L...5C
['NGC2403']
2016ApJ...828L...5C,0,0,0,0,1,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0


2017ApJ...834...78M
['IC0010']
2017ApJ...834...78M,0,0,0,0,1,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0


2017ApJ...835...28J
['NGC4258']
2017ApJ...835...28J,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0


2017ApJ...836...74J
['M101' 'M66' 'M96' 'NGC3370' 'NGC5584']
2017ApJ...836...74J,0,0,0,0,1,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,1,1,0,0,0,0,0,0,0,0,1,0


2018ApJS..235...23S
['M101' 'M66' 'M96' 'NGC2500' 'NGC4258' 'NGC4395']
2018ApJS..235...23S,0,0,0,0,1,0,0,0,0,1,0,0,0,0,0,0,0,0,0,1,1,0,0,1,0,1,0,1,0,0,0,0,0,0,0,0,0,0


2018AstBu..73...22T
['NGC2366' 'NGC4395' 'UGC08091' 'UGC09128']
2018AstBu..73...22T,0,0,0,0,1,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,1,0,1,0,0


2021AstBu..76..255T
['NGC1073']
2021AstBu..76..255T,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0


2024ApJ...966...89A
['NGC4258' 'NGC5584']
2024ApJ...966...89A,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0


2024ApJ...966..175N
['M81' 'NGC2403' 'UGC09128']
2024ApJ...966..175N,0,0,0,0,1,0,0,0,1,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0


2024ApJ...976..177L
['NGC3370' 'NGC5584']
2024ApJ...976..177L,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,1,0


2025A&A...697L...6V
['M33']
2025A&A...697L...6V,0,0,0,0,1,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0

In [61]:
ART_S_PLRC = np.unique(PLRC_articles_eff['bibcode'])
ART_S_TRGB = np.unique(TRGB_articles_eff['bibcode'])
print(len(ART_S_PLRC),len(ART_S_TRGB))

59 67

In [62]:
np.intersect1d(ART_S_PLRC,ART_S_TRGB)

array(['2000ApJ...529..745F', '2004ApJ...608...42S',
       '2007ApJ...667L.151A', '2011ApJ...733..124S'], dtype=object)

In [70]:
sec_col_PLRC = PLRC_articles_eff[['galaxy', 'bibcode','citation']]
sec_col_TRGB = TRGB_articles_eff[['galaxy', 'bibcode','citation']]
general_concat = pd.concat([sec_col_PLRC,sec_col_TRGB], ignore_index=True)
general_concat

      galaxy              bibcode              citation
0     IC0010  2000ApJ...529..745F  Ferrarese et al.2000
1        M33  2000ApJ...529..745F  Ferrarese et al.2000
2        M33  2001ApJ...548..564W  Willick & Batra 2001
3        M33  2001ApJ...553...47F   Freedman et al.2001
4        M33  2001ApJ...553...47F   Freedman et al.2001
..       ...                  ...                   ...
539  NGC5584  2017ApJ...836...74J       Jang & Lee 2017
540  NGC5584  2017ApJ...836...74J       Jang & Lee 2017
541  NGC5584  2024ApJ...966...89A     Anand et al. 2024
542  NGC5584  2024ApJ...976..177L        Li et al. 2024
543  NGC5584  2024ApJ...976..177L        Li et al. 2024

[544 rows x 3 columns]

In [75]:
ART_S = np.unique(general_concat['bibcode'])
with open(f"transition_to_excel_general.txt", "w", encoding="ascii") as f:
    pass
for A in range(len(ART_S)):
    print(ART_S[A])
    filter_art = general_concat[general_concat['bibcode'] == ART_S[A]]
    unique_gal_in_art = np.unique(filter_art['galaxy'])
    print(unique_gal_in_art)
    for_excel = [0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0]
    for m in range(len(unique_gal_in_art)):
        for g in range(len(galaxy_list)):
            if galaxy_list[g] == unique_gal_in_art[m]:
                for_excel[g] = 1

    buffer = [filter_art['citation'].iloc[0],0,0,0,0,0]
    print(ART_S[A],*buffer,*for_excel, sep=",")
    print('\n')
    with open("transition_to_excel_general.txt", "a", encoding="ascii") as f:
        print(ART_S[A], *buffer, *for_excel, sep="\t", file=f)

1995AJ....110.1640T
['NGC2366']
1995AJ....110.1640T,Tolstoy et al.1995,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0


1996ApJS..107..693S
['NGC4496A']
1996ApJS..107..693S,Saha et al. 1996,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0


2000AJ....119..177A
['UGC09128']
2000AJ....119..177A,Aparicio et al. 2000,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0


2000ApJ...529..723G
['M66' 'M96' 'NGC4414' 'NGC4496A' 'NGC4536']
2000ApJ...529..723G,Gibson et al. 2000,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,1,1,1,0,1,0,0,0,0,0,0


2000ApJ...529..745F
['IC0010' 'M101' 'M33' 'M66' 'M81' 'M96' 'NGC0925' 'NGC2541' 'NGC3198'
 'NGC3319' 'NGC4414' 'NGC4496A' 'NGC4535' 'NGC4536' 'NGC4725' 'NGC6822'
 'NGC7331']
2000ApJ...529..745F,Ferrarese et al.2000,0,0,0,0,0,1,0,1,1,1,0,1,0,0,1,1,1,0,0,0,0,1,0,0,0,1,0,1,1,1,1,1,1,0,0,0,0,1


2000ApJ...530L...5G
['NGC4496A' 'NGC4536']
2000ApJ...530L...5G,Gibson et al. 2000,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,1,0,0,0,0,0,0


2001ApJ...547L.103G
['M66' 'M96' 'NGC4414' 'NGC4496A' 'NGC4536']
2001ApJ...547L.103G,Gibson & Stetson 2001,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,1,1,1,0,1,0,0,0,0,0,0


2001ApJ...548..564W
['M101' 'M33' 'M66' 'M81' 'M96' 'NGC0925' 'NGC2541' 'NGC3198' 'NGC3319'
 'NGC4258' 'NGC4414' 'NGC4496A' 'NGC4535' 'NGC4536' 'NGC4725' 'NGC6822'
 'NGC7331']
2001ApJ...548..564W,Willick & Batra 2001,0,0,0,0,0,0,0,1,1,1,0,1,0,0,1,1,1,0,0,1,0,1,0,0,0,1,0,1,1,1,1,1,1,0,0,0,0,1


2001ApJ...549..721M
['M101' 'M81' 'NGC0925' 'NGC3198' 'NGC4496A' 'NGC4536']
2001ApJ...549..721M,Macri et al.2001,0,0,0,0,0,0,0,0,1,1,0,1,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,1,0,0,0,0,0,0


2001ApJ...553...47F
['M101' 'M33' 'M66' 'M81' 'M96' 'NGC0925' 'NGC2403' 'NGC2541' 'NGC3198'
 'NGC3319' 'NGC4258' 'NGC4414' 'NGC4496A' 'NGC4535' 'NGC4536' 'NGC4725'
 'NGC7331']
2001ApJ...553...47F,Freedman et al.2001,0,0,0,0,0,0,0,1,1,1,0,1,0,1,1,1,1,0,0,1,0,0,0,0,0,1,0,1,1,1,1,1,1,0,0,0,0,1


2001ApJ...553..562N
['NGC4258']
2001ApJ...553..562N,Newman et al.2001,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0


2001ApJ...559..225H
['IC0010']
2001ApJ...559..225H,Hunter 2001,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0


2002A&A...383..125K
['NGC2366' 'NGC4236']
2002A&A...383..125K,Karachentsev, I. D. et al.2002,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0


2002A&A...383..398P
['M101' 'M33' 'M66' 'M81' 'M96' 'NGC0925' 'NGC2541' 'NGC3198' 'NGC3319'
 'NGC4258' 'NGC4414' 'NGC4496A' 'NGC4535' 'NGC4536' 'NGC4725' 'NGC6822'
 'NGC7331']
2002A&A...383..398P,Paturel et al. 2002,0,0,0,0,0,0,0,1,1,1,0,1,0,0,1,1,1,0,0,1,0,1,0,0,0,1,0,1,1,1,1,1,1,0,0,0,0,1


2002A&A...389...19P
['M101' 'M33' 'M66' 'M81' 'M96' 'NGC0925' 'NGC2541' 'NGC3198' 'NGC3319'
 'NGC4258' 'NGC4414' 'NGC4496A' 'NGC4535' 'NGC4536' 'NGC4725' 'NGC6822'
 'NGC7331']
2002A&A...389...19P,Paturel, G. et al.2002,0,0,0,0,0,0,0,1,1,1,0,1,0,0,1,1,1,0,0,1,0,1,0,0,0,1,0,1,1,1,1,1,1,0,0,0,0,1


2002AJ....123..207D
['M66']
2002AJ....123..207D,Dolphin & Kennicutt 2002,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0


2002AJ....123..244K
['M33']
2002AJ....123..244K,Kim et al.2002,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0


2002AJ....123.1307M
['NGC4214']
2002AJ....123.1307M,Maiz-Apellaniz et al.2002,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0


2002AJ....124..811D
['NGC4214']
2002AJ....124..811D,Drozdovsky et al.2002,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0


2002ApJ...565..959L
['M33']
2002ApJ...565..959L,Lee et al.2002,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0


2002ApJ...566..833C
['NGC4258']
2002ApJ...566..833C,Caputo et al. 2002,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0


2003A&A...398..467K
['NGC4395' 'NGC5204']
2003A&A...398..467K,Karachentsev et al. 2003,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0


2003A&A...398..479K
['IC2574']
2003A&A...398..479K,Karachentsev et al. 2003,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0


2003A&A...411..361K
['M66' 'M81' 'NGC0925' 'NGC2541' 'NGC3198' 'NGC3319' 'NGC4258' 'NGC4414'
 'NGC4496A' 'NGC4535' 'NGC4536' 'NGC4725' 'NGC7331']
2003A&A...411..361K,Kanbur, S. M. et al.2003,0,0,0,0,0,0,0,0,1,0,0,1,0,0,1,1,1,0,0,1,0,0,0,0,0,0,0,1,1,1,1,1,1,0,0,0,0,1


2003AJ....125.3046D
['NGC2403']
2003AJ....125.3046D,Davidge 2003,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0


2003AJ....125.3097W
['NGC6822']
2003AJ....125.3097W,Wyder 2003,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0


2003ApJ...586..959N
['NGC4258']
2003ApJ...586..959N,Ngeow et al. 2003,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0


2004A&A...423..925G
['M33']
2004A&A...423..925G,Galleti, S. et al.2004,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0


2004AJ....127.2322T
['NGC4395']
2004AJ....127.2322T,Tammann et al.2004,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0


2004AJ....128..224T
['M33']
2004AJ....128..224T,Tiede et al.2004,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0


2004AJ....128..237B
['M33']
2004AJ....128..237B,Brooks et al.2004,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0


2004AJ....128.2815P
['NGC6822']
2004AJ....128.2815P,Pietrzynski et al.2004,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0


2004ApJ...608...42S
['M101' 'M33' 'M81' 'NGC6822']
2004ApJ...608...42S,Sakai et al.2004,0,0,0,0,0,0,0,1,1,1,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0


2004MNRAS.349.1130N
['NGC4258']
2004MNRAS.349.1130N,Ngow & Kanbur 2004,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0


2004MNRAS.350..243M
['M33']
2004MNRAS.350..243M,McConnachie et al.2004,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0


2005A&A...429..837C
['NGC6822']
2005A&A...429..837C,Cioni, M.-R. & Habing, H. J. 2005,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0


2005A&A...431..127T
['M81']
2005A&A...431..127T,Tikhonov, N. A. et al.2005,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0


2005ApJ...627..579R
['NGC3370' 'NGC4536']
2005ApJ...627..579R,Riess et al. 2005,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,1,0,0,0,0,0,0


2005ApJ...627..739T
['NGC2366']
2005ApJ...627..739T,Thuan & Izotov 2005,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0


2005ApJ...633..810M
['NGC4258']
2005ApJ...633..810M,Mouhcine et al.2005,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0


2005MNRAS.356..979M
['M33']
2005MNRAS.356..979M,Rizzi et al.2005,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0


2006AJ....132..729T
['NGC4214' 'UGC08091' 'UGC09128']
2006AJ....132..729T,Tully et al.2006,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,1,0,0


2006ApJ...642L..29N
['NGC3370' 'NGC4536']
2006ApJ...642L..29N,Ngeow & Kanbur 2006,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,1,0,0,0,0,0,0


2006ApJ...647.1056G
['NGC6822']
2006ApJ...647.1056G,Gieren et al.2006,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0


2006ApJ...652.1133M
['NGC4258']
2006ApJ...652.1133M,Macri et al.2006,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0


2006ApJS..165..108S
['M101' 'M33' 'M66' 'M81' 'M96' 'NGC0925' 'NGC2403' 'NGC2541' 'NGC3198'
 'NGC3319' 'NGC3370' 'NGC4258' 'NGC4414' 'NGC4496A' 'NGC4535' 'NGC4536'
 'NGC4725' 'NGC6822' 'NGC7331']
2006ApJS..165..108S,Saha et al.2006,0,0,0,0,0,0,0,1,1,1,0,1,0,1,1,1,1,0,0,1,0,1,0,0,0,1,1,1,1,1,1,1,1,0,0,0,0,1


2007AJ....133.1810B
['NGC4258']
2007AJ....133.1810B,Benedict et al.2007,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0


2007ApJ...661..815R
['M101' 'M33' 'M81' 'NGC4258']
2007ApJ...661..815R,Rizzi et al.2007,0,0,0,0,0,0,0,1,1,1,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0


2007ApJ...662..272V
['IC0010']
2007ApJ...662..272V,Vacca et al.2007,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0


2007ApJ...667L.151A
['MRK116']
2007ApJ...667L.151A,Aloisi et al.2007,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0


2007ApJ...671.1640A
['NGC4258']
2007ApJ...671.1640A,Aloisi et al.2007,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0


2007AstL...33..137T
['MRK116']
2007AstL...33..137T,Tikhonov 2007,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0


2007MNRAS.379..723V
['NGC4258']
2007MNRAS.379..723V,van Leeuwen et al.2007,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0


2008AJ....135.1482S
['M33']
2008AJ....135.1482S,Stonkute et al.2008,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0


2008ARep...52...19T
['NGC2366']
2008ARep...52...19T,Tikhonov & Galazutdinova 2008,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0


2008ApJ...684..102B
['NGC4258']
2008ApJ...684..102B,Bono et al.2008,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0


2008ApJ...688L..69S
['IC0010']
2008ApJ...688L..69S,Sanna et al.2008,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0


2008ApJ...689..721M
['NGC4258']
2008ApJ...689..721M,Mager et al.2008,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0


2008MNRAS.390.1762D
['NGC4258']
2008MNRAS.390.1762D,Di Benedetto 2008,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0


2009AJ....137.4707M
['M81']
2009AJ....137.4707M,McCommas et al.2009,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0


2009AJ....138..332J
['IC2574' 'M33' 'M81' 'NGC2366' 'NGC2403' 'NGC4214' 'NGC4236' 'NGC4395'
 'UGC08091' 'UGC09128']
2009AJ....138..332J,Jacobs et al.2009,0,0,0,0,0,0,1,1,1,0,0,0,1,1,0,0,0,1,1,0,1,0,0,0,0,0,0,0,0,0,0,0,0,1,0,1,0,0


2009ApJ...690..389M
['NGC4258']
2009ApJ...690..389M,Madore et al.2009a,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0


2009ApJ...693..936M
['NGC6822']
2009ApJ...693..936M,Madore et al.2009b,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0


2009ApJ...694.1331M
['M96']
2009ApJ...694.1331M,Mould & Sakai 2009,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0


2009ApJ...697..996M
['M66']
2009ApJ...697..996M,Mould & Sakai 2009,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0


2009ApJ...699..539R
['NGC3370' 'NGC4536']
2009ApJ...699..539R,Riess et al. 2009,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,1,0,0,0,0,0,0


2009ApJ...703..816K
['IC0010']
2009ApJ...703..816K,Kim et al.2009,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0


2009ApJ...704.1120U
['M33']
2009ApJ...704.1120U,U et al. 2009,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0


2009ApJS..183...67D
['IC2574' 'M81' 'NGC2366' 'NGC2403' 'NGC4214' 'UGC08091' 'UGC09128']
2009ApJS..183...67D,Dalcanton et al.2009,0,0,0,0,0,0,1,0,1,0,0,0,1,1,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,1,0,0


2009AstL...35..748T
['IC0010']
2009AstL...35..748T,Tikhonov & Galazutdinova 2009,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0


2009MNRAS.396.1287S
['M33']
2009MNRAS.396.1287S,Sowcroft et al.2009,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0


2010ApJ...711..808F
['MRK116']
2010ApJ...711..808F,Fiorentino et al. 2010,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0


2010ApJ...713..615M
['MRK116']
2010ApJ...713..615M,Marconi et al. 2010,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0


2010ApJ...715..277B
['M33' 'NGC4258' 'NGC6822']
2010ApJ...715..277B,Bono et al. 2010,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,1,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0


2010ApJ...718.1118D
['M81']
2010ApJ...718.1118D,Dalcanton et al.2010,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0


2010ApJ...724..799Y
['M33']
2010ApJ...724..799Y,Yang et al.2010,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0


2011A&A...533A..91G
['M33']
2011A&A...533A..91G,Grossi, M. et al.2011,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0


2011AJ....141..194G
['NGC6822']
2011AJ....141..194G,Gorski et al.2011,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0


2011ApJ...730..119R
['NGC3370' 'NGC4536' 'NGC5584']
2011ApJ...730..119R,Riess et al. 2011,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,1,0,0,0,0,1,0


2011ApJ...733..124S
['M101']
2011ApJ...733..124S,Shappee & Stanek 2011,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0


2011ApJ...743..176G
['M81']
2011ApJ...743..176G,Gerke et al.2011,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0


2011ApJS..193...26P
['M33']
2011ApJS..193...26P,Pellerin & Macri 2011,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0


2011ApJS..195...18R
['NGC2403']
2011ApJS..195...18R,Radburn-Smith et al.2011,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0


2012A&A...540A..49M
['NGC4214' 'NGC6822' 'UGC08091' 'UGC09128']
2012A&A...540A..49M,McCall, M. L. et al.2012,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,1,0,1,0,0


2012A&A...548A.129F
['NGC6822']
2012A&A...548A.129F,Fusco et al. 2012,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0


2012ApJ...751L..19J
['M81']
2012ApJ...751L..19J,Jang et al. 2012,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0


2012ApJ...758...11C
['M33']
2012ApJ...758...11C,Conn et al.2012,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0


2012ApJ...760L..14L
['M101']
2012ApJ...760L..14L,Lee & Jang 2012,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0


2012MNRAS.421.2998F
['NGC6822']
2012MNRAS.421.2998F,Feast et al.2012,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0


2013AJ....146...86T
['IC2574' 'NGC4214' 'NGC4236' 'NGC4395' 'UGC09128']
2013AJ....146...86T,Tully et al.2013,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,1,1,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0


2013ApJ...773...13L
['M66' 'M96']
2013ApJ...773...13L,Lee & Jang 2013,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,1,0,0,0,0,0,0,0,0,0,0


2013ApJ...773...69G
['M33']
2013ApJ...773...69G,Gieren et al.2013,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0


2013ApJ...777...79M
['M101']
2013ApJ...777...79M,Mager et al.2013,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0


2013AstBu..68..125M
['NGC4214' 'NGC5204' 'UGC09128']
2013AstBu..68..125M,Makarov et al. 2013,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,1,0,0


2013MNRAS.430..546D
['NGC4258']
2013MNRAS.430..546D,Di Benedetto 2013,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0


2013MNRAS.434.2866F
['NGC3370' 'NGC4258' 'NGC4536' 'NGC5584']
2013MNRAS.434.2866F,Fiorentino et al.2013,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,1,0,0,0,0,1,0,0,0,0,1,0


2014A&A...572A..64M
['NGC6822']
2014A&A...572A..64M,Majewski et al.2014,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0


2014AJ....148....7W
['NGC4214']
2014AJ....148....7W,Wu et al. 2014,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0


2014ApJ...794..107R
['NGC6822']
2014ApJ...794..107R,Rich et al.2014,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0


2014MNRAS.440.1138E
['NGC4258']
2014MNRAS.440.1138E,Efstathiou 2014,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0


2015AJ....149..183H
['NGC4258']
2015AJ....149..183H,Hatt et al.2015,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0


2015ApJ...807..133J
['NGC5584']
2015ApJ...807..133J,Jang & Lee 2015,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0


2015AstL...41..239T
['M101']
2015AstL...41..239T,Tikhonov et al.2015,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0


2015MNRAS.449.1171N
['M101']
2015MNRAS.449.1171N,Nataf et al. 2015,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0


2015MNRAS.450.3597F
['NGC4258']
2015MNRAS.450.3597F,Fausnaugh et al.2015,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0


2015MNRAS.450.3886M
['NGC5204']
2015MNRAS.450.3886M,McQuinn et al. 2015,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0


2016AJ....151...88B
['NGC6822']
2016AJ....151...88B,Bhardwaj et al.2016,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0


2016ApJ...826...56R
['M101' 'NGC3370' 'NGC4536' 'NGC5584']
2016ApJ...826...56R,Riess et al.2016,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,1,0,0,0,0,1,0


2016ApJ...828L...5C
['NGC2403']
2016ApJ...828L...5C,Carlin et al.2016,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0


2017ApJ...834...78M
['IC0010']
2017ApJ...834...78M,McQuinn et al.2017,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0


2017ApJ...835...28J
['NGC4258']
2017ApJ...835...28J,Jang & Lee 2017,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0


2017ApJ...836...74J
['M101' 'M66' 'M96' 'NGC3370' 'NGC5584']
2017ApJ...836...74J,Jang & Lee 2017,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,1,1,0,0,0,0,0,0,0,0,1,0


2018ApJS..235...23S
['M101' 'M66' 'M96' 'NGC2500' 'NGC4258' 'NGC4395']
2018ApJS..235...23S,Sabbi et al.2018,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,1,1,0,0,1,0,1,0,1,0,0,0,0,0,0,0,0,0,0


2018AstBu..73...22T
['NGC2366' 'NGC4395' 'UGC08091' 'UGC09128']
2018AstBu..73...22T,Tikhonov 2018,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,1,0,1,0,0


2021ApJ...911...12J
['NGC5584']
2021ApJ...911...12J,Javanmardi et al. 2021,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0


2021AstBu..76..255T
['NGC1073']
2021AstBu..76..255T,Tikhonov & Galazutdinova 2021,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0


2022ApJ...934L...7R
['M101' 'NGC3370' 'NGC4536' 'NGC5584']
2022ApJ...934L...7R,Riess et al. 2022,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,1,0,0,0,0,1,0


2023ApJ...951..118B
['M33']
2023ApJ...951..118B,Breuval et al.2023,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0


2024ApJ...966...89A
['NGC4258' 'NGC5584']
2024ApJ...966...89A,Anand et al. 2024,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0


2024ApJ...966..175N
['M81' 'NGC2403' 'UGC09128']
2024ApJ...966..175N,Newman et al. 2024,0,0,0,0,0,0,0,0,1,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0


2024ApJ...976..177L
['NGC3370' 'NGC5584']
2024ApJ...976..177L,Li et al. 2024,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,1,0


2025A&A...697L...6V
['M33']
2025A&A...697L...6V,Vansevicius 2025,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0

In [14]:
column_x_emptyDF = ['IC0010',
                    'IC2574',
                    'M33',
                    'M81',
                    'M101',
                    'MRK116',
                    'NGC0925',
                    'NGC2366',
                    'NGC2403',
                    'NGC2541',
                    'NGC3198',
                    'NGC3319',
                    'NGC4214',
                    'NGC4236',
                    'NGC4258',
                    'NGC4395',
                    'NGC6822',
                    'NGC1073',
                    'NGC2500',
                    'NGC3184',
                    'M96',
                    'NGC3370',
                    'M66',
                    'NGC4414',
                    'NGC4496A',
                    'NGC4535',
                    'NGC4536',
                    'NGC4725',
                    'UGC08091',
                    'NGC5204',
                    'UGC09128',
                    'NGC5584',                                  
                    'NGC7331',]
Empty_DF = pd.DataFrame(columns=column_x_emptyDF)
Empty_DF

Empty DataFrame
Columns: [IC0010, IC2574, M33, M81, M101, MRK116, NGC0925, NGC2366, NGC2403, NGC2541, NGC3198, NGC3319, NGC4214, NGC4236, NGC4258, NGC4395, NGC6822, NGC1073, NGC2500, NGC3184, M96, NGC3370, M66, NGC4414, NGC4496A, NGC4535, NGC4536, NGC4725, UGC08091, NGC5204, UGC09128, NGC5584, NGC7331]
Index: []

[0 rows x 33 columns]

In [56]:
df = pd.read_csv(os.path.join(tables_dir,PLRC_tab_list[0]))
df['galaxy'] = (PLRC_tab_list[0].split('.')[1]).replace('_PLRC','')

columna_left = df.pop('galaxy')
df.insert(0, 'galaxy', columna_left)

df.rename(columns={
    'RefCode': 'bibcode',
    'Citation': 'citation',
    'Band': 'band',
    'mu_0': 'modulus',
    'e_R': 'random_error',
    'e_S': 'systematic_error',
    'e_T': 'total_error',
    'Category': 'category_error',
    'Ncef': 'cepheids_number',
    'Zcorr': 'metal_correction',
    'zeroP': 'zero_point',
    'Rank': 'probe_quality',
    'Year': 'publication_year',
    'Date': 'review_year',
    'Comments': 'comments',
    'Author': 'review_author',
    'ADS_date': 'ads_date',
    'JD': 'ads_jd',
}, inplace=True)


PLRC_final_DF = pd.concat([Empty_DF,df], ignore_index=True)

/tmp/ipykernel_12736/1176340567.py:29: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  PLRC_final_DF = pd.concat([Empty_DF,df], ignore_index=True)

In [57]:
PLRC_final_DF

,galaxy,bibcode,citation,band,modulus,random_error,systematic_error,total_error,category_error,cepheids_number,metal_correction,zero_point,probe_quality,publication_year,review_year,comments,review_author,ads_date,ads_jd
0,IC0010,2000ApJ...529..745F,Ferrarese et al.2000,W(VI),24.1,0.19,NaN,NaN,1,4,False,LMC,1,2000,2024,There are no specific comments on the publicat...,Valencia et al.2024,2000-02-00,2451575.5

In [ ]:
column_x_emptyDF = ['galaxy',
                    'bibcode',
                    'citation',
                    'band',
                    'modulus',
                    'random_error',
                    'systematic_error',
                    'total_error',
                    'category_error',
                    'cepheids_number',
                    'metal_correction',
                    'zero_point',
                    'probe_quality',
                    'publication_year',
                    'review_year',
                    'comments',
                    'review_author',
                    'ads_date',
                    'ads_jd',]
Empty_DF = pd.DataFrame(columns=column_x_emptyDF)