### Libraries

In [87]:
import re
import os
import numpy as np
from astropy.io import ascii
from astropy.io import fits
from astropy.table import Table
import matplotlib
import matplotlib.pyplot as plt
import pandas as pd
from io import StringIO
from matplotlib.ticker import AutoMinorLocator
from astropy.constants import L_sun
from matplotlib import gridspec
import astropy.units as u
from math import pi
import gc
from matplotlib.ticker import ScalarFormatter
import matplotlib.colors as mcolors
import matplotlib.patheffects as pe
from astropy.table import Column
from scipy.stats import bootstrap

from __future__ import annotations
import os
import json
from astropy.cosmology import FlatwCDM
'''
import pymultinest
import corner
from getdist import plots, MCSamples
import scipy.optimize as op
from scipy import stats
from scipy.stats import norm
from astropy.time import Time
import matplotlib.dates as mdates

from venn import venn
import requests

'''
!pip install venn

from venn import venn
import requests

Requirement already satisfied: venn in /home/holman/.conda/envs/cosmos/lib/python3.11/site-packages (0.1.3)
Requirement already satisfied: matplotlib in /home/holman/.conda/envs/cosmos/lib/python3.11/site-packages (from venn) (3.8.0)
Requirement already satisfied: contourpy>=1.0.1 in /home/holman/.conda/envs/cosmos/lib/python3.11/site-packages (from matplotlib->venn) (1.2.0)
Requirement already satisfied: cycler>=0.10 in /home/holman/.conda/envs/cosmos/lib/python3.11/site-packages (from matplotlib->venn) (0.11.0)
Requirement already satisfied: fonttools>=4.22.0 in /home/holman/.conda/envs/cosmos/lib/python3.11/site-packages (from matplotlib->venn) (4.25.0)
Requirement already satisfied: kiwisolver>=1.0.1 in /home/holman/.conda/envs/cosmos/lib/python3.11/site-packages (from matplotlib->venn) (1.4.4)
Requirement already satisfied: numpy<2,>=1.21 in /home/holman/.conda/envs/cosmos/lib/python3.11/site-packages (from matplotlib->venn) (1.26.4)
Requirement already satisfied: packaging>=20.0 in /home/holman/.conda/envs/cosmos/lib/python3.11/site-packages (from matplotlib->venn) (23.1)
Requirement already satisfied: pillow>=6.2.0 in /home/holman/.conda/envs/cosmos/lib/python3.11/site-packages (from matplotlib->venn) (10.2.0)
Requirement already satisfied: pyparsing>=2.3.1 in /home/holman/.conda/envs/cosmos/lib/python3.11/site-packages (from matplotlib->venn) (3.0.9)
Requirement already satisfied: python-dateutil>=2.7 in /home/holman/.conda/envs/cosmos/lib/python3.11/site-packages (from matplotlib->venn) (2.8.2)
Requirement already satisfied: six>=1.5 in /home/holman/.conda/envs/cosmos/lib/python3.11/site-packages (from python-dateutil>=2.7->matplotlib->venn) (1.16.0)

In [88]:
def HyperLeda(filename):
    """
    Lee una tabla tipo NED/HyperLEDA ignorando comentarios y headers,
    devolviendo todas las columnas en un DataFrame de pandas.
    """

    # Leer el archivo ignorando líneas de comentario
    df = pd.read_csv(
        filename,
        comment="#",
        sep=",",
        engine="python"
    )

    # Limpiar nombres de columnas
    df.columns = [c.strip() for c in df.columns]

    #Convertir todo lo que se pueda a numérico
    #for col in df.columns:
        #df[col] = pd.to_numeric(df[col], errors="ignore")

    return df

def SIMBAD(filename):
    """
    Lee una tabla tipo NED/HyperLEDA ignorando comentarios y headers,
    devolviendo todas las columnas en un DataFrame de pandas.
    """

    # Leer el archivo ignorando líneas de comentario
    df = pd.read_csv(
        filename,
        comment="#",
        sep="|",
        engine="python"
    )

    # Limpiar nombres de columnas
    df.columns = [c.strip() for c in df.columns]

    #Convertir todo lo que se pueda a numérico
    #for col in df.columns:
        #df[col] = pd.to_numeric(df[col], errors="ignore")

    return df

def NED(filename):
    """
    Lee una tabla tipo NED/HyperLEDA ignorando comentarios y headers,
    devolviendo todas las columnas en un DataFrame de pandas.
    """

    # Leer el archivo ignorando líneas de comentario
    df = pd.read_csv(
        filename,
        comment="#",
        sep=",",
        engine="python"
    )

    # Limpiar nombres de columnas
    df.columns = [c.strip() for c in df.columns]

    #Convertir todo lo que se pueda a numérico
    #for col in df.columns:
        #df[col] = pd.to_numeric(df[col], errors="ignore")

    return df

def Prev_Fer(filename):
    """
    Lee una tabla tipo NED/HyperLEDA ignorando comentarios y headers,
    devolviendo todas las columnas en un DataFrame de pandas.
    """

    # Leer el archivo ignorando líneas de comentario
    df = pd.read_csv(
        filename,
        comment="#",
        sep=",",
        engine="python"
    )

    # Limpiar nombres de columnas
    df.columns = [c.strip() for c in df.columns]

    #Convertir todo lo que se pueda a numérico
    #for col in df.columns:
        #df[col] = pd.to_numeric(df[col], errors="ignore")

    return df

In [89]:
df_dist = NED("~/HIIGalaxies/Distance_moduli/Data_NED/19.NGC2500.csv")

df_dist['Method'] = df_dist['Method'].str.strip()
df_dist['Reference'] = df_dist['Reference'].str.strip()
df_dist = df_dist[df_dist['Reference'].str[0:4].astype(int) >= 2000]


PLRC = np.unique(df_dist[(df_dist['Method']=='Cepheids')    &   (df_dist['err(m-M)'].notnull())]['Reference'])
TRGB = np.unique(df_dist[(df_dist['Method']=='TRGB')    &   (df_dist['err(m-M)'].notnull())]['Reference'])
RRLy = np.unique(df_dist[(df_dist['Method']=='RR Lyrae')    &   (df_dist['err(m-M)'].notnull())]['Reference'])

print(len(PLRC), len(TRGB), len(RRLy))

df_dist

0 1 0

,No.,(m-M),err(m-M),Distance,Method,Reference,Notes,SN Name,Redshift,H0,LMCModulus
0,1,30.18,0.46,10.9,TRGB,2018ApJS..235...23S,NaN,NaN,NaN,NaN,NaN

In [90]:
home = os.path.expanduser('~/HIIGalaxies/Distance_moduli/Data_NED/')
list_files = os.listdir(home)
list_files.sort(key=lambda x: int(x.split('.')[0]))

for b in list_files:
    df_dist = NED(f"~/HIIGalaxies/Distance_moduli/Data_NED/{b}")
    df_dist['Method'] = df_dist['Method'].str.strip()
    df_dist['Reference'] = df_dist['Reference'].str.strip()
    df_dist = df_dist[df_dist['Reference'].str[0:4].astype(int) >= 2000]


    PLRC = np.unique(df_dist[(df_dist['Method']=='Cepheids')    ]['Reference']) #&   (df_dist['err(m-M)'].notnull())
    TRGB = np.unique(df_dist[(df_dist['Method']=='TRGB')    ]['Reference']) # &   (df_dist['err(m-M)'].notnull())
    RRLy = np.unique(df_dist[(df_dist['Method']=='RR Lyrae')    ]['Reference']) #&   (df_dist['err(m-M)'].notnull())

    print(len(PLRC),"	", len(TRGB),"	", len(RRLy))
    #print(b,"     ",len(PLRC),"	", len(TRGB),"	", len(RRLy),"\n")
    #b,"     ", ,"\n"

64 	 8 	 40
1 	 9 	 1
0 	 4 	 0
16 	 17 	 6
12 	 8 	 0
14 	 7 	 0
3 	 3 	 0
10 	 0 	 0
1 	 7 	 0
4 	 5 	 0
8 	 0 	 0
11 	 0 	 0
9 	 0 	 0
0 	 8 	 0
0 	 3 	 0
25 	 6 	 0
1 	 4 	 0
14 	 9 	 3
0 	 0 	 0
0 	 1 	 0
0 	 0 	 0
11 	 4 	 0
8 	 1 	 0
12 	 4 	 0
10 	 0 	 0
16 	 0 	 0
10 	 0 	 0
20 	 0 	 0
9 	 0 	 0
1 	 4 	 0
0 	 2 	 0
0 	 8 	 0
3 	 2 	 0
9 	 0 	 0

In [91]:
df_dist = HyperLeda(f"~/HIIGalaxies/Distance_moduli/Data_HyperLeda/0.LMC.csv")
df_dist = df_dist[df_dist['bibcode'].str[0:4].astype(int) >= 2000]
df_dist['$link[method_method]'] = df_dist['$link[method_method]'].str.strip()
df_dist['bibcode'] = df_dist['bibcode'].str.strip()

PLRC = np.unique(df_dist[df_dist['$link[method_method]']=='Cepheids']['bibcode'])
TRGB = np.unique(df_dist[df_dist['$link[method_method]']=='TRGB']['bibcode'])
RRLy = np.unique(df_dist[df_dist['$link[method_method]']=='RRLyrae']['bibcode'])

#print(b,"     ",len(PLRC),"	", len(TRGB),"	", len(RRLy),"\n")

df_dist

,$objname,$j2000,modulus,e_modulus,flimit,fquality,distance,e_distance,flimit.1,fquality.1,modc,$link[method_method],$link[iref_iref],$link[bibref_bibcode],$link[calib_calib_bibcode],pgc,dataset,bibcode,calib_bibcode,calibsys
1,ESO056-115,J052334.6-694522,18.5070,0.003000,NaN,NaN,0.050281,0.000070,NaN,NaN,18.507000,Cepheids,52042,Musella+2016,Cepheids:Fiorentino+2007,17223,52042,2016MNRAS.457.3084M,2007A&A...476..863F,NaN
2,ESO056-115,J052334.6-694522,18.5500,0.060000,NaN,NaN,0.051286,0.001437,NaN,NaN,18.534862,Cepheids,51879,Fouque+2003,Cepheids:Fouque+2003,17223,51879,2003LNP...635...21F,2003LNP...635...21F,NaN
4,ESO056-115,J052334.6-694522,18.3700,0.000000,NaN,NaN,0.047206,0.000000,NaN,NaN,18.398429,Cepheids,51470,Paturel+2002,Cepheids:Lanoix+1999,17223,51470,2002A&A...389...19P,1999MNRAS.308..969L,NaN
5,ESO056-115,J052334.6-694522,18.3400,0.060000,NaN,NaN,0.046559,0.001304,NaN,NaN,18.340000,Cepheids,51540,An+2007,,17223,51540,2007ApJ...671.1640A,NaN,An+2007
6,ESO056-115,J052334.6-694522,18.4000,0.050000,NaN,NaN,0.047863,0.001115,NaN,NaN,18.400000,Cepheids,51538,Benedict+2007,,17223,51538,2007AJ....133.1810B,NaN,Benedict+2007
8,ESO056-115,J052334.6-694522,18.3900,0.050000,NaN,NaN,0.047643,0.001110,NaN,NaN,18.389999,Cepheids,51539,van Leeuwen+2007,,17223,51539,2007MNRAS.379..723V,NaN,vanLeuwen+2007
9,ESO056-115,J052334.6-694522,18.4500,0.050000,NaN,NaN,0.048978,0.001141,NaN,NaN,18.450001,Cepheids,51539,van Leeuwen+2007,,17223,51539,2007MNRAS.379..723V,NaN,vanLeuwen+2007
10,ESO056-115,J052334.6-694522,18.4700,0.030000,NaN,NaN,0.049431,0.000688,NaN,NaN,18.469999,Cepheids,51539,van Leeuwen+2007,,17223,51539,2007MNRAS.379..723V,NaN,vanLeuwen+2007
11,ESO056-115,J052334.6-694522,18.5200,0.030000,NaN,NaN,0.050582,0.000704,NaN,NaN,18.520000,Cepheids,51539,van Leeuwen+2007,,17223,51539,2007MNRAS.379..723V,NaN,vanLeuwen+2007
12,ESO056-115,J052334.6-694522,18.4100,0.160000,NaN,NaN,0.048084,0.003677,NaN,NaN,18.410000,Cepheids,51542,Macri+2006,,17223,51542,2006ApJ...652.1133M,NaN,NaN
13,ESO056-115,J052334.6-694522,18.5000,0.100000,NaN,NaN,0.050119,0.002362,NaN,NaN,18.500000,Cepheids,51332,Sakai+2004,,17223,51332,2004ApJ...608...42S,NaN,NaN
14,ESO056-115,J052334.6-694522,18.5590,0.026000,NaN,NaN,0.051499,0.000620,NaN,NaN,18.559000,Cepheids,51541,di Benedetto2008,,17223,51541,2008MNRAS.390.1762D,NaN,NaN
15,ESO056-115,J052334.6-694522,18.4930,0.008000,NaN,NaN,0.049957,0.000184,NaN,NaN,18.493000,DEB,51850,Pietrzy&nacute;ski+2013,,17223,51850,2013Natur.495...76P,NaN,NaN
16,ESO056-115,J052334.6-694522,18.5200,0.070000,NaN,NaN,0.050582,0.001657,NaN,NaN,18.520000,DEB,51837,Bonanos+2011,,17223,51837,2011ApJ...729L...9B,NaN,NaN
18,ESO056-115,J052334.6-694522,18.2700,0.070000,NaN,NaN,0.045082,0.001477,NaN,NaN,18.270000,RC,52268,Popowski2000,RC:Popowski2000,17223,52268,2000ApJ...528L...9P,2000ApJ...528L...9P,NaN
19,ESO056-115,J052334.6-694522,18.4500,0.070000,NaN,NaN,0.048978,0.001605,NaN,NaN,18.450001,RC,52266,Clementini;+2003,RC:Popowski2000,17223,52266,2003AJ....125.1309C,2000ApJ...528L...9P,NaN
20,ESO056-115,J052334.6-694522,18.2400,0.080000,NaN,NaN,0.044463,0.001669,NaN,NaN,18.240000,RC,52267,Udalski2000,RC:Udalski2000,17223,52267,2000ApJ...531L..25U,2000ApJ...531L..25U,NaN
21,ESO056-115,J052334.6-694522,18.4200,0.070000,NaN,NaN,0.048306,0.001583,NaN,NaN,18.420000,RC,52266,Clementini;+2003,RC:Udalski2000,17223,52266,2003AJ....125.1309C,2000ApJ...531L..25U,NaN
22,ESO056-115,J052334.6-694522,18.4980,0.007000,NaN,NaN,0.050073,0.000162,NaN,NaN,18.497999,RC,51409,Pietrzynski+2003,,17223,51409,2003AJ....125.2494P,NaN,Pietrzynski+2003
23,ESO056-115,J052334.6-694522,18.4600,0.070000,NaN,NaN,0.049204,0.001612,NaN,NaN,18.459999,RC,51195,Borissova+2009,,17223,51195,2009A&A...502..505B,NaN,NaN
24,ESO056-115,J052334.6-694522,18.4700,0.020000,NaN,NaN,0.049431,0.000457,NaN,NaN,18.469999,RC,51599,Laney+2012,,17223,51599,2012MNRAS.419.1637L,NaN,NaN
25,ESO056-115,J052334.6-694522,18.4900,0.060000,NaN,NaN,0.049888,0.001398,NaN,NaN,18.490000,RC,51599,Laney+2012,,17223,51599,2012MNRAS.419.1637L,NaN,NaN
26,ESO056-115,J052334.6-694522,18.5000,0.108000,NaN,NaN,0.050119,0.002556,NaN,NaN,18.500000,RC,51583,Fiorentino+2011,,17223,51583,2011A&A...535A..63F,NaN,NaN
27,ESO056-115,J052334.6-694522,18.5900,0.089443,NaN,NaN,0.052240,0.002197,NaN,NaN,18.590000,RC,51694,Romaniello+2000,,17223,51694,2000ApJ...530..738R,NaN,NaN
28,ESO056-115,J052334.6-694522,18.5300,0.130000,NaN,NaN,0.050816,0.003135,NaN,NaN,18.530001,RRLyrae,51195,Borissova+2009,RRLyrae:Borissova+2009,17223,51195,2009A&A...502..505B,2009A&A...502..505B,Borissova+2009
30,ESO056-115,J052334.6-694522,18.3800,0.160000,NaN,NaN,0.047424,0.003626,NaN,NaN,18.379999,RRLyrae,52266,Clementini;+2003,RRLyrae:MV=0.68,17223,52266,2003AJ....125.1309C,NaN,NaN
31,ESO056-115,J052334.6-694522,18.3000,0.140000,NaN,NaN,0.045709,0.003044,NaN,NaN,18.299999,RRLyrae,52266,Clementini;+2003,RRLyrae:MV=0.76,17223,52266,2003AJ....125.1309C,NaN,NaN
33,ESO056-115,J052334.6-694522,18.5900,0.090000,NaN,NaN,0.052240,0.002211,NaN,NaN,18.598994,TRGB,51332,Sakai+2004,TRGB:Lee+1993,17223,51332,2004ApJ...608...42S,1993ApJ...417..553L,Lee+1993
34,ESO056-115,J052334.6-694522,18.6900,0.257099,NaN,NaN,0.054702,0.006876,NaN,NaN,18.690001,TRGB,51694,Romaniello+2000,,17223,51694,2000ApJ...530..738R,NaN,NaN
35,ESO056-115,J052334.6-694522,18.5000,0.130000,NaN,c,0.050119,0.003092,NaN,c,18.500000,Cepheids,51384,Ferrarese+2000,,17223,51384,2000ApJS..128..431F,NaN,Ferrarese+2000
37,ESO056-115,J052334.6-694522,18.3000,0.040000,NaN,c,0.045709,0.000850,NaN,c,18.299999,Cepheids,51345,Dolphin+2003,,17223,51345,2003AJ....125.1261D,NaN,NaN
38,ESO056-115,J052334.6-694522,18.3200,0.010000,NaN,c,0.046132,0.000213,NaN,c,18.320000,Cepheids,51345,Dolphin+2003,,17223,51345,2003AJ....125.1261D,NaN,NaN
39,ESO056-115,J052334.6-694522,18.4100,0.160000,NaN,c,0.048084,0.003677,NaN,c,18.410000,Cepheids,51471,McCommas+2009,,17223,51471,2009AJ....137.4707M,NaN,NaN
40,ESO056-115,J052334.6-694522,18.4949,NaN,NaN,c,0.050000,NaN,NaN,c,18.494850,Cepheids,51160,Karachentsev+2004,,17223,51160,2004AJ....127.2031K,NaN,NaN
41,ESO056-115,J052334.6-694522,18.5000,0.010000,NaN,c,0.050119,0.000231,NaN,c,18.500000,Cepheids,51345,Dolphin+2003,,17223,51345,2003AJ....125.1261D,NaN,NaN
42,ESO056-115,J052334.6-694522,18.4600,0.110000,NaN,c,0.049204,0.002557,NaN,c,18.459999,RC,51345,Dolphin+2003,,17223,51345,2003AJ....125.1261D,NaN,NaN
43,ESO056-115,J052334.6-694522,18.4700,0.070000,NaN,c,0.049431,0.001619,NaN,c,18.469999,RRLyrae,51345,Dolphin+2003,,17223,51345,2003AJ....125.1261D,NaN,NaN
44,ESO056-115,J052334.6-694522,18.5300,NaN,NaN,c,0.050816,NaN,NaN,c,18.530001,RRLyrae,52014,Tammann+2008,,17223,52014,2008A&ARv..15..289T,NaN,NaN
45,ESO056-115,J052334.6-694522,18.5900,NaN,NaN,c,0.052240,NaN,NaN,c,18.590000,SNIa,52014,Tammann+2008,,17223,52014,2008A&ARv..15..289T,NaN,NaN
46,ESO056-115,J052334.6-694522,18.5200,0.090000,NaN,c,0.050582,0.002141,NaN,c,18.591109,TRGB,51345,Dolphin+2003,TRGB:I=-4.00,17223,51345,2003AJ....125.1261D,NaN,I=-4.00

In [92]:
home = os.path.expanduser('~/HIIGalaxies/Distance_moduli/Data_HyperLeda/')
list_files = os.listdir(home)
list_files.sort(key=lambda x: int(x.split('.')[0]))

for b in list_files:
    df_dist = HyperLeda(f"~/HIIGalaxies/Distance_moduli/Data_HyperLeda/{b}")
    df_dist = df_dist[df_dist['bibcode'].str[0:4].astype(int) >= 2000]
    df_dist['$link[method_method]'] = df_dist['$link[method_method]'].str.strip()
    df_dist['bibcode'] = df_dist['bibcode'].str.strip()

    PLRC = np.unique(df_dist[(df_dist['$link[method_method]']=='Cepheids')   ]['bibcode']) #& (df_dist['e_modulus'].notnull())
    TRGB = np.unique(df_dist[(df_dist['$link[method_method]']=='TRGB')   ]['bibcode']) #& (df_dist['e_modulus'].notnull())
    RRLy = np.unique(df_dist[(df_dist['$link[method_method]']=='RRLyrae')   ]['bibcode']) #& (df_dist['e_modulus'].notnull())

    #print(b,"     ",len(PLRC),"	", len(TRGB),"	", len(RRLy),"\n")
    print(len(PLRC),"	", len(TRGB),"	", len(RRLy))

13 	 3 	 4
3 	 2 	 0
0 	 6 	 0
11 	 12 	 3
9 	 9 	 0
10 	 6 	 0
2 	 2 	 0
9 	 1 	 0
0 	 6 	 0
4 	 5 	 0
7 	 1 	 0
8 	 0 	 0
8 	 0 	 0
0 	 10 	 0
0 	 5 	 0
15 	 7 	 0
2 	 6 	 0
10 	 6 	 2
0 	 0 	 0
0 	 0 	 0
0 	 0 	 0
9 	 3 	 0
2 	 0 	 0
12 	 3 	 0
10 	 0 	 0
11 	 0 	 0
9 	 0 	 0
11 	 0 	 0
8 	 0 	 0
0 	 6 	 0
0 	 6 	 0
0 	 9 	 0
0 	 1 	 0
7 	 0 	 0

In [93]:
home = os.path.expanduser('~/HIIGalaxies/Distance_moduli/Data_SIMBAD/')
list_files = os.listdir(home)
list_files.sort(key=lambda x: int(x.split('.')[0]))

for b in list_files:
    df_dist = SIMBAD(f"~/HIIGalaxies/Distance_moduli/Data_SIMBAD/{b}")
    df_dist = df_dist[df_dist['reference'].str[0:4].astype(int) >= 2000]
    #print(df_dist)
    df_dist['reference'] = df_dist['reference'].str.strip()
    df_dist['method'] = df_dist['method'].str.strip()
    df_dist['err-        err+'] = df_dist['err-        err+'].str.strip()

    PLRC = np.unique(df_dist[(df_dist['method'].str[0:3] == 'Cep')]['reference'])
    TRGB = np.unique(df_dist[((df_dist['method'] == 'T-RGB') | (df_dist['method'] == 'TRGB') )]['reference'])
    RRLy = np.unique(df_dist[(df_dist['method'].str[0:3] == 'RR') ]['reference'])
    NoID = np.unique(df_dist[(df_dist['method'] == '')]['reference'])


    print(len(PLRC),"	", len(TRGB),"	", len(RRLy),"	", len(NoID))
    #b,"     ", ,"\n"

#print(PLRC,TRGB,RRLy)
#print(len(PLRC),"	", len(TRGB),"	", len(RRLy),"	", len(NoID))
#print('+' in df_dist.iloc[6].str[0:20]['err-        err+'])
#df_dist

2 	 0 	 0 	 3
1 	 1 	 0 	 2
0 	 4 	 0 	 3
3 	 1 	 0 	 3
3 	 0 	 0 	 3
2 	 0 	 0 	 5
0 	 0 	 0 	 2
3 	 0 	 0 	 5
1 	 1 	 0 	 3
3 	 1 	 0 	 5
2 	 0 	 0 	 5
5 	 0 	 0 	 4
2 	 0 	 0 	 5
0 	 1 	 0 	 3
0 	 2 	 0 	 5
2 	 0 	 0 	 5
0 	 3 	 0 	 4
3 	 0 	 0 	 4
0 	 0 	 0 	 1
0 	 0 	 0 	 3
0 	 0 	 0 	 3
3 	 0 	 0 	 3
1 	 0 	 0 	 3
3 	 0 	 0 	 4
2 	 0 	 0 	 6
2 	 0 	 0 	 3
2 	 0 	 0 	 3
3 	 0 	 0 	 3
3 	 0 	 0 	 3
1 	 1 	 0 	 3
0 	 3 	 0 	 2
0 	 2 	 0 	 3
0 	 0 	 0 	 2
4 	 0 	 0 	 4

In [94]:
home = os.path.expanduser('~/HIIGalaxies/Distance_moduli/Compilation_tables/')
list_files = os.listdir(home)
list_files.sort(key=lambda x: int(x.split('.')[0]))

PLRC_list = [x for x in list_files if 'PLRC' in x]

for b in PLRC_list:
    df_dist = Prev_Fer(f"~/HIIGalaxies/Distance_moduli/Compilation_tables/{b}")
    PLRC = np.unique(df_dist['RefCode'])

    print(b,"     ",len(PLRC))

1.IC0010_PLRC.csv       1
3.M33_PLRC.csv       12
4.M81_PLRC.csv       10
5.M101_PLRC.csv       10
6.MRK116_PLRC.csv       1
7.NGC0925_PLRC.csv       7
9.NGC2403_PLRC.csv       2
10.NGC2541_PLRC.csv       6
11.NGC3198_PLRC.csv       7
12.NGC3319_PLRC.csv       6
15.NGC4258_PLRC.csv       20
16.NGC4395_PLRC.csv       1
17.NGC6822_PLRC.csv       13
21.M96_PLRC.csv       6
22.NGC3370_PLRC.csv       7
23.M66_PLRC.csv       8
24.NGC4414_PLRC.csv       7
25.NGC4496_PLRC.csv       10
26.NGC4535_PLRC.csv       6
27.NGC4536_PLRC.csv       15
28.NGC4725_PLRC.csv       6
32.NGC5584_PLRC.csv       3

In [95]:
home = os.path.expanduser('~/HIIGalaxies/Distance_moduli/Compilation_tables/')
list_files = os.listdir(home)
list_files.sort(key=lambda x: int(x.split('.')[0]))

TRGB_list = [x for x in list_files if 'TRGB' in x]

for b in TRGB_list:
    df_dist = Prev_Fer(f"~/HIIGalaxies/Distance_moduli/Compilation_tables/{b}")
    TRGB = np.unique(df_dist['RefCode'])

    print(b[0:2],"     ",len(TRGB))

1.       7
2.       4
3.       15
4.       7
5.       7
6.       2
8.       5
9.       5
13       7
14       3
15       6
16       4
17       6
18       1
19       1
21       4
22       1
23       4
29       4
30       2
31       6
32       1

### Meter todo en un txt y luego hacer diagramas de Venn

In [109]:
#Crear archivo en limpio para no sobreescribir

with open(os.path.expanduser('~/HIIGalaxies/Distance_moduli/Venn_diagrams/venn_data.txt'), 'w') as archivo:
    pass

In [110]:
home = os.path.expanduser('~/HIIGalaxies/Distance_moduli/Data_NED')
list_files = os.listdir(home)
list_files.sort(key=lambda x: int(x.split('.')[0]))

for b in list_files:
    df_dist = NED(f"~/HIIGalaxies/Distance_moduli/Data_NED/{b}")
    df_dist['Method'] = df_dist['Method'].str.strip()
    df_dist['Reference'] = df_dist['Reference'].str.strip()
    df_dist = df_dist[df_dist['Reference'].str[0:4].astype(int) >= 2000]
    PLRC = np.unique(df_dist[(df_dist['Method']=='Cepheids')    ]['Reference']) #&   (df_dist['err(m-M)'].notnull())
    TRGB = np.unique(df_dist[(df_dist['Method']=='TRGB')    ]['Reference']) # &   (df_dist['err(m-M)'].notnull())
    RRLy = np.unique(df_dist[(df_dist['Method']=='RR Lyrae')    ]['Reference']) #&   (df_dist['err(m-M)'].notnull())

    Gal_name = b.replace('.csv','')

    PLRC_toTXT,TRGB_toTXT,RRLy_toTXT = [['NED',Gal_name,x,'Cepheids'] for x in PLRC],[['NED',Gal_name,x,'TRGB'] for x in TRGB],[['NED',Gal_name,x,'RRLyrae'] for x in RRLy]

    with open(os.path.expanduser('~/HIIGalaxies/Distance_moduli/Venn_diagrams/venn_data.txt'), "a+") as f:
        for i in range(len(PLRC_toTXT)):
            f.write(f"{PLRC_toTXT[i][0]},{PLRC_toTXT[i][1]},{PLRC_toTXT[i][2]},{PLRC_toTXT[i][3]}\n")
        for i in range(len(TRGB_toTXT)):
            f.write(f"{TRGB_toTXT[i][0]},{TRGB_toTXT[i][1]},{TRGB_toTXT[i][2]},{TRGB_toTXT[i][3]}\n")
        for i in range(len(RRLy_toTXT)):
            f.write(f"{RRLy_toTXT[i][0]},{RRLy_toTXT[i][1]},{RRLy_toTXT[i][2]},{RRLy_toTXT[i][3]}\n")

In [111]:
home = os.path.expanduser('~/HIIGalaxies/Distance_moduli/Data_HyperLeda')
list_files = os.listdir(home)
list_files.sort(key=lambda x: int(x.split('.')[0]))

for b in list_files:
    df_dist = HyperLeda(f"~/HIIGalaxies/Distance_moduli/Data_HyperLeda/{b}")
    df_dist = df_dist[df_dist['bibcode'].str[0:4].astype(int) >= 2000]
    df_dist['$link[method_method]'] = df_dist['$link[method_method]'].str.strip()
    df_dist['bibcode'] = df_dist['bibcode'].str.strip()

    PLRC = np.unique(df_dist[(df_dist['$link[method_method]']=='Cepheids')   ]['bibcode']) #& (df_dist['e_modulus'].notnull())
    TRGB = np.unique(df_dist[(df_dist['$link[method_method]']=='TRGB')   ]['bibcode']) #& (df_dist['e_modulus'].notnull())
    RRLy = np.unique(df_dist[(df_dist['$link[method_method]']=='RRLyrae')   ]['bibcode']) #& (df_dist['e_modulus'].notnull())

    Gal_name = b.replace('.csv','')

    PLRC_toTXT,TRGB_toTXT,RRLy_toTXT = [['HyperLeda',Gal_name,x,'Cepheids'] for x in PLRC],[['HyperLeda',Gal_name,x,'TRGB'] for x in TRGB],[['HyperLeda',Gal_name,x,'RRLyrae'] for x in RRLy]

    with open(os.path.expanduser('~/HIIGalaxies/Distance_moduli/Venn_diagrams/venn_data.txt'), "a+") as f:
        for i in range(len(PLRC_toTXT)):
            f.write(f"{PLRC_toTXT[i][0]},{PLRC_toTXT[i][1]},{PLRC_toTXT[i][2]},{PLRC_toTXT[i][3]}\n")
        for i in range(len(TRGB_toTXT)):
            f.write(f"{TRGB_toTXT[i][0]},{TRGB_toTXT[i][1]},{TRGB_toTXT[i][2]},{TRGB_toTXT[i][3]}\n")
        for i in range(len(RRLy_toTXT)):
            f.write(f"{RRLy_toTXT[i][0]},{RRLy_toTXT[i][1]},{RRLy_toTXT[i][2]},{RRLy_toTXT[i][3]}\n")

In [112]:
home = os.path.expanduser('~/HIIGalaxies/Distance_moduli/Data_SIMBAD')
list_files = os.listdir(home)
list_files.sort(key=lambda x: int(x.split('.')[0]))

for b in list_files:
    df_dist = SIMBAD(f"~/HIIGalaxies/Distance_moduli/Data_SIMBAD/{b}")
    df_dist = df_dist[df_dist['reference'].str[0:4].astype(int) >= 2000]
    #print(df_dist)
    df_dist['reference'] = df_dist['reference'].str.strip()
    df_dist['method'] = df_dist['method'].str.strip()
    df_dist['err-        err+'] = df_dist['err-        err+'].str.strip()

    PLRC = np.unique(df_dist[(df_dist['method'].str[0:3] == 'Cep')]['reference'])
    TRGB = np.unique(df_dist[((df_dist['method'] == 'T-RGB') | (df_dist['method'] == 'TRGB') )]['reference'])
    RRLy = np.unique(df_dist[(df_dist['method'].str[0:3] == 'RR') ]['reference'])
    NoID = np.unique(df_dist[(df_dist['method'] == '')]['reference'])

    Gal_name = b.replace('.csv','')

    PLRC_toTXT,TRGB_toTXT,RRLy_toTXT = [['SIMBAD',Gal_name,x,'Cepheids'] for x in PLRC],[['SIMBAD',Gal_name,x,'TRGB'] for x in TRGB],[['SIMBAD',Gal_name,x,'RRLyrae'] for x in RRLy]

    NoID_toTXT = [['SIMBAD',Gal_name,x,'NoID'] for x in NoID]


    with open(os.path.expanduser('~/HIIGalaxies/Distance_moduli/Venn_diagrams/venn_data.txt'), "a+") as f:
        for i in range(len(PLRC_toTXT)):
            f.write(f"{PLRC_toTXT[i][0]},{PLRC_toTXT[i][1]},{PLRC_toTXT[i][2]},{PLRC_toTXT[i][3]}\n")
        for i in range(len(TRGB_toTXT)):
            f.write(f"{TRGB_toTXT[i][0]},{TRGB_toTXT[i][1]},{TRGB_toTXT[i][2]},{TRGB_toTXT[i][3]}\n")
        for i in range(len(RRLy_toTXT)):
            f.write(f"{RRLy_toTXT[i][0]},{RRLy_toTXT[i][1]},{RRLy_toTXT[i][2]},{RRLy_toTXT[i][3]}\n")
        for i in range(len(NoID_toTXT)):
            f.write(f"{NoID_toTXT[i][0]},{NoID_toTXT[i][1]},{NoID_toTXT[i][2]},{NoID_toTXT[i][3]}\n")

In [113]:
home = os.path.expanduser('~/HIIGalaxies/Distance_moduli/Compilation_tables')
list_files = os.listdir(home)
list_files.sort(key=lambda x: int(x.split('.')[0]))

PLRC_list = [x for x in list_files if 'PLRC' in x]

for b in PLRC_list:

    N_ident = int(b.split('.')[0])

    if ( N_ident < 18 ):

        Gal_name = b.replace('.csv','')
        Gal_name = Gal_name.replace('_PLRC','')
        df_dist = Prev_Fer(f"~/HIIGalaxies/Distance_moduli/Compilation_tables/{b}")
        df_dist = df_dist[df_dist["Author"].str.contains("valencia", case=False, na=False)]
        PLRC = np.unique(df_dist['RefCode'])
        PLRC_toTXT = [['Fernando',Gal_name,x,'Cepheids'] for x in PLRC]
        with open(os.path.expanduser('~/HIIGalaxies/Distance_moduli/Venn_diagrams/venn_data.txt'), "a+") as f:
            for i in range(len(PLRC_toTXT)):
                f.write(f"{PLRC_toTXT[i][0]},{PLRC_toTXT[i][1]},{PLRC_toTXT[i][2]},{PLRC_toTXT[i][3]}\n")


TRGB_list = [x for x in list_files if 'TRGB' in x]

for b in TRGB_list:

    N_ident = int(b.split('.')[0])

    if ( N_ident < 18 ):

        Gal_name = b.replace('.csv','')
        Gal_name = Gal_name.replace('_TRGB','')
        df_dist = Prev_Fer(f"~/HIIGalaxies/Distance_moduli/Compilation_tables/{b}")
        df_dist = df_dist[df_dist["Author"].str.contains("valencia", case=False, na=False)]
        TRGB = np.unique(df_dist['RefCode'])
        TRGB_toTXT = [['Fernando',Gal_name,x,'TRGB'] for x in TRGB]
        with open(os.path.expanduser('~/HIIGalaxies/Distance_moduli/Venn_diagrams/venn_data.txt'), "a+") as f:
            for i in range(len(TRGB_toTXT)):
                f.write(f"{TRGB_toTXT[i][0]},{TRGB_toTXT[i][1]},{TRGB_toTXT[i][2]},{TRGB_toTXT[i][3]}\n")

In [114]:
# Agregar los datos de chavez Manualmente


with open(os.path.expanduser('~/HIIGalaxies/Distance_moduli/Venn_diagrams/venn_data.txt'), "a+") as f:
    f.write(f"Chavez,18.NGC1073,2021AstBu..76..255T,NoID\n")
    f.write(f"Chavez,25.NGC4496,1996ApJS..107..693S,NoID\n")
    f.write(f"Chavez,20.NGC3184,2021MNRAS.501.3621A,NoID\n")
    f.write(f"Chavez,20.NGC3184,2002AJ....124.2490L,NoID\n")

#Chavez,18.NGC1073,2021AstBu..76..255T,NoID
#Chavez,25.NGC4496,1996ApJS..107..693S,NoID
#Chavez,20.NGC3184,2021MNRAS.501.3621A,NoID
#Chavez,20.NGC3184,2002AJ....124.2490L,NoID

In [115]:
df_Venn = pd.read_csv(os.path.expanduser('~/HIIGalaxies/Distance_moduli/Venn_diagrams/venn_data.txt'),
                       sep=',',
                        names=['Source', 'Galaxy', 'Ref','Method'])

In [116]:
def Venn_plotter(Object,DF):
    NAME = Object
    METHOD = ['Cepheids','TRGB','RRLyrae']
    name_method = ['PLRC','TRGB','PLCR']

    for i in range(len(METHOD)):
        NED_v = DF[(DF['Source']=='NED') & (DF['Galaxy']==NAME) & (DF['Method']==METHOD[i]) ]['Ref'].tolist()
        HyperLeda_v = DF[(DF['Source']=='HyperLeda') & (DF['Galaxy']==NAME) & (DF['Method']==METHOD[i]) ]['Ref'].tolist()
        SIMBAD_v = DF[(DF['Source']=='SIMBAD') & (DF['Galaxy']==NAME) & (DF['Method']==METHOD[i]) ]['Ref'].tolist()
        Fernando_v = DF[(DF['Source']=='Fernando') & (DF['Galaxy']==NAME) & (DF['Method']==METHOD[i]) ]['Ref'].tolist()
        if (len(NED_v)>0 and len(HyperLeda_v)>0) or (len(NED_v)>0 and len(SIMBAD_v)>0) or (len(SIMBAD_v)>0 and len(HyperLeda_v)>0):
            Filtering = np.array([len(NED_v)>0,len(HyperLeda_v)>0,len(SIMBAD_v)>0,len(Fernando_v)>0])
            Claves = np.array(['NED','HyperLeda','SIMBAD','Fernando'])
            Sets = np.array([set(NED_v), set(HyperLeda_v), set(SIMBAD_v), set(Fernando_v)])
            Claves = Claves[Filtering]
            Sets = Sets[Filtering]
            galaxy_dict = dict(zip(Claves, Sets))
            fig, ax = plt.subplots(figsize=(8, 8))
            ax.set_title(f"{NAME} - {METHOD[i]}")
            venn(galaxy_dict,ax=ax)
            # Corrección de sintaxis en f-string (comillas simples/dobles)
            ruta_guardado = os.path.expanduser("~/HIIGalaxies/Distance_moduli/Venn_diagrams/")
            fig.savefig(f"{ruta_guardado}{NAME}_{name_method[i]}.png")

            # 3. CRUCIAL: Cierra la figura para liberar la memoria RAM inmediatamente
            plt.close(fig)

In [117]:
Objetos = np.unique(df_Venn['Galaxy'])

for x in Objetos:
    Venn_plotter(x,df_Venn)

In [118]:
with open(os.path.expanduser('~/HIIGalaxies/Distance_moduli/Venn_diagrams/venn_data_NoLMC.txt'), 'w') as archivo:
    pass

In [119]:
df_Venn = pd.read_csv(os.path.expanduser('~/HIIGalaxies/Distance_moduli/Venn_diagrams/venn_data.txt'),
                       sep=',',
                        names=['Source', 'Galaxy', 'Ref','Method'])
NoLMC_data = df_Venn[df_Venn['Galaxy'] != '0.LMC']

NoLMC_data.to_csv(os.path.expanduser('~/HIIGalaxies/Distance_moduli/Venn_diagrams/venn_data_NoLMC.txt'), index=False, header=False)

In [120]:
Final_list = pd.read_csv(os.path.expanduser('~/HIIGalaxies/Distance_moduli/Venn_diagrams/venn_data_NoLMC.txt'),
                       sep=',',
                        names=['Source', 'Galaxy', 'Ref','Method'])

articulos = np.unique(Final_list['Ref'])
articulos.sort()
len(articulos)

157

In [121]:
GEHR_hosts = np.unique(Final_list['Galaxy']).tolist()
GEHR_hosts.sort(key=lambda x: int(x.split('.')[0]))
GEHR_hosts = np.array(GEHR_hosts)
source_methods = np.array(['Fernando', 'NED', 'HyperLeda','SIMBAD','Chavez','Cepheids','TRGB','RRLyrae','NoID'])

header_array =np.concatenate((source_methods,GEHR_hosts))
header_array

array(['Fernando', 'NED', 'HyperLeda', 'SIMBAD', 'Chavez', 'Cepheids',
       'TRGB', 'RRLyrae', 'NoID', '1.IC0010', '2.IC2574', '3.M33',
       '4.M81', '5.M101', '6.MRK116', '7.NGC0925', '8.NGC2366',
       '9.NGC2403', '10.NGC2541', '11.NGC3198', '12.NGC3319',
       '13.NGC4214', '14.NGC4236', '15.NGC4258', '16.NGC4395',
       '17.NGC6822', '18.NGC1073', '19.NGC2500', '20.NGC3184', '21.M96',
       '22.NGC3370', '23.M66', '24.NGC4414', '25.NGC4496', '26.NGC4535',
       '27.NGC4536', '28.NGC4725', '29.UGC08091', '30.NGC5204',
       '31.UGC09128', '32.NGC5584', '33.NGC7331'], dtype='<U11')

In [122]:
Final_list

        Source      Galaxy                  Ref    Method
0          NED    1.IC0010  2000ApJ...529..745F  Cepheids
1          NED    1.IC0010  2000ApJ...529..745F      TRGB
2          NED    1.IC0010  2001ApJ...559..225H      TRGB
3          NED    1.IC0010  2007ApJ...662..272V      TRGB
4          NED    1.IC0010  2008ApJ...688L..69S      TRGB
...        ...         ...                  ...       ...
1005  Fernando  17.NGC6822  2012A&A...540A..49M      TRGB
1006    Chavez  18.NGC1073  2021AstBu..76..255T      NoID
1007    Chavez  25.NGC4496  1996ApJS..107..693S      NoID
1008    Chavez  20.NGC3184  2021MNRAS.501.3621A      NoID
1009    Chavez  20.NGC3184  2002AJ....124.2490L      NoID

[1010 rows x 4 columns]

In [123]:
with open(os.path.expanduser('~/HIIGalaxies/Distance_moduli/Venn_diagrams/articles_track.txt'), 'w') as archivo:
    pass

In [124]:
Articulos_info = []

with open(os.path.expanduser('~/HIIGalaxies/Distance_moduli/Venn_diagrams/articles_track.txt'), "a+") as f:
    f.write(f"Bibcode,{','.join(map(str, header_array))}\n")


for e in articulos:
    item = Final_list[Final_list['Ref']==e]
    #print(item)

    # Bibcode , Checked(Fernando), NED, HyperLeda, SIMBAD, Chavez, PLRC, TRGB, RRLyrae, NoID,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30,31,32,33

    fuentes = np.unique(item['Source'])
    metodo = np.unique(item['Method'])
    gal_host = np.unique(item['Galaxy'])
    filterby_bib = np.concatenate((fuentes,metodo,gal_host))


    matching = np.isin(header_array,filterby_bib)
    matching = np.where(matching, 1, 0)   


    with open(os.path.expanduser('~/HIIGalaxies/Distance_moduli/Venn_diagrams/articles_track.txt'), "a+") as f:
        #f.write(f"{e} {matching}\n")
        f.write(f"{e},{','.join(map(str, matching))}\n")


    #print(e," ",fuentes," ",gal_host," ",metodo)
    #print("\n")
    #print(filterby_bib,"\n")
    #print(e,matching,"\n")

In [125]:
Finally = pd.read_csv(os.path.expanduser('~/HIIGalaxies/Distance_moduli/Venn_diagrams/articles_track.txt'))
Finally.sort_values(by=['Fernando', 'Bibcode', 'NED','HyperLeda','SIMBAD','Chavez','Cepheids','TRGB','RRLyrae','NoID'],inplace=True)
Finally.to_csv(os.path.expanduser('~/HIIGalaxies/Distance_moduli/Venn_diagrams/articles_track_sorted.txt'), index=False)

## Article apereance in Fernando's work

In [128]:
Sorted_articles = pd.read_csv(os.path.expanduser('~/HIIGalaxies/Distance_moduli/Venn_diagrams/articles_track.txt'))

articles  = Sorted_articles[Sorted_articles['Fernando']==1]['Bibcode'].tolist()


articles

['2000ApJ...529..745F',
 '2001ApJ...548..564W',
 '2001ApJ...549..721M',
 '2001ApJ...553...47F',
 '2001ApJ...553..562N',
 '2002A&A...383..125K',
 '2002A&A...389...19P',
 '2002AJ....123..244K',
 '2002AJ....123.1307M',
 '2002AJ....124..811D',
 '2002ApJ...565..959L',
 '2003A&A...411..361K',
 '2003AJ....125.3046D',
 '2004A&A...423..925G',
 '2004AJ....127.2322T',
 '2004AJ....128..224T',
 '2004AJ....128..237B',
 '2004AJ....128.2815P',
 '2004ApJ...608...42S',
 '2004MNRAS.349.1130N',
 '2004MNRAS.350..243M',
 '2005A&A...429..837C',
 '2005A&A...431..127T',
 '2005ApJ...627..739T',
 '2005ApJ...633..810M',
 '2005MNRAS.356..979M',
 '2006AJ....132..729T',
 '2006ApJ...647.1056G',
 '2006ApJ...652.1133M',
 '2006ApJS..165..108S',
 '2007AJ....133.1810B',
 '2007ApJ...661..815R',
 '2007ApJ...662..272V',
 '2007ApJ...667L.151A',
 '2007ApJ...671.1640A',
 '2007MNRAS.379..723V',
 '2008AJ....135.1482S',
 '2008ARep...52...19T',
 '2008ApJ...684..102B',
 '2008ApJ...688L..69S',
 '2008ApJ...689..721M',
 '2008MNRAS.390.1762D',
 '2009AJ....137.4707M',
 '2009AJ....138..332J',
 '2009ApJ...690..389M',
 '2009ApJ...693..936M',
 '2009ApJ...703..816K',
 '2009ApJS..183...67D',
 '2009MNRAS.396.1287S',
 '2010ApJ...718.1118D',
 '2010ApJ...724..799Y',
 '2011A&A...533A..91G',
 '2011AJ....141..194G',
 '2011ApJ...733..124S',
 '2011ApJ...743..176G',
 '2011ApJS..193...26P',
 '2011ApJS..195...18R',
 '2012A&A...540A..49M',
 '2012ApJ...758...11C',
 '2012ApJ...760L..14L',
 '2012MNRAS.421.2998F',
 '2013AJ....146...86T',
 '2013ApJ...773...69G',
 '2013ApJ...777...79M',
 '2013MNRAS.430..546D',
 '2013MNRAS.434.2866F',
 '2014A&A...572A..64M',
 '2014ApJ...794..107R',
 '2014MNRAS.440.1138E',
 '2015AJ....149..183H',
 '2015AstL...41..239T',
 '2015MNRAS.450.3597F',
 '2016AJ....151...88B',
 '2016ApJ...826...56R',
 '2016ApJ...828L...5C',
 '2017ApJ...834...78M',
 '2017ApJ...835...28J',
 '2017ApJ...836...74J',
 '2018ApJS..235...23S',
 '2023ApJ...951..118B']

In [120]:
#!pip install pyfiglet
#!pip install install colorama

import pyfiglet
#from colorama import Fore


fig = pyfiglet.Figlet(font='letters')
text = fig.renderText('18.NGC1073')

with open('GalTitle.txt', 'w') as file:
    # Write the content to the file
    file.write(text)

with open('GalTitle.txt', 'r') as file:
    content = file.read()
    print(content)

 1   88888      NN   NN   GGGG   CCCCC   1   00000  7777777 333333
111 88   88     NNN  NN  GG  GG CC    C 111 00   00     777    3333
 11  88888      NN N NN GG      CC       11 00   00    777    3333
 11 88   88 ... NN  NNN GG   GG CC    C  11 00   00   777       333
111  88888  ... NN   NN  GGGGGG  CCCCC  111  00000   777    333333

In [9]:
content.replace('1.IC0010_PLRC', '1.IC0010_TRGB')

' 1      IIIII  CCCCC   00000   00000   1   00000          PPPPPP  LL      \n111      III  CC    C 00   00 00   00 111 00   00         PP   PP LL      \n 11      III  CC      00   00 00   00  11 00   00         PPPPPP  LL      \n 11 ...  III  CC    C 00   00 00   00  11 00   00         PP      LL      \n111 ... IIIII  CCCCC   00000   00000  111  00000  _______ PP      LLLLLLL \n                                                                          \nRRRRRR   CCCCC  \nRR   RR CC    C \nRRRRRR  CC      \nRR  RR  CC    C \nRR   RR  CCCCC  \n                \n'

In [123]:
import re
import os
import numpy as np
from astropy.io import ascii
from astropy.io import fits
from astropy.table import Table
import matplotlib
import matplotlib.pyplot as plt
import pandas as pd
from io import StringIO
from matplotlib.ticker import AutoMinorLocator
from astropy.constants import L_sun
from matplotlib import gridspec
import astropy.units as u
from math import pi
import gc
from matplotlib.ticker import ScalarFormatter
import matplotlib.colors as mcolors
import matplotlib.patheffects as pe
from astropy.table import Column
from scipy.stats import bootstrap
import requests
from astropy.time import Time

In [124]:
def bibcode_to_jd(bibcode, api_token):
    # 1. Configuración de la consulta a la API de ADS
    url = "https://api.adsabs.harvard.edu/v1/search/query"
    headers = {'Authorization': 'Bearer ' + api_token}
    params = {
        'q': f'identifier:{bibcode}',
        'fl': 'pubdate', # Solo pedimos la fecha de publicación
        'rows': 1
    }

    try:
        response = requests.get(url, params=params, headers=headers)
        response.raise_for_status()
        data = response.json()

        if data['response']['numFound'] == 0:
            return f"No se encontró el Bibcode.{bibcode}"

        # 2. Extraer la fecha (Formato usual de ADS: YYYY-MM-00)
        pubdate_str = data['response']['docs'][0]['pubdate']
        
        # ADS usa "00" para días desconocidos. 
        # Astropy necesita un día válido, así que reemplazamos "00" por "01".
        clean_date = pubdate_str.replace("-00", "-01")
        
        # 3. Convertir a Julian Date usando Astropy
        # Asumimos las 12:00:00 UTC como hora estándar si no existe.
        t = Time(clean_date, format='iso', scale='utc')
        
        return {
            "bibcode": bibcode,
            "pubdate_ads": pubdate_str,
            "julian_date": t.jd
        }

    except Exception as e:
        return f"Error: {e}"

In [127]:
TOKEN = "hAWgut8o369MjD1mArJInPVY2S6BKjzbHQW1ygqg"

bibcode_to_jd("2015MNRAS.454.1000G", TOKEN)

{'bibcode': '2015MNRAS.454.1000G',
 'pubdate_ads': '2015-11-00',
 'julian_date': 2457327.5}

In [2]:
!pip install ipyaladin

from astropy.coordinates import Angle, SkyCoord
from ipyaladin import Aladin, Marker
from pathlib import Path

Collecting ipyaladin
  Downloading ipyaladin-0.7.0-py3-none-any.whl.metadata (7.2 kB)
Requirement already satisfied: anywidget in /home/hollman/miniconda3/envs/cosmos/lib/python3.11/site-packages (from ipyaladin) (0.9.18)
Requirement already satisfied: astropy in /home/hollman/miniconda3/envs/cosmos/lib/python3.11/site-packages (from ipyaladin) (7.2.0)
Requirement already satisfied: ipywidgets>=7.6.0 in /home/hollman/miniconda3/envs/cosmos/lib/python3.11/site-packages (from anywidget->ipyaladin) (8.1.2)
Requirement already satisfied: psygnal>=0.8.1 in /home/hollman/miniconda3/envs/cosmos/lib/python3.11/site-packages (from anywidget->ipyaladin) (0.12.0)
Requirement already satisfied: typing-extensions>=4.2.0 in /home/hollman/miniconda3/envs/cosmos/lib/python3.11/site-packages (from anywidget->ipyaladin) (4.12.2)
Requirement already satisfied: numpy>=1.24 in /home/hollman/miniconda3/envs/cosmos/lib/python3.11/site-packages (from astropy->ipyaladin) (1.26.4)
Requirement already satisfied: pyerfa>=2.0.1.1 in /home/hollman/miniconda3/envs/cosmos/lib/python3.11/site-packages (from astropy->ipyaladin) (2.0.1.5)
Requirement already satisfied: astropy-iers-data>=0.2025.10.27.0.39.10 in /home/hollman/miniconda3/envs/cosmos/lib/python3.11/site-packages (from astropy->ipyaladin) (0.2025.12.8.0.38.44)
Requirement already satisfied: PyYAML>=6.0.0 in /home/hollman/miniconda3/envs/cosmos/lib/python3.11/site-packages (from astropy->ipyaladin) (6.0.1)
Requirement already satisfied: packaging>=22.0.0 in /home/hollman/miniconda3/envs/cosmos/lib/python3.11/site-packages (from astropy->ipyaladin) (23.1)
Requirement already satisfied: comm>=0.1.3 in /home/hollman/miniconda3/envs/cosmos/lib/python3.11/site-packages (from ipywidgets>=7.6.0->anywidget->ipyaladin) (0.2.1)
Requirement already satisfied: ipython>=6.1.0 in /home/hollman/miniconda3/envs/cosmos/lib/python3.11/site-packages (from ipywidgets>=7.6.0->anywidget->ipyaladin) (8.20.0)
Requirement already satisfied: traitlets>=4.3.1 in /home/hollman/miniconda3/envs/cosmos/lib/python3.11/site-packages (from ipywidgets>=7.6.0->anywidget->ipyaladin) (5.7.1)
Requirement already satisfied: widgetsnbextension~=4.0.10 in /home/hollman/miniconda3/envs/cosmos/lib/python3.11/site-packages (from ipywidgets>=7.6.0->anywidget->ipyaladin) (4.0.10)
Requirement already satisfied: jupyterlab-widgets~=3.0.10 in /home/hollman/miniconda3/envs/cosmos/lib/python3.11/site-packages (from ipywidgets>=7.6.0->anywidget->ipyaladin) (3.0.10)
Requirement already satisfied: decorator in /home/hollman/miniconda3/envs/cosmos/lib/python3.11/site-packages (from ipython>=6.1.0->ipywidgets>=7.6.0->anywidget->ipyaladin) (5.1.1)
Requirement already satisfied: jedi>=0.16 in /home/hollman/miniconda3/envs/cosmos/lib/python3.11/site-packages (from ipython>=6.1.0->ipywidgets>=7.6.0->anywidget->ipyaladin) (0.18.1)
Requirement already satisfied: matplotlib-inline in /home/hollman/miniconda3/envs/cosmos/lib/python3.11/site-packages (from ipython>=6.1.0->ipywidgets>=7.6.0->anywidget->ipyaladin) (0.1.6)
Requirement already satisfied: prompt-toolkit<3.1.0,>=3.0.41 in /home/hollman/miniconda3/envs/cosmos/lib/python3.11/site-packages (from ipython>=6.1.0->ipywidgets>=7.6.0->anywidget->ipyaladin) (3.0.43)
Requirement already satisfied: pygments>=2.4.0 in /home/hollman/miniconda3/envs/cosmos/lib/python3.11/site-packages (from ipython>=6.1.0->ipywidgets>=7.6.0->anywidget->ipyaladin) (2.15.1)
Requirement already satisfied: stack-data in /home/hollman/miniconda3/envs/cosmos/lib/python3.11/site-packages (from ipython>=6.1.0->ipywidgets>=7.6.0->anywidget->ipyaladin) (0.2.0)
Requirement already satisfied: pexpect>4.3 in /home/hollman/miniconda3/envs/cosmos/lib/python3.11/site-packages (from ipython>=6.1.0->ipywidgets>=7.6.0->anywidget->ipyaladin) (4.8.0)
Requirement already satisfied: parso<0.9.0,>=0.8.0 in /home/hollman/miniconda3/envs/cosmos/lib/python3.11/site-packages (from jedi>=0.16->ipython>=6.1.0->ipywidgets>=7.6.0->anywidget->ipyaladin) (0.8.3)
Requirement already satisfied: ptyprocess>=0.5 in /home/hollman/miniconda3/envs/cosmos/lib/python3.11/site-packages (from pexpect>4.3->ipython>=6.1.0->ipywidgets>=7.6.0->anywidget->ipyaladin) (0.7.0)
Requirement already satisfied: wcwidth in /home/hollman/miniconda3/envs/cosmos/lib/python3.11/site-packages (from prompt-toolkit<3.1.0,>=3.0.41->ipython>=6.1.0->ipywidgets>=7.6.0->anywidget->ipyaladin) (0.2.5)
Requirement already satisfied: executing in /home/hollman/miniconda3/envs/cosmos/lib/python3.11/site-packages (from stack-data->ipython>=6.1.0->ipywidgets>=7.6.0->anywidget->ipyaladin) (0.8.3)
Requirement already satisfied: asttokens in /home/hollman/miniconda3/envs/cosmos/lib/python3.11/site-packages (from stack-data->ipython>=6.1.0->ipywidgets>=7.6.0->anywidget->ipyaladin) (2.0.5)
Requirement already satisfied: pure-eval in /home/hollman/miniconda3/envs/cosmos/lib/python3.11/site-packages (from stack-data->ipython>=6.1.0->ipywidgets>=7.6.0->anywidget->ipyaladin) (0.2.2)
Requirement already satisfied: six in /home/hollman/miniconda3/envs/cosmos/lib/python3.11/site-packages (from asttokens->stack-data->ipython>=6.1.0->ipywidgets>=7.6.0->anywidget->ipyaladin) (1.16.0)
Downloading ipyaladin-0.7.0-py3-none-any.whl (24 kB)
Installing collected packages: ipyaladin
Successfully installed ipyaladin-0.7.0

In [12]:
aladin = Aladin(
    target=SkyCoord(56.46, 24.10, unit="deg"),
    fov=Angle(2.5, "deg"),
    reticle_size=64,
    reticle_color="#ff89ff",
)
aladin

Aladin()

In [ ]:
#https://cds-astro.github.io/ipyaladin/_collections/notebooks/02_Base_Commands.html