In [44]:
from astroquery.sdss import SDSS
from astroquery.ipac.irsa import Irsa
from astroquery.vizier import Vizier
from astropy import coordinates as coord
from astropy import units as u
from astroquery.ipac.ned import Ned
import numpy as np
import pandas as pd

In [45]:
# Coordenadas de ejemplo
ra, dec = 1.7376141,0.8571812 # en grados
pos = coord.SkyCoord(ra, dec, unit=(u.deg, u.deg), frame='icrs')

# ---- 1. SDSS (u,g,r,i,z) ----
sdss_data = SDSS.query_region(
    pos,
    radius=0.15 * u.arcsec,   # <--- este es el argumento que faltaba
    spectro=False,
    photoobj_fields=[
        'ra','dec',
        'modelMag_u','modelMagErr_u',
        'modelMag_g','modelMagErr_g',
        'modelMag_r','modelMagErr_r',
        'modelMag_i','modelMagErr_i',
        'modelMag_z','modelMagErr_z'
    ]
)

sdss_data

<Table length=2>
       objID               ra        ... modelMag_z modelMagErr_z
       uint64           float64      ...  float64      float64
------------------- ---------------- ... ---------- -------------
1237645879019765919 1.73762334596665 ...    -9999.0       -9999.0
1237645879019831364 1.73757747583687 ...   18.57623    0.05468069

In [3]:
# Coordenadas de ejemplo
ra, dec = 1.7376141,0.8571812 # en grados
pos = coord.SkyCoord(ra, dec, unit=(u.deg, u.deg), frame='icrs')

# ---- 4. WISE (W1–W4) ----
wise = Irsa.query_region(pos, 
                         catalog='allwise_p3as_psd', 
                         spatial='Cone', 
                         radius=0.15*u.arcsec)
wise['w1mpro','w1sigmpro','w2mpro','w2sigmpro','w3mpro','w3sigmpro','w4mpro','w4sigmpro']

<Table length=1>
 w1mpro w1sigmpro  w2mpro w2sigmpro  w3mpro w3sigmpro  w4mpro w4sigmpro
  mag      mag      mag      mag      mag      mag      mag      mag
float32  float32  float32  float32  float32  float32  float32  float32
------- --------- ------- --------- ------- --------- ------- ---------
 16.286     0.074  15.521     0.121  10.896     0.132   7.271     0.123

In [46]:
result_table = Ned.get_table("UM 199", table='photometry')


result_table[result_table['Observed Passband']=='FUV (GALEX) AB']

<Table length=4>
 No.  Observed Passband ...      Comments
                        ...
int32       object      ...       object
----- ----------------- ... -----------------
    1    FUV (GALEX) AB ... From new raw data
    2    FUV (GALEX) AB ... From new raw data
    3    FUV (GALEX) AB ... From new raw data
    4    FUV (GALEX) AB ... From new raw data

In [5]:
np.unique(result_table['Observed Passband'])

<MaskedColumn name='Observed Passband' dtype='object' length=27>
      FUV (GALEX) AB
        H{beta} line
      NUV (GALEX) AB
           W1 (WISE)
           W2 (WISE)
           W3 (WISE)
           W4 (WISE)
  g (SDSS CModel) AB
   g (SDSS Model) AB
     g (SDSS PSF) AB
g (SDSS Petrosian)AB
  i (SDSS CModel) AB
                 ...
  r (SDSS CModel) AB
   r (SDSS Model) AB
     r (SDSS PSF) AB
r (SDSS Petrosian)AB
  u (SDSS CModel) AB
   u (SDSS Model) AB
     u (SDSS PSF) AB
u (SDSS Petrosian)AB
  z (SDSS CModel) AB
   z (SDSS Model) AB
     z (SDSS PSF) AB
z (SDSS Petrosian)AB

In [ ]:
import os
HOME = os.path.expanduser("~") + '/gdrive/DataHII/'

def magAB_to_flux(mag, mag_err):
    f = 10**(-0.4 * (mag - 8.90))
    ferr = f * np.log(10)/2.5 * mag_err
    return f, ferr

WISE_ZP = {
    'W1': 309.540,
    'W2': 171.787,
    'W3': 31.674,
    'W4': 8.363
}

def vega_to_jy(mag, mag_err, band):
    """Convierte magnitudes Vega de WISE a flux (Jy) con error."""
    f0 = WISE_ZP[band.upper()]
    f = f0 * 10**(-0.4 * mag)
    ferr = f * np.log(10)/2.5 * mag_err
    return f, ferr



def GALEX_data(table,filter_band):
    
    TABLE = table[(table['Observed Passband']==filter_band)]

    check = np.unique(TABLE['Significance'])

    # OJO con esto despues, hay un valor malo aqui es el "SBS 0926+606A" para el FUV
    if ((np.where(check == 'no uncertainty reported'))!= 0)  and (len(np.unique(TABLE['Uncertainty']))==1):
        #CHOSEN = table[table['Significance']=='no uncertainty reported']
        flx = TABLE['Photometry Measurement'][0]

        fx_mJy, fxerr_mJy = magAB_to_flux(flx, 0.0)

        #return flx, flx_err
        #return fx_mJy, fxerr_mJy
        fxerr_mJy = np.random.uniform(low=0,high=0.018)
        return fx_mJy * 1e3 , fxerr_mJy * 1e3
    
    else:
        TABLE = table[(table['Observed Passband']==filter_band) & (table['Qualifiers']=='Kron flux in elliptical aperture')]
        errors = np.array(TABLE['Uncertainty'])

        Err_min = np.min(errors)

        CHOSEN = TABLE[TABLE['Uncertainty']==Err_min]


        flx = CHOSEN['Photometry Measurement'][0]
        flx_err = float(CHOSEN['Uncertainty'][0].replace("+/-",""))

        fx_mJy, fxerr_mJy = magAB_to_flux(flx, flx_err)

        #return flx, flx_err
        #return fx_mJy, fxerr_mJy
        return fx_mJy * 1e3 , fxerr_mJy * 1e3



def SDSS_data(table,filter_band):
    TABLE = table[(table['Observed Passband']==filter_band)]

    Ref = np.array(TABLE['Refcode'])

    Older_ref = np.max(Ref)

    CHOSEN = TABLE[TABLE['Refcode']==Older_ref]


    flx = CHOSEN['Photometry Measurement'][0]
    flx_err = float(CHOSEN['Uncertainty'][0].replace("+/-",""))

    fx_mJy, fxerr_mJy = magAB_to_flux(flx, flx_err)

    #return flx, flx_err
    #return fx_mJy, fxerr_mJy
    return fx_mJy * 1e3 , fxerr_mJy * 1e3










def WISE_data(table,filter_band):

    band = filter_band[0:2]

    TABLE = table[(table['Observed Passband']==filter_band) & (table['Qualifiers']=='Profile-fit')]

    CHOSEN = TABLE


    flx = CHOSEN['Photometry Measurement'][0]

    str_removal = CHOSEN['Uncertainty'][0].replace("+/-","")
    str_removal = str_removal.replace(">","")

    flx_err = float(str_removal)
    #flx_err = float(CHOSEN['Uncertainty'][0].replace(">",""))

    if ('-' in str(flx)) or ('-' in str(flx_err)):
        return np.nan , np.nan
    else:
        fx_mJy, fxerr_mJy = vega_to_jy(flx, flx_err,band)
        #return flx, flx_err
        #return fx_mJy, fxerr_mJy
        return fx_mJy * 1e3 , fxerr_mJy * 1e3

In [7]:
# Sacando los datos para CIGALE

DF = pd.read_csv(HOME+'/SPS/HIIGs_aladin.csv')

head = "# id redshift galex.FUV galex.FUV_err galex.NUV galex.NUV_err "
head = head + "sloan.sdss.u sloan.sdss.u_err sloan.sdss.g sloan.sdss.g_err sloan.sdss.r sloan.sdss.r_err sloan.sdss.i sloan.sdss.i_err sloan.sdss.z sloan.sdss.z_err "
head = head + "wise.W1 wise.W1_err wise.W2 wise.W2_err wise.W3 wise.W3_err wise.W4 wise.W4_err \n"

with open("cigale_HIIG_sample.txt", 'w') as file:
    file.write(head)


    for n in range(len(DF)):

        name = DF['Name'][n]

        filters = ['FUV (GALEX) AB', 'NUV (GALEX) AB','u (SDSS Model) AB','g (SDSS Model) AB','r (SDSS Model) AB','i (SDSS Model) AB','z (SDSS Model) AB',
                  'W1 (WISE)','W2 (WISE)','W3 (WISE)','W4 (WISE)']
        NED_table = Ned.get_table(name, table='photometry')
        ned_filters = np.unique(NED_table['Observed Passband'])

        idx,z = '',0
        fuv,nuv,u,g,r,i,z,W1,W2,W3,W4 = 0,0,0,0,0,0,0,0,0,0,0
        e1,e2,e3,e4,e5,e6,e7,e8,e9,e10,e11 = 0,0,0,0,0,0,0,0,0,0,0

        cond = (filters[0] in ned_filters) and (filters[1] in ned_filters) and (filters[2] in ned_filters) and (filters[3] in ned_filters) and (filters[4] in ned_filters) \
            and (filters[5] in ned_filters) and (filters[6] in ned_filters) and (filters[7] in ned_filters) and (filters[8] in ned_filters) and (filters[9] in ned_filters)

        
        if cond:
            idx = str(DF['N'][n]) + '_' + str(DF['Name'][n]).replace(' ','')
            z = DF['Z'][n]
            print(idx)

            fuv,e1 = GALEX_data(NED_table,filters[0])
            nuv,e2 = GALEX_data(NED_table,filters[1])

            u,e3 = SDSS_data(NED_table,filters[2])
            g,e4 = SDSS_data(NED_table,filters[3])
            r,e5 = SDSS_data(NED_table,filters[4])
            i,e6 = SDSS_data(NED_table,filters[5])
            z,e7 = SDSS_data(NED_table,filters[6])

            W1,e8 = WISE_data(NED_table,filters[7])
            W2,e9 = WISE_data(NED_table,filters[8])
            W3,e10 = WISE_data(NED_table,filters[9])
            W4,e11 = WISE_data(NED_table,filters[10])



            output = f"{idx} {z} {fuv} {e1} {nuv} {e2} "
            output = output + f"{u} {e3} {g} {e4} {r} {e5} {i} {e6} {z} {e7} "
            output = output + f"{W1} {e8} {W2} {e9} {W3} {e10} {W4} {e11} \n"

            file.write(output)

0_UM199
1_UM282
2_UM336
4_SBS0934+546
5_UM570
6_UM162
10_SHOC391
11_WAS69
12_WAS17
14_WISEAJ095227.57+322810.3
15_WISEAJ094252.78+354725.7
16_WISEAJ105040.86+342946.3
17_TOLOLO1057+083
20_SHOC143
21_SHOC220
22_SHOC316
23_SHOC008
24_SBS0813+521
25_WISEAJ094809.88+425713.1
28_SHOC022
29_WISEAJ121329.48+114057.2
31_WISEAJ130119.26+123959.7
32_WISEAJ104653.98+134646.4
33_SHOC293
34_SBS0926+606A
36_SHOC282
38_SHOC014
39_SHOC043
40_SHOC113
41_SHOC592
42_SHOC590
43_SHOC247
44_WISEAJ231442.11+010621.6
46_SHOC084
47_SHOC115
48_SHOC133
51_SHOC153
52_SHOC174
53_SHOC203
57_SHOC486
58_SHOC584
59_SHOC586
60_SHOC595
62_WISEAJ104457.84+035312.9
63_WISEAJ105326.00+043014.5
65_WISEAJ220802.85+131334.5
66_WISEAJ212043.94+010006.9
67_WISEAJ104755.92+073951.2
68_WISEAJ214350.85-072003.9
69_WISEAJ092540.91+063116.8
71_WISEAJ092749.17+084037.1
72_WISEAJ101036.62+641242.6
73_WISEAJ100746.48+025229.1
74_WISEAJ222510.11-001153.1
76_WISEAJ105210.40+032712.7
78_WISEAJ102429.21+052451.0
79_WISEAJ090531.04+033530.3
82_WISEAJ225140.29+132713.7
83_WISEAJ230123.64+133314.2
85_WISEAJ224556.90+125022.4
86_WISEAJ081334.13+313251.9
87_WISEAJ080000.72+274641.8
89_WISEAJ084219.11+300703.6
91_WISEAJ074806.32+193146.4
96_WISEAJ080619.49+194927.2
97_WISEAJ081420.73+575007.7
98_WISEAJ105108.90+131928.2
99_WISEAJ074947.00+154013.4
100_WISEAJ090418.13+260106.2
101_WISEAJ082722.53+202613.0
103_WISEAJ142342.85+225728.4
108_WISEAJ085221.70+121651.7
109_WISEAJ083946.00+140033.4
111_WISEAJ100720.55+193348.5
112_WISEAJ091640.96+182808.4
113_WISEAJ093424.08+222522.6
114_WISEAJ084000.36+180530.9
115_WISEAJ103726.55+270759.4
117_WISEAJ101136.07+263027.5
118_WISEAJ162152.58+151855.9

In [8]:
#Numero de galaxias con datos completos

DF = pd.read_csv(HOME+'/SPS/HIIGs_aladin.csv')

HIIG_names = np.array(DF['Name'])

print('Name | FUV | NUV | u | g | r | i | z | W1 | W2 | W3 | W4 | ALL |')

sep = ' | '

name_id = 0

Found = 0

for name in HIIG_names:
    result_table = Ned.get_table(name, table='photometry')
    filters = np.unique(result_table['Observed Passband'])

    c = 0 

    tab = str(name_id) + '_id' + sep

    #FUV
    if 'FUV (GALEX) AB' in filters:
        tab += str(1) + sep
        c += 1
    else:
        tab += str(0) + sep
    #NUV
    if 'NUV (GALEX) AB' in filters:
        tab += str(1) + sep
        c += 1
    else:
        tab += str(0) + sep
    #u
    if 'u (SDSS Model) AB' in filters:
        tab += str(1) + sep
        c += 1
    else:
        tab += str(0) + sep
    #g
    if 'g (SDSS Model) AB' in filters:
        tab += str(1) + sep
        c += 1
    else:
        tab += str(0) + sep
    #r
    if 'r (SDSS Model) AB' in filters:
        tab += str(1) + sep
        c += 1
    else:
        tab += str(0) + sep
    #i
    if 'i (SDSS Model) AB' in filters:
        tab += str(1) + sep
        c += 1
    else:
        tab += str(0) + sep
    #z
    if 'z (SDSS Model) AB' in filters:
        tab += str(1) + sep
        c += 1
    else:
        tab += str(0) + sep
    #W1
    if 'W1 (WISE)' in filters:
        tab += str(1) + sep
        c += 1
    else:
        tab += str(0) + sep
    #W2
    if 'W2 (WISE)' in filters:
        tab += str(1) + sep
        c += 1
    else:
        tab += str(0) + sep
    #W3
    if 'W3 (WISE)' in filters:
        tab += str(1) + sep
        c += 1
    else:
        tab += str(0) + sep
    #W4
    if 'W4 (WISE)' in filters:
        tab += str(1) + sep
        c += 1
    else:
        tab += str(0) + sep
    


    if c == 11:
        tab += '  All found' + sep
        Found += 1
        print(tab + name)
    else:
        tab += str(0) + sep


    

    name_id += 1

print(f'\n Found complete:{Found}')

Name | FUV | NUV | u | g | r | i | z | W1 | W2 | W3 | W4 | ALL |
0_id | 1 | 1 | 1 | 1 | 1 | 1 | 1 | 1 | 1 | 1 | 1 |   All found | UM 199
1_id | 1 | 1 | 1 | 1 | 1 | 1 | 1 | 1 | 1 | 1 | 1 |   All found | UM 282
2_id | 1 | 1 | 1 | 1 | 1 | 1 | 1 | 1 | 1 | 1 | 1 |   All found | UM 336
4_id | 1 | 1 | 1 | 1 | 1 | 1 | 1 | 1 | 1 | 1 | 1 |   All found | SBS 0934+546
5_id | 1 | 1 | 1 | 1 | 1 | 1 | 1 | 1 | 1 | 1 | 1 |   All found | UM 570
6_id | 1 | 1 | 1 | 1 | 1 | 1 | 1 | 1 | 1 | 1 | 1 |   All found | UM 162
10_id | 1 | 1 | 1 | 1 | 1 | 1 | 1 | 1 | 1 | 1 | 1 |   All found | SHOC 391
11_id | 1 | 1 | 1 | 1 | 1 | 1 | 1 | 1 | 1 | 1 | 1 |   All found | WAS 69
12_id | 1 | 1 | 1 | 1 | 1 | 1 | 1 | 1 | 1 | 1 | 1 |   All found | WAS 17
14_id | 1 | 1 | 1 | 1 | 1 | 1 | 1 | 1 | 1 | 1 | 1 |   All found | WISEA J095227.57+322810.3
15_id | 1 | 1 | 1 | 1 | 1 | 1 | 1 | 1 | 1 | 1 | 1 |   All found | WISEA J094252.78+354725.7
16_id | 1 | 1 | 1 | 1 | 1 | 1 | 1 | 1 | 1 | 1 | 1 |   All found | WISEA J105040.86+342946.3
17_id | 1 | 1 | 1 | 1 | 1 | 1 | 1 | 1 | 1 | 1 | 1 |   All found | TOLOLO 1057+083
20_id | 1 | 1 | 1 | 1 | 1 | 1 | 1 | 1 | 1 | 1 | 1 |   All found | SHOC 143
21_id | 1 | 1 | 1 | 1 | 1 | 1 | 1 | 1 | 1 | 1 | 1 |   All found | SHOC 220
22_id | 1 | 1 | 1 | 1 | 1 | 1 | 1 | 1 | 1 | 1 | 1 |   All found | SHOC 316
23_id | 1 | 1 | 1 | 1 | 1 | 1 | 1 | 1 | 1 | 1 | 1 |   All found | SHOC 008
24_id | 1 | 1 | 1 | 1 | 1 | 1 | 1 | 1 | 1 | 1 | 1 |   All found | SBS 0813+521
25_id | 1 | 1 | 1 | 1 | 1 | 1 | 1 | 1 | 1 | 1 | 1 |   All found | WISEA J094809.88+425713.1
28_id | 1 | 1 | 1 | 1 | 1 | 1 | 1 | 1 | 1 | 1 | 1 |   All found | SHOC 022
29_id | 1 | 1 | 1 | 1 | 1 | 1 | 1 | 1 | 1 | 1 | 1 |   All found | WISEA J121329.48+114057.2
31_id | 1 | 1 | 1 | 1 | 1 | 1 | 1 | 1 | 1 | 1 | 1 |   All found | WISEA J130119.26+123959.7
32_id | 1 | 1 | 1 | 1 | 1 | 1 | 1 | 1 | 1 | 1 | 1 |   All found | WISEA J104653.98+134646.4
33_id | 1 | 1 | 1 | 1 | 1 | 1 | 1 | 1 | 1 | 1 | 1 |   All found | SHOC 293
34_id | 1 | 1 | 1 | 1 | 1 | 1 | 1 | 1 | 1 | 1 | 1 |   All found | SBS 0926+606A
36_id | 1 | 1 | 1 | 1 | 1 | 1 | 1 | 1 | 1 | 1 | 1 |   All found | SHOC 282
38_id | 1 | 1 | 1 | 1 | 1 | 1 | 1 | 1 | 1 | 1 | 1 |   All found | SHOC 014
39_id | 1 | 1 | 1 | 1 | 1 | 1 | 1 | 1 | 1 | 1 | 1 |   All found | SHOC 043
40_id | 1 | 1 | 1 | 1 | 1 | 1 | 1 | 1 | 1 | 1 | 1 |   All found | SHOC 113
41_id | 1 | 1 | 1 | 1 | 1 | 1 | 1 | 1 | 1 | 1 | 1 |   All found | SHOC 592
42_id | 1 | 1 | 1 | 1 | 1 | 1 | 1 | 1 | 1 | 1 | 1 |   All found | SHOC 590
43_id | 1 | 1 | 1 | 1 | 1 | 1 | 1 | 1 | 1 | 1 | 1 |   All found | SHOC 247
44_id | 1 | 1 | 1 | 1 | 1 | 1 | 1 | 1 | 1 | 1 | 1 |   All found | WISEA J231442.11+010621.6
46_id | 1 | 1 | 1 | 1 | 1 | 1 | 1 | 1 | 1 | 1 | 1 |   All found | SHOC 084
47_id | 1 | 1 | 1 | 1 | 1 | 1 | 1 | 1 | 1 | 1 | 1 |   All found | SHOC 115
48_id | 1 | 1 | 1 | 1 | 1 | 1 | 1 | 1 | 1 | 1 | 1 |   All found | SHOC 133
51_id | 1 | 1 | 1 | 1 | 1 | 1 | 1 | 1 | 1 | 1 | 1 |   All found | SHOC 153
52_id | 1 | 1 | 1 | 1 | 1 | 1 | 1 | 1 | 1 | 1 | 1 |   All found | SHOC 174
53_id | 1 | 1 | 1 | 1 | 1 | 1 | 1 | 1 | 1 | 1 | 1 |   All found | SHOC 203
57_id | 1 | 1 | 1 | 1 | 1 | 1 | 1 | 1 | 1 | 1 | 1 |   All found | SHOC 486
58_id | 1 | 1 | 1 | 1 | 1 | 1 | 1 | 1 | 1 | 1 | 1 |   All found | SHOC 584
59_id | 1 | 1 | 1 | 1 | 1 | 1 | 1 | 1 | 1 | 1 | 1 |   All found | SHOC 586
60_id | 1 | 1 | 1 | 1 | 1 | 1 | 1 | 1 | 1 | 1 | 1 |   All found | SHOC 595
62_id | 1 | 1 | 1 | 1 | 1 | 1 | 1 | 1 | 1 | 1 | 1 |   All found | WISEA J104457.84+035312.9
63_id | 1 | 1 | 1 | 1 | 1 | 1 | 1 | 1 | 1 | 1 | 1 |   All found | WISEA J105326.00+043014.5
65_id | 1 | 1 | 1 | 1 | 1 | 1 | 1 | 1 | 1 | 1 | 1 |   All found | WISEA J220802.85+131334.5
66_id | 1 | 1 | 1 | 1 | 1 | 1 | 1 | 1 | 1 | 1 | 1 |   All found | WISEA J212043.94+010006.9
67_id | 1 | 1 | 1 | 1 | 1 | 1 | 1 | 1 | 1 | 1 | 1 |   All found | WISEA J104755.92+073951.2
68_id | 1 | 1 | 1 | 1 | 1 | 1 | 1 | 1 | 1 | 1 | 1 |   All found | WISEA J214350.85-072003.9
69_id | 1 | 1 | 1 | 1 | 1 | 1 | 1 | 1 | 1 | 1 | 1 |   All found | WISEA J092540.91+063116.8
71_id | 1 | 1 | 1 | 1 | 1 | 1 | 1 | 1 | 1 | 1 | 1 |   All found | WISEA J092749.17+084037.1
72_id | 1 | 1 | 1 | 1 | 1 | 1 | 1 | 1 | 1 | 1 | 1 |   All found | WISEA J101036.62+641242.6
73_id | 1 | 1 | 1 | 1 | 1 | 1 | 1 | 1 | 1 | 1 | 1 |   All found | WISEA J100746.48+025229.1
74_id | 1 | 1 | 1 | 1 | 1 | 1 | 1 | 1 | 1 | 1 | 1 |   All found | WISEA J222510.11-001153.1
76_id | 1 | 1 | 1 | 1 | 1 | 1 | 1 | 1 | 1 | 1 | 1 |   All found | WISEA J105210.40+032712.7
78_id | 1 | 1 | 1 | 1 | 1 | 1 | 1 | 1 | 1 | 1 | 1 |   All found | WISEA J102429.21+052451.0
79_id | 1 | 1 | 1 | 1 | 1 | 1 | 1 | 1 | 1 | 1 | 1 |   All found | WISEA J090531.04+033530.3
82_id | 1 | 1 | 1 | 1 | 1 | 1 | 1 | 1 | 1 | 1 | 1 |   All found | WISEA J225140.29+132713.7
83_id | 1 | 1 | 1 | 1 | 1 | 1 | 1 | 1 | 1 | 1 | 1 |   All found | WISEA J230123.64+133314.2
85_id | 1 | 1 | 1 | 1 | 1 | 1 | 1 | 1 | 1 | 1 | 1 |   All found | WISEA J224556.90+125022.4
86_id | 1 | 1 | 1 | 1 | 1 | 1 | 1 | 1 | 1 | 1 | 1 |   All found | WISEA J081334.13+313251.9
87_id | 1 | 1 | 1 | 1 | 1 | 1 | 1 | 1 | 1 | 1 | 1 |   All found | WISEA J080000.72+274641.8
89_id | 1 | 1 | 1 | 1 | 1 | 1 | 1 | 1 | 1 | 1 | 1 |   All found | WISEA J084219.11+300703.6
91_id | 1 | 1 | 1 | 1 | 1 | 1 | 1 | 1 | 1 | 1 | 1 |   All found | WISEA J074806.32+193146.4
96_id | 1 | 1 | 1 | 1 | 1 | 1 | 1 | 1 | 1 | 1 | 1 |   All found | WISEA J080619.49+194927.2
97_id | 1 | 1 | 1 | 1 | 1 | 1 | 1 | 1 | 1 | 1 | 1 |   All found | WISEA J081420.73+575007.7
98_id | 1 | 1 | 1 | 1 | 1 | 1 | 1 | 1 | 1 | 1 | 1 |   All found | WISEA J105108.90+131928.2
99_id | 1 | 1 | 1 | 1 | 1 | 1 | 1 | 1 | 1 | 1 | 1 |   All found | WISEA J074947.00+154013.4
100_id | 1 | 1 | 1 | 1 | 1 | 1 | 1 | 1 | 1 | 1 | 1 |   All found | WISEA J090418.13+260106.2
101_id | 1 | 1 | 1 | 1 | 1 | 1 | 1 | 1 | 1 | 1 | 1 |   All found | WISEA J082722.53+202613.0
103_id | 1 | 1 | 1 | 1 | 1 | 1 | 1 | 1 | 1 | 1 | 1 |   All found | WISEA J142342.85+225728.4
108_id | 1 | 1 | 1 | 1 | 1 | 1 | 1 | 1 | 1 | 1 | 1 |   All found | WISEA J085221.70+121651.7
109_id | 1 | 1 | 1 | 1 | 1 | 1 | 1 | 1 | 1 | 1 | 1 |   All found | WISEA J083946.00+140033.4
111_id | 1 | 1 | 1 | 1 | 1 | 1 | 1 | 1 | 1 | 1 | 1 |   All found | WISEA J100720.55+193348.5
112_id | 1 | 1 | 1 | 1 | 1 | 1 | 1 | 1 | 1 | 1 | 1 |   All found | WISEA J091640.96+182808.4
113_id | 1 | 1 | 1 | 1 | 1 | 1 | 1 | 1 | 1 | 1 | 1 |   All found | WISEA J093424.08+222522.6
114_id | 1 | 1 | 1 | 1 | 1 | 1 | 1 | 1 | 1 | 1 | 1 |   All found | WISEA J084000.36+180530.9
115_id | 1 | 1 | 1 | 1 | 1 | 1 | 1 | 1 | 1 | 1 | 1 |   All found | WISEA J103726.55+270759.4
117_id | 1 | 1 | 1 | 1 | 1 | 1 | 1 | 1 | 1 | 1 | 1 |   All found | WISEA J101136.07+263027.5
118_id | 1 | 1 | 1 | 1 | 1 | 1 | 1 | 1 | 1 | 1 | 1 |   All found | WISEA J162152.58+151855.9

 Found complete:80

In [9]:
from astroquery.vizier import Vizier
from astropy.coordinates import SkyCoord
import astropy.units as u
import pandas as pd
Vizier.clear_cache()

In [25]:
DF

,N,Name,ra,dec,Z,PLATE,MJD,FIBERID
0,0,UM 199,1.737614,0.857181,0.073682,388,51793,457
1,1,UM 282,12.947112,0.161124,0.037556,394,51913,472
2,2,UM 336,23.436174,0.953078,0.019236,400,51820,441
3,3,MRK 0627,131.643397,36.438978,0.010634,934,52672,369
4,4,SBS 0934+546,144.556301,54.473618,0.102102,556,51991,224
...,...,...,...,...,...,...,...,...
116,116,WISEA J103226.97+271755.3,158.112320,27.298679,0.192490,2353,53794,585
117,117,WISEA J101136.07+263027.5,152.900317,26.507660,0.054666,2347,53757,501
118,118,WISEA J162152.58+151855.9,245.469098,15.315537,0.034341,2208,53880,306
119,119,WISEA J090506.84+223834.7,136.278600,22.642759,0.125548,2284,53708,545
120,120,WISEA J094000.50+203122.7,145.002109,20.522973,0.044799,2361,53762,523

In [42]:
Vizier.ROW_LIMIT = 10000 
for i in range(len(DF)):
    ra, dec = DF['ra'][i], DF['dec'][i]
    pos = SkyCoord(ra=ra*u.deg, dec=dec*u.deg, frame="icrs")

    cat_id = "II/319/las9"

    res = Vizier.query_region(pos, radius=1*u.arcsec, catalog=cat_id)

    if res:
        tab = res[0]
        df = tab.to_pandas()
        LEN = len(df)
    else:
        print("Sin detección en UKIDSS dentro del radio dado  ",i)

Sin detección en UKIDSS dentro del radio dado   3
Sin detección en UKIDSS dentro del radio dado   4
Sin detección en UKIDSS dentro del radio dado   7
Sin detección en UKIDSS dentro del radio dado   8
Sin detección en UKIDSS dentro del radio dado   9
Sin detección en UKIDSS dentro del radio dado   12
Sin detección en UKIDSS dentro del radio dado   13
Sin detección en UKIDSS dentro del radio dado   14
Sin detección en UKIDSS dentro del radio dado   15
Sin detección en UKIDSS dentro del radio dado   16
Sin detección en UKIDSS dentro del radio dado   19
Sin detección en UKIDSS dentro del radio dado   21
Sin detección en UKIDSS dentro del radio dado   22
Sin detección en UKIDSS dentro del radio dado   23
Sin detección en UKIDSS dentro del radio dado   24
Sin detección en UKIDSS dentro del radio dado   25
Sin detección en UKIDSS dentro del radio dado   26
Sin detección en UKIDSS dentro del radio dado   34
Sin detección en UKIDSS dentro del radio dado   38
Sin detección en UKIDSS dentro del radio dado   39
Sin detección en UKIDSS dentro del radio dado   40
Sin detección en UKIDSS dentro del radio dado   41
Sin detección en UKIDSS dentro del radio dado   42
Sin detección en UKIDSS dentro del radio dado   45
Sin detección en UKIDSS dentro del radio dado   47
Sin detección en UKIDSS dentro del radio dado   48
Sin detección en UKIDSS dentro del radio dado   49
Sin detección en UKIDSS dentro del radio dado   50
Sin detección en UKIDSS dentro del radio dado   51
Sin detección en UKIDSS dentro del radio dado   52
Sin detección en UKIDSS dentro del radio dado   53
Sin detección en UKIDSS dentro del radio dado   54
Sin detección en UKIDSS dentro del radio dado   58
Sin detección en UKIDSS dentro del radio dado   59
Sin detección en UKIDSS dentro del radio dado   61
Sin detección en UKIDSS dentro del radio dado   64
Sin detección en UKIDSS dentro del radio dado   65
Sin detección en UKIDSS dentro del radio dado   68
Sin detección en UKIDSS dentro del radio dado   72
Sin detección en UKIDSS dentro del radio dado   76
Sin detección en UKIDSS dentro del radio dado   82
Sin detección en UKIDSS dentro del radio dado   84
Sin detección en UKIDSS dentro del radio dado   85
Sin detección en UKIDSS dentro del radio dado   86
Sin detección en UKIDSS dentro del radio dado   88
Sin detección en UKIDSS dentro del radio dado   89
Sin detección en UKIDSS dentro del radio dado   91
Sin detección en UKIDSS dentro del radio dado   92
Sin detección en UKIDSS dentro del radio dado   97
Sin detección en UKIDSS dentro del radio dado   99
Sin detección en UKIDSS dentro del radio dado   100
Sin detección en UKIDSS dentro del radio dado   101
Sin detección en UKIDSS dentro del radio dado   102
Sin detección en UKIDSS dentro del radio dado   103
Sin detección en UKIDSS dentro del radio dado   107
Sin detección en UKIDSS dentro del radio dado   108
Sin detección en UKIDSS dentro del radio dado   109
Sin detección en UKIDSS dentro del radio dado   110
Sin detección en UKIDSS dentro del radio dado   111
Sin detección en UKIDSS dentro del radio dado   112
Sin detección en UKIDSS dentro del radio dado   113
Sin detección en UKIDSS dentro del radio dado   114
Sin detección en UKIDSS dentro del radio dado   115
Sin detección en UKIDSS dentro del radio dado   116
Sin detección en UKIDSS dentro del radio dado   117
Sin detección en UKIDSS dentro del radio dado   118
Sin detección en UKIDSS dentro del radio dado   119
Sin detección en UKIDSS dentro del radio dado   120

In [35]:
# Configuración
Vizier.ROW_LIMIT = 10000  # puedes aumentar si buscas muchos objetos
#Vizier.columns = ["RAJ2000", "DEJ2000", "Ymag", "Jmag", "Hmag", "Kmag", "e_Ymag", "e_Jmag", "e_Hmag", "e_Kmag"]

# Coordenadas del objeto
ra, dec = 12.947112,0.16112404 # grados
pos = SkyCoord(ra=ra*u.deg, dec=dec*u.deg, frame="icrs")

# Catálogo UKIDSS LAS en VizieR
cat_id = "II/319/"  # DR9 LAS (hay DR10/DR11 también)

# Consulta por radio
res = Vizier.query_region(pos, radius=1*u.arcsec, catalog=cat_id)

if res:
    tab = res[0]
    df = tab.to_pandas()
    df
else:
    print("Sin detección en UKIDSS dentro del radio dado.")


df

,ULAS,m,RAJ2000,DEJ2000,Ymag,e_Ymag,Jmag1,e_Jmag1,Jmag2,e_Jmag2,Hmag,e_Hmag,Kmag,e_Kmag,Epoch,pmRA,pmDE,cl
0,J005147.32+000939.9,1,12.947188,0.161089,18.503,0.043,18.181,0.064,NaN,NaN,17.636999,0.057,17.327,0.094,2005.7657,NaN,NaN,1

In [11]:
from astroquery.vizier import Vizier
vizier = Vizier() # this instantiates Vizier with its default parameters
catalog_list = vizier.find_catalogs('ukidss')

for k, v in catalog_list.items():
    print(k, ":", v.description)

II/316 : UKIDSS-DR6 Galactic Plane Survey (Lucas+ 2012)
II/319 : UKIDSS-DR9 LAS, GCS and DXS Surveys (Lawrence+ 2012)

In [12]:
from astroquery.vizier import Vizier
vizier = Vizier() # this instantiates Vizier with its default parameters
catalog_list = vizier.find_catalogs('wise')

for k, v in catalog_list.items():
    print(k, ":", v.description)

II/311 : WISE All-Sky Data Release (Cutri+ 2012)
II/328 : AllWISE Data Release (Cutri+ 2013)
II/363 : The band-merged unWISE Catalog (Schlafly+, 2019)
II/365 : The CatWISE2020 catalog (updated version 28-Jan-2021) (Marocco+, 2021)

In [14]:
vizier.ROW_LIMIT = 50
UKIDSS = vizier.get_catalogs("II/319/las9")
Uk_cat = UKIDSS[0]
Uk_cat = Uk_cat.to_pandas()
Uk_cat

,ULAS,m,RAJ2000,DEJ2000,Ymag,e_Ymag,Jmag1,e_Jmag1,Jmag2,e_Jmag2,Hmag,e_Hmag,Kmag,e_Kmag,Epoch,pmRA,pmDE,cl
0,J131601.51-001710.5,1,199.006326,-0.286277,NaN,NaN,18.550,0.095,NaN,NaN,17.636000,0.100,16.819000,0.080,2005.4480,NaN,NaN,1
1,J131606.65-001737.0,1,199.027721,-0.293624,NaN,NaN,NaN,NaN,NaN,NaN,18.854000,0.194,18.184000,0.181,2009.1556,NaN,NaN,-2
2,J131607.02-001721.4,2,199.029261,-0.289282,18.007000,0.024,NaN,NaN,NaN,NaN,16.862000,0.032,16.669001,0.046,2009.4343,NaN,NaN,-1
3,J131607.02-001721.4,1,199.029267,-0.289279,NaN,NaN,17.429,0.035,NaN,NaN,16.959000,0.054,16.806000,0.080,2005.4480,NaN,NaN,-1
4,J131605.36-001725.9,1,199.022372,-0.290555,NaN,NaN,NaN,NaN,NaN,NaN,18.785000,0.182,18.122000,0.171,2009.1556,NaN,NaN,-1
5,J131605.36-001725.8,2,199.022367,-0.290509,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,18.117001,0.265,2005.3768,NaN,NaN,-1
6,J131610.62-001658.7,1,199.044253,-0.282975,NaN,NaN,18.749,0.114,NaN,NaN,NaN,NaN,17.797001,0.198,2005.4480,NaN,NaN,-2
7,J131610.63-001658.6,2,199.044322,-0.282950,19.334000,0.074,NaN,NaN,NaN,NaN,18.393000,0.127,NaN,NaN,2009.4343,NaN,NaN,1
8,J131611.00-001656.6,2,199.045860,-0.282390,19.186001,0.065,NaN,NaN,NaN,NaN,18.112000,0.098,18.047001,0.159,2009.4343,NaN,NaN,-1
9,J131611.00-001656.5,1,199.045855,-0.282371,NaN,NaN,18.631,0.103,NaN,NaN,18.118999,0.156,17.756001,0.191,2005.4480,NaN,NaN,-1
10,J131611.25-001650.0,1,199.046883,-0.280575,NaN,NaN,NaN,NaN,NaN,NaN,18.648001,0.160,17.549999,0.102,2009.1556,NaN,NaN,-2
11,J131611.21-001649.7,2,199.046739,-0.280479,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,17.179001,0.112,2005.3768,NaN,NaN,1
12,J131602.15-001650.4,2,199.008995,-0.280691,15.955000,0.006,NaN,NaN,NaN,NaN,15.344000,0.009,15.304000,0.014,2009.4343,NaN,NaN,-1
13,J131602.16-001650.4,1,199.009005,-0.280678,NaN,NaN,15.703,0.008,NaN,NaN,15.311000,0.012,15.261000,0.020,2005.4480,NaN,NaN,-1
14,J131606.19-001628.8,2,199.025802,-0.274693,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,17.684000,0.178,2005.3768,NaN,NaN,-1
15,J131606.20-001628.7,1,199.025857,-0.274664,20.304001,0.176,NaN,NaN,NaN,NaN,18.746000,0.176,17.792000,0.127,2009.4343,NaN,NaN,1
16,J131608.05-001558.4,1,199.033564,-0.266240,NaN,NaN,19.560,0.238,NaN,NaN,NaN,NaN,NaN,NaN,2005.4480,NaN,NaN,-1
17,J131608.04-001558.5,2,199.033532,-0.266269,20.167000,0.155,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2009.4343,NaN,NaN,-1
18,J131605.09-001622.2,2,199.021218,-0.272836,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,17.888000,0.139,2009.1556,NaN,NaN,-1
19,J131605.10-001622.5,1,199.021254,-0.272917,NaN,NaN,NaN,NaN,NaN,NaN,18.723000,0.271,18.237000,0.294,2005.3768,NaN,NaN,-1
20,J131606.25-001610.9,1,199.026081,-0.269696,NaN,NaN,15.520,0.007,NaN,NaN,14.854000,0.008,14.718000,0.012,2005.4480,NaN,NaN,-1
21,J131606.25-001610.8,2,199.026079,-0.269694,15.922000,0.006,NaN,NaN,NaN,NaN,14.868000,0.006,14.770000,0.009,2009.4343,NaN,NaN,-1
22,J131604.71-001609.5,1,199.019664,-0.269317,NaN,NaN,19.042,0.148,NaN,NaN,17.726999,0.108,17.063999,0.100,2005.4480,NaN,NaN,1
23,J131604.70-001609.5,2,199.019619,-0.269325,19.452999,0.082,NaN,NaN,NaN,NaN,17.954000,0.086,17.042999,0.065,2009.4343,NaN,NaN,1
24,J131618.51-001716.6,1,199.077151,-0.287958,20.237000,0.207,NaN,NaN,NaN,NaN,NaN,NaN,17.945000,0.161,2009.4343,NaN,NaN,1
25,J131618.53-001715.7,1,199.077231,-0.287714,NaN,NaN,19.214,0.175,NaN,NaN,NaN,NaN,NaN,NaN,2005.4480,NaN,NaN,1
26,J131622.07-001650.9,2,199.091965,-0.280830,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,17.596001,0.165,2005.3768,NaN,NaN,1
27,J131622.08-001651.2,1,199.092034,-0.280904,NaN,NaN,NaN,NaN,NaN,NaN,18.584000,0.179,17.438000,0.101,2009.1556,NaN,NaN,1
28,J131618.40-001642.4,1,199.076694,-0.278469,19.680000,0.125,18.942,0.125,NaN,NaN,18.013000,0.106,17.493999,0.107,2009.4343,NaN,NaN,1
29,J131618.40-001642.4,2,199.076683,-0.278454,NaN,NaN,18.802,0.120,NaN,NaN,18.351999,0.194,17.518000,0.154,2005.4480,NaN,NaN,1
30,J131618.40-001641.8,1,199.076673,-0.278299,NaN,NaN,NaN,NaN,NaN,NaN,18.346001,0.193,NaN,NaN,2005.3768,NaN,NaN,1
31,J131620.65-001627.4,1,199.086058,-0.274286,19.311001,0.090,18.580,0.090,NaN,NaN,18.312000,0.139,17.624001,0.120,2009.4343,NaN,NaN,-2
32,J131620.67-001627.3,2,199.086126,-0.274265,NaN,NaN,18.596,0.099,NaN,NaN,18.179001,0.166,18.349001,0.330,2005.4480,NaN,NaN,-1
33,J131616.11-001654.2,2,199.067143,-0.281740,20.318001,0.177,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2009.4343,NaN,NaN,-1
34,J131616.09-001654.3,1,199.067062,-0.281754,20.528999,0.269,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2009.4343,NaN,NaN,-1
35,J131617.54-001556.6,2,199.073103,-0.265745,NaN,NaN,18.049,0.060,NaN,NaN,17.306000,0.074,16.326000,0.052,2005.4480,NaN,NaN,1
36,J131617.53-001556.7,1,199.073071,-0.265768,18.597000,0.048,17.982,0.052,NaN,NaN,17.198000,0.051,16.325001,0.037,2009.4343,NaN,NaN,1
37,J131617.17-001542.9,2,199.071562,-0.261944,NaN,NaN,17.624,0.041,NaN,NaN,17.181000,0.066,16.853001,0.083,2005.4480,NaN,NaN,-1
38,J131617.16-001543.1,1,199.071518,-0.261998,18.327000,0.038,17.670,0.040,NaN,NaN,17.131001,0.048,16.760000,0.055,2009.4343,NaN,NaN,-1
39,J131623.81-001615.0,2,199.099245,-0.270860,NaN,NaN,19.319,0.191,NaN,NaN,NaN,NaN,NaN,NaN,2005.4480,NaN,NaN,1
40,J131623.79-001614.9,1,199.099140,-0.270821,20.271000,0.214,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2009.4343,NaN,NaN,1
41,J131624.42-001605.5,1,199.101753,-0.268212,19.846001,0.146,NaN,NaN,NaN,NaN,18.271999,0.135,17.434000,0.101,2009.4343,NaN,NaN,1
42,J131624.41-001605.3,2,199.101733,-0.268162,NaN,NaN,19.098,0.156,NaN,NaN,NaN,NaN,17.791000,0.198,2005.4480,NaN,NaN,1
43,J131620.74-001616.8,1,199.086445,-0.271339,NaN,NaN,19.887,0.322,NaN,NaN,NaN,NaN,NaN,NaN,2005.4480,NaN,NaN,-1
44,J131622.23-001604.0,2,199.092633,-0.267793,NaN,NaN,17.708,0.044,NaN,NaN,17.341000,0.077,17.245001,0.120,2005.4480,NaN,NaN,-1
45,J131622.22-001604.2,1,199.092607,-0.267851,17.968000,0.028,17.637,0.039,NaN,NaN,17.292999,0.055,17.320000,0.091,2009.4343,NaN,NaN,-1
46,J131625.64-001531.2,1,199.106846,-0.258691,19.382999,0.096,18.806,0.110,NaN,NaN,17.871000,0.093,17.039000,0.071,2009.4343,NaN,NaN,1
47,J131625.64-001531.2,2,199.106856,-0.258691,NaN,NaN,18.929,0.134,NaN,NaN,18.048000,0.147,17.158001,0.111,2005.4480,NaN,NaN,1
48,J131622.01-001543.9,2,199.091738,-0.262218,NaN,NaN,18.592,0.099,NaN,NaN,17.622000,0.099,16.839001,0.083,2005.4480,NaN,NaN,1
49,J131622.00-001543.9,1,199.091690,-0.262211,19.198999,0.082,18.660,0.096,NaN,NaN,17.771000,0.085,16.759001,0.055,2009.4343,NaN,NaN,1

In [15]:
Vizier(catalog="II/319").get_catalog_metadata()

<Table length=1>
               title                ...  doi
               object               ... object
----------------------------------- ... ------
UKIDSS-DR9 LAS, GCS and DXS Surveys ...     --

In [38]:
from astroquery.ukidss import Ukidss
import astropy.coordinates as coord
import astropy.units as u
table = Ukidss.query_region(coord.SkyCoord(12.947112,0.16112404,
                                           unit=(u.deg, u.deg),
                                           frame="icrs"),
                            programme_id="LAS", radius=1 * u.arcsec)
table


for i in range(len(DF)):
    ra, dec = DF['ra'][i], DF['dec'][i]
    table = Ukidss.query_region(coord.SkyCoord(ra,dec,
                                           unit=(u.deg, u.deg),
                                           frame="icrs"),
                            programme_id="LAS", radius=1 * u.arcsec)
    if len(table)!=0:
        print("Found: ", i)

Found:  0
Found:  1
Found:  2

WARNING: NoResultsWarning: Query returned no results, so the table will be empty [astroquery.wfau.core]
WARNING: NoResultsWarning: Query returned no results, so the table will be empty [astroquery.wfau.core]

Found:  5
Found:  6

WARNING: NoResultsWarning: Query returned no results, so the table will be empty [astroquery.wfau.core]
WARNING: NoResultsWarning: Query returned no results, so the table will be empty [astroquery.wfau.core]
WARNING: NoResultsWarning: Query returned no results, so the table will be empty [astroquery.wfau.core]

Found:  10
Found:  11

WARNING: NoResultsWarning: Query returned no results, so the table will be empty [astroquery.wfau.core]
WARNING: NoResultsWarning: Query returned no results, so the table will be empty [astroquery.wfau.core]
WARNING: NoResultsWarning: Query returned no results, so the table will be empty [astroquery.wfau.core]
WARNING: NoResultsWarning: Query returned no results, so the table will be empty [astroquery.wfau.core]
WARNING: NoResultsWarning: Query returned no results, so the table will be empty [astroquery.wfau.core]

Found:  17
Found:  18

WARNING: NoResultsWarning: Query returned no results, so the table will be empty [astroquery.wfau.core]

Found:  20

WARNING: NoResultsWarning: Query returned no results, so the table will be empty [astroquery.wfau.core]
WARNING: NoResultsWarning: Query returned no results, so the table will be empty [astroquery.wfau.core]
WARNING: NoResultsWarning: Query returned no results, so the table will be empty [astroquery.wfau.core]
WARNING: NoResultsWarning: Query returned no results, so the table will be empty [astroquery.wfau.core]
WARNING: NoResultsWarning: Query returned no results, so the table will be empty [astroquery.wfau.core]
WARNING: NoResultsWarning: Query returned no results, so the table will be empty [astroquery.wfau.core]

Found:  27
Found:  28
Found:  29
Found:  30
Found:  31
Found:  32
Found:  33

WARNING: NoResultsWarning: Query returned no results, so the table will be empty [astroquery.wfau.core]

Found:  35
Found:  36
Found:  37

WARNING: NoResultsWarning: Query returned no results, so the table will be empty [astroquery.wfau.core]
WARNING: NoResultsWarning: Query returned no results, so the table will be empty [astroquery.wfau.core]
WARNING: NoResultsWarning: Query returned no results, so the table will be empty [astroquery.wfau.core]
WARNING: NoResultsWarning: Query returned no results, so the table will be empty [astroquery.wfau.core]
WARNING: NoResultsWarning: Query returned no results, so the table will be empty [astroquery.wfau.core]

Found:  43
Found:  44

WARNING: NoResultsWarning: Query returned no results, so the table will be empty [astroquery.wfau.core]

Found:  46

WARNING: NoResultsWarning: Query returned no results, so the table will be empty [astroquery.wfau.core]
WARNING: NoResultsWarning: Query returned no results, so the table will be empty [astroquery.wfau.core]
WARNING: NoResultsWarning: Query returned no results, so the table will be empty [astroquery.wfau.core]
WARNING: NoResultsWarning: Query returned no results, so the table will be empty [astroquery.wfau.core]
WARNING: NoResultsWarning: Query returned no results, so the table will be empty [astroquery.wfau.core]
WARNING: NoResultsWarning: Query returned no results, so the table will be empty [astroquery.wfau.core]
WARNING: NoResultsWarning: Query returned no results, so the table will be empty [astroquery.wfau.core]
WARNING: NoResultsWarning: Query returned no results, so the table will be empty [astroquery.wfau.core]

Found:  55
Found:  56
Found:  57

WARNING: NoResultsWarning: Query returned no results, so the table will be empty [astroquery.wfau.core]
WARNING: NoResultsWarning: Query returned no results, so the table will be empty [astroquery.wfau.core]

Found:  60

WARNING: NoResultsWarning: Query returned no results, so the table will be empty [astroquery.wfau.core]

Found:  62
Found:  63

WARNING: NoResultsWarning: Query returned no results, so the table will be empty [astroquery.wfau.core]
WARNING: NoResultsWarning: Query returned no results, so the table will be empty [astroquery.wfau.core]

Found:  66
Found:  67

WARNING: NoResultsWarning: Query returned no results, so the table will be empty [astroquery.wfau.core]

Found:  69
Found:  70
Found:  71

WARNING: NoResultsWarning: Query returned no results, so the table will be empty [astroquery.wfau.core]

Found:  73
Found:  74
Found:  75
Found:  76
Found:  77
Found:  78
Found:  79
Found:  80
Found:  81

WARNING: NoResultsWarning: Query returned no results, so the table will be empty [astroquery.wfau.core]

Found:  83

WARNING: NoResultsWarning: Query returned no results, so the table will be empty [astroquery.wfau.core]
WARNING: NoResultsWarning: Query returned no results, so the table will be empty [astroquery.wfau.core]
WARNING: NoResultsWarning: Query returned no results, so the table will be empty [astroquery.wfau.core]

Found:  87

WARNING: NoResultsWarning: Query returned no results, so the table will be empty [astroquery.wfau.core]
WARNING: NoResultsWarning: Query returned no results, so the table will be empty [astroquery.wfau.core]

Found:  90

WARNING: NoResultsWarning: Query returned no results, so the table will be empty [astroquery.wfau.core]
WARNING: NoResultsWarning: Query returned no results, so the table will be empty [astroquery.wfau.core]

Found:  93
Found:  94
Found:  95
Found:  96

WARNING: NoResultsWarning: Query returned no results, so the table will be empty [astroquery.wfau.core]

Found:  98

WARNING: NoResultsWarning: Query returned no results, so the table will be empty [astroquery.wfau.core]
WARNING: NoResultsWarning: Query returned no results, so the table will be empty [astroquery.wfau.core]
WARNING: NoResultsWarning: Query returned no results, so the table will be empty [astroquery.wfau.core]
WARNING: NoResultsWarning: Query returned no results, so the table will be empty [astroquery.wfau.core]
WARNING: NoResultsWarning: Query returned no results, so the table will be empty [astroquery.wfau.core]

Found:  104
Found:  105
Found:  106

WARNING: NoResultsWarning: Query returned no results, so the table will be empty [astroquery.wfau.core]
WARNING: NoResultsWarning: Query returned no results, so the table will be empty [astroquery.wfau.core]
WARNING: NoResultsWarning: Query returned no results, so the table will be empty [astroquery.wfau.core]
WARNING: NoResultsWarning: Query returned no results, so the table will be empty [astroquery.wfau.core]
WARNING: NoResultsWarning: Query returned no results, so the table will be empty [astroquery.wfau.core]
WARNING: NoResultsWarning: Query returned no results, so the table will be empty [astroquery.wfau.core]
WARNING: NoResultsWarning: Query returned no results, so the table will be empty [astroquery.wfau.core]
WARNING: NoResultsWarning: Query returned no results, so the table will be empty [astroquery.wfau.core]
WARNING: NoResultsWarning: Query returned no results, so the table will be empty [astroquery.wfau.core]
WARNING: NoResultsWarning: Query returned no results, so the table will be empty [astroquery.wfau.core]
WARNING: NoResultsWarning: Query returned no results, so the table will be empty [astroquery.wfau.core]
WARNING: NoResultsWarning: Query returned no results, so the table will be empty [astroquery.wfau.core]
WARNING: NoResultsWarning: Query returned no results, so the table will be empty [astroquery.wfau.core]
WARNING: NoResultsWarning: Query returned no results, so the table will be empty [astroquery.wfau.core]